// -------------------------------------------------------------
// 
// File Name: D:\OFDM- HDL\simulation\baseband\v8\src\Tx\Zed_ofdm64\Complex4Multiply_block1.v
// Created: 2025-04-21 20:44:15
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Complex4Multiply_block1
// Source Path: dsphdl.IFFT/RADIX22FFT_SDF1_7/Complex4Multiply
// Hierarchy Level: 4
// Model version: 3.61
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Complex4Multiply_block1
          (clk,
           reset,
           enb,
           din_7_1_re_dly,
           din_7_1_im_dly,
           din_7_vld_dly,
           twdl_7_1_re,
           twdl_7_1_im,
           dinXTwdl_re,
           dinXTwdl_im,
           dinXTwdl_7_1_vld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [31:0] din_7_1_re_dly;  // sfix32_En8
  input   signed [31:0] din_7_1_im_dly;  // sfix32_En8
  input   din_7_vld_dly;
  input   signed [31:0] twdl_7_1_re;  // sfix32_En30
  input   signed [31:0] twdl_7_1_im;  // sfix32_En30
  output  signed [31:0] dinXTwdl_re;  // sfix32_En8
  output  signed [31:0] dinXTwdl_im;  // sfix32_En8
  output  dinXTwdl_7_1_vld;


  reg signed [31:0] din_re_reg;  // sfix32_En8
  reg signed [31:0] din_im_reg;  // sfix32_En8
  reg signed [31:0] twdl_re_reg;  // sfix32_En30
  reg signed [31:0] twdl_im_reg;  // sfix32_En30
  reg signed [31:0] Complex4Multiply_din1_re_pipe1;  // sfix32
  reg signed [31:0] Complex4Multiply_din1_im_pipe1;  // sfix32
  reg signed [63:0] Complex4Multiply_mult1_re_pipe1;  // sfix64
  reg signed [63:0] Complex4Multiply_mult2_re_pipe1;  // sfix64
  reg signed [63:0] Complex4Multiply_mult1_im_pipe1;  // sfix64
  reg signed [63:0] Complex4Multiply_mult2_im_pipe1;  // sfix64
  reg signed [31:0] Complex4Multiply_twiddle_re_pipe1;  // sfix32
  reg signed [31:0] Complex4Multiply_twiddle_im_pipe1;  // sfix32
  reg signed [63:0] prod1_re;  // sfix64_En38
  reg signed [63:0] prod1_im;  // sfix64_En38
  reg signed [63:0] prod2_re;  // sfix64_En38
  reg signed [63:0] prod2_im;  // sfix64_En38
  reg  din_vld_dly1;
  reg  din_vld_dly2;
  reg  din_vld_dly3;
  reg  prod_vld;
  reg signed [64:0] Complex4Add_multRes_re_reg;  // sfix65
  reg signed [64:0] Complex4Add_multRes_im_reg;  // sfix65
  reg  Complex4Add_prod_vld_reg1;
  reg signed [63:0] Complex4Add_prod1_re_reg;  // sfix64
  reg signed [63:0] Complex4Add_prod1_im_reg;  // sfix64
  reg signed [63:0] Complex4Add_prod2_re_reg;  // sfix64
  reg signed [63:0] Complex4Add_prod2_im_reg;  // sfix64
  wire signed [64:0] Complex4Add_multRes_re_reg_next;  // sfix65_En38
  wire signed [64:0] Complex4Add_multRes_im_reg_next;  // sfix65_En38
  wire signed [64:0] Complex4Add_sub_cast;  // sfix65_En38
  wire signed [64:0] Complex4Add_sub_cast_1;  // sfix65_En38
  wire signed [64:0] Complex4Add_add_cast;  // sfix65_En38
  wire signed [64:0] Complex4Add_add_cast_1;  // sfix65_En38
  wire signed [64:0] mulResFP_re;  // sfix65_En38
  wire signed [64:0] mulResFP_im;  // sfix65_En38
  reg  dinXTwdl_7_1_vld_1;

  initial begin
    Complex4Multiply_din1_re_pipe1 = 32'sb00000000000000000000000000000000;
    Complex4Multiply_din1_im_pipe1 = 32'sb00000000000000000000000000000000;
    Complex4Multiply_twiddle_re_pipe1 = 32'sb00000000000000000000000000000000;
    Complex4Multiply_twiddle_im_pipe1 = 32'sb00000000000000000000000000000000;
    Complex4Multiply_mult1_re_pipe1 = 64'sh0000000000000000;
    Complex4Multiply_mult2_re_pipe1 = 64'sh0000000000000000;
    Complex4Multiply_mult1_im_pipe1 = 64'sh0000000000000000;
    Complex4Multiply_mult2_im_pipe1 = 64'sh0000000000000000;
    prod1_re = 64'sh0000000000000000;
    prod2_re = 64'sh0000000000000000;
    prod1_im = 64'sh0000000000000000;
    prod2_im = 64'sh0000000000000000;
  end

  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        din_re_reg <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          din_re_reg <= din_7_1_re_dly;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        din_im_reg <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          din_im_reg <= din_7_1_im_dly;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        twdl_re_reg <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          twdl_re_reg <= twdl_7_1_re;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        twdl_im_reg <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          twdl_im_reg <= twdl_7_1_im;
        end
      end
    end



  // Complex4Multiply
  always @(posedge clk)
    begin : Complex4Multiply_process
      if (enb) begin
        prod1_re <= Complex4Multiply_mult1_re_pipe1;
        prod2_re <= Complex4Multiply_mult2_re_pipe1;
        prod1_im <= Complex4Multiply_mult1_im_pipe1;
        prod2_im <= Complex4Multiply_mult2_im_pipe1;
        Complex4Multiply_mult1_re_pipe1 <= Complex4Multiply_din1_re_pipe1 * Complex4Multiply_twiddle_re_pipe1;
        Complex4Multiply_mult2_re_pipe1 <= Complex4Multiply_din1_im_pipe1 * Complex4Multiply_twiddle_im_pipe1;
        Complex4Multiply_mult1_im_pipe1 <= Complex4Multiply_din1_re_pipe1 * Complex4Multiply_twiddle_im_pipe1;
        Complex4Multiply_mult2_im_pipe1 <= Complex4Multiply_din1_im_pipe1 * Complex4Multiply_twiddle_re_pipe1;
        Complex4Multiply_twiddle_re_pipe1 <= twdl_re_reg;
        Complex4Multiply_twiddle_im_pipe1 <= twdl_im_reg;
        Complex4Multiply_din1_re_pipe1 <= din_re_reg;
        Complex4Multiply_din1_im_pipe1 <= din_im_reg;
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_4_process
      if (reset == 1'b1) begin
        din_vld_dly1 <= 1'b0;
      end
      else begin
        if (enb) begin
          din_vld_dly1 <= din_7_vld_dly;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_5_process
      if (reset == 1'b1) begin
        din_vld_dly2 <= 1'b0;
      end
      else begin
        if (enb) begin
          din_vld_dly2 <= din_vld_dly1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_6_process
      if (reset == 1'b1) begin
        din_vld_dly3 <= 1'b0;
      end
      else begin
        if (enb) begin
          din_vld_dly3 <= din_vld_dly2;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_7_process
      if (reset == 1'b1) begin
        prod_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          prod_vld <= din_vld_dly3;
        end
      end
    end



  // Complex4Add
  always @(posedge clk or posedge reset)
    begin : Complex4Add_process
      if (reset == 1'b1) begin
        Complex4Add_multRes_re_reg <= 65'sh00000000000000000;
        Complex4Add_multRes_im_reg <= 65'sh00000000000000000;
        Complex4Add_prod1_re_reg <= 64'sh0000000000000000;
        Complex4Add_prod1_im_reg <= 64'sh0000000000000000;
        Complex4Add_prod2_re_reg <= 64'sh0000000000000000;
        Complex4Add_prod2_im_reg <= 64'sh0000000000000000;
        Complex4Add_prod_vld_reg1 <= 1'b0;
        dinXTwdl_7_1_vld_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Complex4Add_multRes_re_reg <= Complex4Add_multRes_re_reg_next;
          Complex4Add_multRes_im_reg <= Complex4Add_multRes_im_reg_next;
          Complex4Add_prod1_re_reg <= prod1_re;
          Complex4Add_prod1_im_reg <= prod1_im;
          Complex4Add_prod2_re_reg <= prod2_re;
          Complex4Add_prod2_im_reg <= prod2_im;
          dinXTwdl_7_1_vld_1 <= Complex4Add_prod_vld_reg1;
          Complex4Add_prod_vld_reg1 <= prod_vld;
        end
      end
    end

  assign Complex4Add_sub_cast = {Complex4Add_prod1_re_reg[63], Complex4Add_prod1_re_reg};
  assign Complex4Add_sub_cast_1 = {Complex4Add_prod2_re_reg[63], Complex4Add_prod2_re_reg};
  assign Complex4Add_multRes_re_reg_next = Complex4Add_sub_cast - Complex4Add_sub_cast_1;
  assign Complex4Add_add_cast = {Complex4Add_prod1_im_reg[63], Complex4Add_prod1_im_reg};
  assign Complex4Add_add_cast_1 = {Complex4Add_prod2_im_reg[63], Complex4Add_prod2_im_reg};
  assign Complex4Add_multRes_im_reg_next = Complex4Add_add_cast + Complex4Add_add_cast_1;
  assign mulResFP_re = Complex4Add_multRes_re_reg;
  assign mulResFP_im = Complex4Add_multRes_im_reg;



  assign dinXTwdl_re = mulResFP_re[61:30];



  assign dinXTwdl_im = mulResFP_im[61:30];



  assign dinXTwdl_7_1_vld = dinXTwdl_7_1_vld_1;

endmodule  // Complex4Multiply_block1

