// -------------------------------------------------------------
// 
// File Name: D:\OFDM- HDL\simulation\baseband\v8\src\Tx\Zed_ofdm64\Counter_Limited.v
// Created: 2025-04-21 20:44:15
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Counter_Limited
// Source Path: Zed_ofdm64/top_all/tx_top/OFDM_TXSYS/Counter Limited
// Hierarchy Level: 1
// Model version: 3.61
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Counter_Limited
          (clk,
           reset,
           enb,
           y);


  input   clk;
  input   reset;
  input   enb;
  output  [15:0] y;  // uint16


  reg [15:0] Output_out1;  // uint16
  wire [15:0] Increment_Real_World_out1;  // uint16
  wire [15:0] Wrap_To_Zero_out1;  // uint16


  Increment_Real_World u_Increment_Real_World (.u(Output_out1),  // uint16
                                               .y(Increment_Real_World_out1)  // uint16
                                               );

  Wrap_To_Zero u_Wrap_To_Zero (.U(Increment_Real_World_out1),  // uint16
                               .Y(Wrap_To_Zero_out1)  // uint16
                               );

  always @(posedge clk or posedge reset)
    begin : Output_rsvd_process
      if (reset == 1'b1) begin
        Output_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Output_out1 <= Wrap_To_Zero_out1;
        end
      end
    end



  assign y = Output_out1;

endmodule  // Counter_Limited

