// -------------------------------------------------------------
// 
// File Name: D:\OFDM- HDL\simulation\baseband\v8\src\Tx\Zed_ofdm64\HDLFFTShiftMod.v
// Created: 2025-04-21 20:44:15
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: HDLFFTShiftMod
// Source Path: 
// Hierarchy Level: 2
// Model version: 3.61
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module HDLFFTShiftMod
          (clk,
           reset,
           enb,
           varargout_1_re,
           varargout_1_im,
           varargout_2,
           varargout_1_re_1,
           varargout_1_im_1,
           varargout_2_1);


  input   clk;
  input   reset;
  input   enb;
  input   signed [31:0] varargout_1_re;  // sfix32_En8
  input   signed [31:0] varargout_1_im;  // sfix32_En8
  input   varargout_2;
  output  signed [31:0] varargout_1_re_1;  // sfix32_En8
  output  signed [31:0] varargout_1_im_1;  // sfix32_En8
  output  varargout_2_1;


  wire obj_HDLFFTShiftModObj_resetSig;
  wire signed [31:0] tmp;  // sfix32_En8
  wire obj_HDLFFTShiftModObj_count;
  wire obj_HDLFFTShiftModObj_count_1;
  wire obj_HDLFFTShiftModObj_count_2;
  reg  obj_HDLFFTShiftModObj_count_3;
  wire tmp_1;
  wire tmp_2;
  wire tmp_3;
  wire signed [31:0] tmp_4;  // sfix32_En8
  wire signed [31:0] temp1;  // sfix32_En8
  wire signed [32:0] p28temp1_cast;  // sfix33_En8
  wire signed [32:0] p28temp1_cast_1;  // sfix33_En8
  wire signed [31:0] tmp_5;  // sfix32_En8
  wire signed [31:0] tmp_6;  // sfix32_En8
  wire signed [31:0] obj_HDLFFTShiftModObj_rePart;  // sfix32_En8
  wire signed [31:0] tmp_7;  // sfix32_En8
  reg signed [31:0] obj_HDLFFTShiftModObj_rePart_1;  // sfix32_En8
  wire signed [31:0] tmp_8;  // sfix32_En8
  wire signed [31:0] tmp_9;  // sfix32_En8
  wire signed [31:0] temp2;  // sfix32_En8
  wire signed [32:0] p27temp2_cast;  // sfix33_En8
  wire signed [32:0] p27temp2_cast_1;  // sfix33_En8
  wire signed [31:0] tmp_10;  // sfix32_En8
  wire signed [31:0] tmp_11;  // sfix32_En8
  wire signed [31:0] obj_HDLFFTShiftModObj_imPart;  // sfix32_En8
  wire signed [31:0] tmp_12;  // sfix32_En8
  reg signed [31:0] obj_HDLFFTShiftModObj_imPart_1;  // sfix32_En8
  wire signed [31:0] varargout_1_re_2;  // sfix32_En8
  wire signed [31:0] varargout_1_im_2;  // sfix32_En8
  wire obj_HDLFFTShiftModObj_validOut;
  wire tmp_13;
  reg  obj_HDLFFTShiftModObj_validOut_1;


  assign obj_HDLFFTShiftModObj_resetSig = 1'b0;



  assign tmp = varargout_1_re;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp19
  assign obj_HDLFFTShiftModObj_count = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp19
  assign obj_HDLFFTShiftModObj_count_1 = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp7
  assign obj_HDLFFTShiftModObj_count_2 = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp15
  assign tmp_1 = (obj_HDLFFTShiftModObj_count_3 == 1'b0 ? obj_HDLFFTShiftModObj_count :
              obj_HDLFFTShiftModObj_count_1);



  assign tmp_2 = (varargout_2 == 1'b0 ? obj_HDLFFTShiftModObj_count_3 :
              tmp_1);



  assign tmp_3 = (obj_HDLFFTShiftModObj_resetSig == 1'b0 ? tmp_2 :
              obj_HDLFFTShiftModObj_count_2);



  always @(posedge clk or posedge reset)
    begin : obj_HDLFFTShiftModObj_count_reg_process
      if (reset == 1'b1) begin
        obj_HDLFFTShiftModObj_count_3 <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_HDLFFTShiftModObj_count_3 <= tmp_3;
        end
      end
    end



  assign tmp_4 = varargout_1_re;



  assign p28temp1_cast = {varargout_1_re[31], varargout_1_re};
  assign p28temp1_cast_1 =  - (p28temp1_cast);
  assign temp1 = p28temp1_cast_1[31:0];



  assign tmp_5 = (obj_HDLFFTShiftModObj_count_3 == 1'b0 ? tmp_4 :
              temp1);



  assign tmp_6 = (varargout_2 == 1'b0 ? tmp :
              tmp_5);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp13
  assign obj_HDLFFTShiftModObj_rePart = 32'sb00000000000000000000000000000000;



  assign tmp_7 = (obj_HDLFFTShiftModObj_resetSig == 1'b0 ? tmp_6 :
              obj_HDLFFTShiftModObj_rePart);



  always @(posedge clk or posedge reset)
    begin : obj_HDLFFTShiftModObj_rePart_reg_process
      if (reset == 1'b1) begin
        obj_HDLFFTShiftModObj_rePart_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          obj_HDLFFTShiftModObj_rePart_1 <= tmp_7;
        end
      end
    end



  assign tmp_8 = varargout_1_im;



  // HDL code generation from MATLAB function: SystemCore_stepImpl
  assign tmp_9 = varargout_1_im;



  assign p27temp2_cast = {varargout_1_im[31], varargout_1_im};
  assign p27temp2_cast_1 =  - (p27temp2_cast);
  assign temp2 = p27temp2_cast_1[31:0];



  assign tmp_10 = (obj_HDLFFTShiftModObj_count_3 == 1'b0 ? tmp_9 :
              temp2);



  assign tmp_11 = (varargout_2 == 1'b0 ? tmp_8 :
              tmp_10);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp10
  assign obj_HDLFFTShiftModObj_imPart = 32'sb00000000000000000000000000000000;



  assign tmp_12 = (obj_HDLFFTShiftModObj_resetSig == 1'b0 ? tmp_11 :
              obj_HDLFFTShiftModObj_imPart);



  always @(posedge clk or posedge reset)
    begin : obj_HDLFFTShiftModObj_imPart_reg_process
      if (reset == 1'b1) begin
        obj_HDLFFTShiftModObj_imPart_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          obj_HDLFFTShiftModObj_imPart_1 <= tmp_12;
        end
      end
    end



  assign varargout_1_re_2 = obj_HDLFFTShiftModObj_rePart_1;
  assign varargout_1_im_2 = obj_HDLFFTShiftModObj_imPart_1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp4
  assign obj_HDLFFTShiftModObj_validOut = 1'b0;



  assign tmp_13 = (obj_HDLFFTShiftModObj_resetSig == 1'b0 ? varargout_2 :
              obj_HDLFFTShiftModObj_validOut);



  always @(posedge clk or posedge reset)
    begin : obj_HDLFFTShiftModObj_validOut_reg_process
      if (reset == 1'b1) begin
        obj_HDLFFTShiftModObj_validOut_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_HDLFFTShiftModObj_validOut_1 <= tmp_13;
        end
      end
    end



  assign varargout_1_re_1 = varargout_1_re_2;

  assign varargout_1_im_1 = varargout_1_im_2;

  assign varargout_2_1 = obj_HDLFFTShiftModObj_validOut_1;

endmodule  // HDLFFTShiftMod

