// -------------------------------------------------------------
// 
// File Name: D:\OFDM- HDL\simulation\baseband\v8\src\Tx\Zed_ofdm64\OFDM_TXSYS.v
// Created: 2025-04-21 20:44:15
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// rf_wave_out_re                ce_out        1
// rf_wave_out_im                ce_out        1
// datain_ready                  ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: OFDM_TXSYS
// Source Path: Zed_ofdm64/top_all/tx_top/OFDM_TXSYS
// Hierarchy Level: 0
// Model version: 3.61
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module OFDM_TXSYS
          (clk,
           reset,
           clk_enable,
           datain,
           ce_out,
           rf_wave_out_re,
           rf_wave_out_im,
           datain_ready);


  input   clk;
  input   reset;
  input   clk_enable;
  input   [1:0] datain;  // ufix2
  output  ce_out;
  output  signed [15:0] rf_wave_out_re;  // sfix16_En14
  output  signed [15:0] rf_wave_out_im;  // sfix16_En14
  output  datain_ready;


  wire enb;
  wire [15:0] Counter_Limited_out1;  // uint16
  wire Compare_To_Constant3_out1;
  reg  Delay30_out1;
  wire [15:0] count_step;  // uint16
  wire [15:0] count_from;  // uint16
  reg [15:0] frame_cnt_out1;  // uint16
  wire [15:0] count;  // uint16
  wire need_to_wrap;
  wire [15:0] count_value;  // uint16
  wire [15:0] count_1;  // uint16
  wire Compare_To_Constant_out1;
  reg  [1:0] Delay21_reg;  // ufix1 [2]
  wire Compare_To_Constant_out1_1;
  reg  Compare_To_Constant_out1_2;
  reg  [1026:0] reduced_reg;  // ufix1 [1027]
  wire Compare_To_Constant_out1_3;
  wire Compare_To_Constant2_out1;
  reg  [2:0] Delay10_reg;  // ufix1 [3]
  wire Delay10_out1;
  reg [15:0] Delay19_reg [0:2];  // ufix16 [3]
  reg [15:0] Delay19_reg_next [0:2];  // ufix16 [3]
  reg [15:0] Delay19_out1;  // uint16
  wire [8:0] prelookup_idx_sat;  // ufix9
  wire [8:0] prelookup_idx;  // ufix9
  wire signed [15:0] alpha1_D_Lookup_Table_1 [0:287];  // sfix16_En14 [288]
  wire signed [15:0] realOut;  // sfix16_En14
  reg signed [15:0] realOut_1;  // sfix16_En14
  wire signed [15:0] alpha1_D_Lookup_Table_3 [0:287];  // sfix16_En14 [288]
  wire signed [15:0] imagOut;  // sfix16_En14
  reg signed [15:0] imagOut_1;  // sfix16_En14
  wire [8:0] prelookup_idx_sat_1;  // ufix9
  wire [8:0] prelookup_idx_1;  // ufix9
  wire signed [15:0] alpha1_D_Lookup_Table2_1 [0:287];  // sfix16_En14 [288]
  wire signed [15:0] realOut_2;  // sfix16_En14
  reg signed [15:0] realOut_3;  // sfix16_En14
  wire signed [15:0] alpha1_D_Lookup_Table2_3 [0:287];  // sfix16_En14 [288]
  wire signed [15:0] imagOut_2;  // sfix16_En14
  reg signed [15:0] imagOut_3;  // sfix16_En14
  wire signed [15:0] Multiport_Switch2_out1_re;  // sfix16_En14
  wire signed [15:0] Multiport_Switch2_out1_im;  // sfix16_En14
  reg signed [15:0] Delay13_reg_re [0:1026];  // sfix16_En14 [1027]
  reg signed [15:0] Delay13_reg_im [0:1026];  // sfix16_En14 [1027]
  reg signed [15:0] Delay13_reg_next_re [0:1026];  // sfix16_En14 [1027]
  reg signed [15:0] Delay13_reg_next_im [0:1026];  // sfix16_En14 [1027]
  reg signed [15:0] Delay13_out1_re;  // sfix16_En14
  reg signed [15:0] Delay13_out1_im;  // sfix16_En14
  wire signed [31:0] Constant4_out1_re;  // sfix32_En8
  wire signed [31:0] Constant4_out1_im;  // sfix32_En8
  reg [1:0] Delay16_out1;  // ufix2
  wire signed [15:0] alpha_table_data_re [0:3];  // sfix16_En4 [4]
  wire signed [15:0] alpha_table_data_im [0:3];  // sfix16_En4 [4]
  wire signed [15:0] Rectangular_QAM_Modulator_Baseband_out1_re;  // sfix16_En4
  wire signed [15:0] Rectangular_QAM_Modulator_Baseband_out1_im;  // sfix16_En4
  wire signed [31:0] Gain8_out;  // sfix32_En8
  wire signed [31:0] Gain8_out_1;  // sfix32_En8
  reg signed [31:0] Delay6_out1_re;  // sfix32_En8
  reg signed [31:0] Delay6_out1_im;  // sfix32_En8
  wire signed [31:0] Multiport_Switch3_out1_re;  // sfix32_En8
  wire signed [31:0] Multiport_Switch3_out1_im;  // sfix32_En8
  wire Compare_To_Constant1_out1;
  reg  Delay25_out1;
  wire AND1_out1;
  reg  Delay_out1;
  reg  [1:0] Delay5_reg;  // ufix1 [2]
  wire Delay5_out1;
  wire signed [31:0] data_re;  // sfix32_En8
  wire signed [31:0] data_im;  // sfix32_En8
  wire signed [15:0] Data_Type_Conversion4_out1_re;  // sfix16_En14
  wire signed [15:0] Data_Type_Conversion4_out1_im;  // sfix16_En14
  reg signed [15:0] Delay14_out1_re;  // sfix16_En14
  reg signed [15:0] Delay14_out1_im;  // sfix16_En14
  wire signed [15:0] Saturation_out1;  // sfix16_En14
  wire signed [15:0] Saturation1_out1;  // sfix16_En14
  wire signed [15:0] Multiport_Switch1_out1_re;  // sfix16_En14
  wire signed [15:0] Multiport_Switch1_out1_im;  // sfix16_En14
  reg signed [15:0] Delay15_out1_re;  // sfix16_En14
  reg signed [15:0] Delay15_out1_im;  // sfix16_En14
  reg signed [31:0] Delay19_t_0_0;  // int32
  reg signed [31:0] Delay19_t_0_1;  // int32
  reg signed [31:0] Delay19_t_1;  // int32
  reg signed [31:0] Delay13_t_0_0;  // int32
  reg signed [31:0] Delay13_t_0_1;  // int32
  reg signed [31:0] Delay13_t_1;  // int32

  initial begin
    realOut_1 = 16'sb0000000000000000;
    imagOut_1 = 16'sb0000000000000000;
    realOut_3 = 16'sb0000000000000000;
    imagOut_3 = 16'sb0000000000000000;
  end

  Counter_Limited u_Counter_Limited (.clk(clk),
                                     .reset(reset),
                                     .enb(clk_enable),
                                     .y(Counter_Limited_out1)  // uint16
                                     );

  assign Compare_To_Constant3_out1 = Counter_Limited_out1 == 16'b0000000100011111;



  assign enb = clk_enable;

  always @(posedge clk or posedge reset)
    begin : Delay30_process
      if (reset == 1'b1) begin
        Delay30_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay30_out1 <= Compare_To_Constant3_out1;
        end
      end
    end



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 4
  assign count_step = 16'b0000000000000001;



  assign count_from = 16'b0000000000000000;



  assign count = frame_cnt_out1 + count_step;



  assign need_to_wrap = frame_cnt_out1 == 16'b0000000000000100;



  assign count_value = (need_to_wrap == 1'b0 ? count :
              count_from);



  assign count_1 = (Delay30_out1 == 1'b0 ? frame_cnt_out1 :
              count_value);



  always @(posedge clk or posedge reset)
    begin : frame_cnt_process
      if (reset == 1'b1) begin
        frame_cnt_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          frame_cnt_out1 <= count_1;
        end
      end
    end



  assign Compare_To_Constant_out1 = frame_cnt_out1 >= 16'b0000000000000010;



  always @(posedge clk or posedge reset)
    begin : Delay21_process
      if (reset == 1'b1) begin
        Delay21_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          Delay21_reg[0] <= Compare_To_Constant_out1;
          Delay21_reg[1] <= Delay21_reg[0];
        end
      end
    end

  assign Compare_To_Constant_out1_1 = Delay21_reg[1];



  always @(posedge clk or posedge reset)
    begin : reduced_process
      if (reset == 1'b1) begin
        Compare_To_Constant_out1_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          Compare_To_Constant_out1_2 <= Compare_To_Constant_out1_1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : reduced_1_process
      if (reset == 1'b1) begin
        reduced_reg <= {1027{1'b0}};
      end
      else begin
        if (enb) begin
          reduced_reg[0] <= Compare_To_Constant_out1_2;
          reduced_reg[32'sd1026:32'sd1] <= reduced_reg[32'sd1025:32'sd0];
        end
      end
    end

  assign Compare_To_Constant_out1_3 = reduced_reg[1026];



  assign Compare_To_Constant2_out1 = frame_cnt_out1 >= 16'b0000000000000001;



  always @(posedge clk or posedge reset)
    begin : Delay10_process
      if (reset == 1'b1) begin
        Delay10_reg <= {3{1'b0}};
      end
      else begin
        if (enb) begin
          Delay10_reg[0] <= Compare_To_Constant2_out1;
          Delay10_reg[32'sd2:32'sd1] <= Delay10_reg[32'sd1:32'sd0];
        end
      end
    end

  assign Delay10_out1 = Delay10_reg[2];



  always @(posedge clk or posedge reset)
    begin : Delay19_process
      if (reset == 1'b1) begin
        for(Delay19_t_1 = 32'sd0; Delay19_t_1 <= 32'sd2; Delay19_t_1 = Delay19_t_1 + 32'sd1) begin
          Delay19_reg[Delay19_t_1] <= 16'b0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(Delay19_t_0_1 = 32'sd0; Delay19_t_0_1 <= 32'sd2; Delay19_t_0_1 = Delay19_t_0_1 + 32'sd1) begin
            Delay19_reg[Delay19_t_0_1] <= Delay19_reg_next[Delay19_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay19_out1 = Delay19_reg[2];
    Delay19_reg_next[0] = Counter_Limited_out1;

    for(Delay19_t_0_0 = 32'sd0; Delay19_t_0_0 <= 32'sd1; Delay19_t_0_0 = Delay19_t_0_0 + 32'sd1) begin
      Delay19_reg_next[Delay19_t_0_0 + 32'sd1] = Delay19_reg[Delay19_t_0_0];
    end

  end



  assign prelookup_idx_sat = (Delay19_out1 == 16'b0000000000000000 ? 9'b000000000 :
              (Delay19_out1 >= 16'b0000000100011111 ? 9'b100011111 :
              Delay19_out1[8:0]));



  assign prelookup_idx = (prelookup_idx_sat > 9'b100011111 ? 9'b100011111 :
              prelookup_idx_sat);



  assign alpha1_D_Lookup_Table_1[0] = 16'sb0000000010010110;
  assign alpha1_D_Lookup_Table_1[1] = 16'sb0000001000111011;
  assign alpha1_D_Lookup_Table_1[2] = 16'sb0000010001111101;
  assign alpha1_D_Lookup_Table_1[3] = 16'sb0000000011010110;
  assign alpha1_D_Lookup_Table_1[4] = 16'sb1111011100010001;
  assign alpha1_D_Lookup_Table_1[5] = 16'sb1111100110010010;
  assign alpha1_D_Lookup_Table_1[6] = 16'sb0000011000101101;
  assign alpha1_D_Lookup_Table_1[7] = 16'sb0000100010001111;
  assign alpha1_D_Lookup_Table_1[8] = 16'sb0000011001011001;
  assign alpha1_D_Lookup_Table_1[9] = 16'sb0000001000100101;
  assign alpha1_D_Lookup_Table_1[10] = 16'sb1111101111001000;
  assign alpha1_D_Lookup_Table_1[11] = 16'sb0000001100001000;
  assign alpha1_D_Lookup_Table_1[12] = 16'sb0000011101101101;
  assign alpha1_D_Lookup_Table_1[13] = 16'sb1111101010010100;
  assign alpha1_D_Lookup_Table_1[14] = 16'sb1111101111001001;
  assign alpha1_D_Lookup_Table_1[15] = 16'sb0000001110100101;
  assign alpha1_D_Lookup_Table_1[16] = 16'sb1111010110110101;
  assign alpha1_D_Lookup_Table_1[17] = 16'sb1111001010000001;
  assign alpha1_D_Lookup_Table_1[18] = 16'sb0000000100110000;
  assign alpha1_D_Lookup_Table_1[19] = 16'sb1111011101001010;
  assign alpha1_D_Lookup_Table_1[20] = 16'sb1110101000100001;
  assign alpha1_D_Lookup_Table_1[21] = 16'sb1111111011110011;
  assign alpha1_D_Lookup_Table_1[22] = 16'sb0000110111101101;
  assign alpha1_D_Lookup_Table_1[23] = 16'sb1111110110111001;
  assign alpha1_D_Lookup_Table_1[24] = 16'sb1111011000011011;
  assign alpha1_D_Lookup_Table_1[25] = 16'sb1111111010010011;
  assign alpha1_D_Lookup_Table_1[26] = 16'sb1111100000111110;
  assign alpha1_D_Lookup_Table_1[27] = 16'sb1111001000000110;
  assign alpha1_D_Lookup_Table_1[28] = 16'sb0000010010010010;
  assign alpha1_D_Lookup_Table_1[29] = 16'sb0000111110011110;
  assign alpha1_D_Lookup_Table_1[30] = 16'sb1111111101110010;
  assign alpha1_D_Lookup_Table_1[31] = 16'sb1111010010011111;
  assign alpha1_D_Lookup_Table_1[32] = 16'sb1111011000000000;
  assign alpha1_D_Lookup_Table_1[33] = 16'sb1111010010011111;
  assign alpha1_D_Lookup_Table_1[34] = 16'sb1111111101110010;
  assign alpha1_D_Lookup_Table_1[35] = 16'sb0000111110011110;
  assign alpha1_D_Lookup_Table_1[36] = 16'sb0000010010010010;
  assign alpha1_D_Lookup_Table_1[37] = 16'sb1111001000000110;
  assign alpha1_D_Lookup_Table_1[38] = 16'sb1111100000111110;
  assign alpha1_D_Lookup_Table_1[39] = 16'sb1111111010010011;
  assign alpha1_D_Lookup_Table_1[40] = 16'sb1111011000011011;
  assign alpha1_D_Lookup_Table_1[41] = 16'sb1111110110111001;
  assign alpha1_D_Lookup_Table_1[42] = 16'sb0000110111101101;
  assign alpha1_D_Lookup_Table_1[43] = 16'sb1111111011110011;
  assign alpha1_D_Lookup_Table_1[44] = 16'sb1110101000100001;
  assign alpha1_D_Lookup_Table_1[45] = 16'sb1111011101001010;
  assign alpha1_D_Lookup_Table_1[46] = 16'sb0000000100110000;
  assign alpha1_D_Lookup_Table_1[47] = 16'sb1111001010000001;
  assign alpha1_D_Lookup_Table_1[48] = 16'sb1111010110110101;
  assign alpha1_D_Lookup_Table_1[49] = 16'sb0000001110100101;
  assign alpha1_D_Lookup_Table_1[50] = 16'sb1111101111001001;
  assign alpha1_D_Lookup_Table_1[51] = 16'sb1111101010010100;
  assign alpha1_D_Lookup_Table_1[52] = 16'sb0000011101101101;
  assign alpha1_D_Lookup_Table_1[53] = 16'sb0000001100001000;
  assign alpha1_D_Lookup_Table_1[54] = 16'sb1111101111001000;
  assign alpha1_D_Lookup_Table_1[55] = 16'sb0000001000100101;
  assign alpha1_D_Lookup_Table_1[56] = 16'sb0000011001011001;
  assign alpha1_D_Lookup_Table_1[57] = 16'sb0000100010001111;
  assign alpha1_D_Lookup_Table_1[58] = 16'sb0000011000101101;
  assign alpha1_D_Lookup_Table_1[59] = 16'sb1111100110010010;
  assign alpha1_D_Lookup_Table_1[60] = 16'sb1111011100010001;
  assign alpha1_D_Lookup_Table_1[61] = 16'sb0000000011010110;
  assign alpha1_D_Lookup_Table_1[62] = 16'sb0000010001111101;
  assign alpha1_D_Lookup_Table_1[63] = 16'sb0000001000111011;
  assign alpha1_D_Lookup_Table_1[64] = 16'sb0000000010010110;
  assign alpha1_D_Lookup_Table_1[65] = 16'sb0000011110010011;
  assign alpha1_D_Lookup_Table_1[66] = 16'sb0000111001101100;
  assign alpha1_D_Lookup_Table_1[67] = 16'sb1111110100101111;
  assign alpha1_D_Lookup_Table_1[68] = 16'sb1110111100111000;
  assign alpha1_D_Lookup_Table_1[69] = 16'sb1111110011110011;
  assign alpha1_D_Lookup_Table_1[70] = 16'sb1111100101000110;
  assign alpha1_D_Lookup_Table_1[71] = 16'sb1110100000011010;
  assign alpha1_D_Lookup_Table_1[72] = 16'sb1111100001011011;
  assign alpha1_D_Lookup_Table_1[73] = 16'sb0000010100110101;
  assign alpha1_D_Lookup_Table_1[74] = 16'sb1111001111111111;
  assign alpha1_D_Lookup_Table_1[75] = 16'sb1111000101001011;
  assign alpha1_D_Lookup_Table_1[76] = 16'sb1111110011011000;
  assign alpha1_D_Lookup_Table_1[77] = 16'sb0000000000111010;
  assign alpha1_D_Lookup_Table_1[78] = 16'sb0000010001100111;
  assign alpha1_D_Lookup_Table_1[79] = 16'sb1111111100011110;
  assign alpha1_D_Lookup_Table_1[80] = 16'sb1111001100010000;
  assign alpha1_D_Lookup_Table_1[81] = 16'sb1111101110110000;
  assign alpha1_D_Lookup_Table_1[82] = 16'sb0000101000111010;
  assign alpha1_D_Lookup_Table_1[83] = 16'sb0000100000101101;
  assign alpha1_D_Lookup_Table_1[84] = 16'sb1111110110111101;
  assign alpha1_D_Lookup_Table_1[85] = 16'sb1111000111101111;
  assign alpha1_D_Lookup_Table_1[86] = 16'sb1110111000101111;
  assign alpha1_D_Lookup_Table_1[87] = 16'sb1111011111010000;
  assign alpha1_D_Lookup_Table_1[88] = 16'sb0000010011101111;
  assign alpha1_D_Lookup_Table_1[89] = 16'sb0001000001000101;
  assign alpha1_D_Lookup_Table_1[90] = 16'sb0000111100001000;
  assign alpha1_D_Lookup_Table_1[91] = 16'sb0000000010010011;
  assign alpha1_D_Lookup_Table_1[92] = 16'sb1111110111110011;
  assign alpha1_D_Lookup_Table_1[93] = 16'sb0000001110101100;
  assign alpha1_D_Lookup_Table_1[94] = 16'sb0000001000000110;
  assign alpha1_D_Lookup_Table_1[95] = 16'sb0000011010110001;
  assign alpha1_D_Lookup_Table_1[96] = 16'sb0000110000000000;
  assign alpha1_D_Lookup_Table_1[97] = 16'sb0000011010000110;
  assign alpha1_D_Lookup_Table_1[98] = 16'sb0000010101110010;
  assign alpha1_D_Lookup_Table_1[99] = 16'sb0000001100101011;
  assign alpha1_D_Lookup_Table_1[100] = 16'sb1111101110101101;
  assign alpha1_D_Lookup_Table_1[101] = 16'sb1111110010100000;
  assign alpha1_D_Lookup_Table_1[102] = 16'sb1111100001011111;
  assign alpha1_D_Lookup_Table_1[103] = 16'sb1111011001110100;
  assign alpha1_D_Lookup_Table_1[104] = 16'sb0000100110010111;
  assign alpha1_D_Lookup_Table_1[105] = 16'sb0000101001111110;
  assign alpha1_D_Lookup_Table_1[106] = 16'sb1111100100000100;
  assign alpha1_D_Lookup_Table_1[107] = 16'sb0000010001101001;
  assign alpha1_D_Lookup_Table_1[108] = 16'sb0000111110101100;
  assign alpha1_D_Lookup_Table_1[109] = 16'sb0000010001001100;
  assign alpha1_D_Lookup_Table_1[110] = 16'sb0000100001100101;
  assign alpha1_D_Lookup_Table_1[111] = 16'sb0000111000010111;
  assign alpha1_D_Lookup_Table_1[112] = 16'sb0000001000011100;
  assign alpha1_D_Lookup_Table_1[113] = 16'sb1111111110001101;
  assign alpha1_D_Lookup_Table_1[114] = 16'sb0000000010111101;
  assign alpha1_D_Lookup_Table_1[115] = 16'sb1111111000111011;
  assign alpha1_D_Lookup_Table_1[116] = 16'sb0000000101101110;
  assign alpha1_D_Lookup_Table_1[117] = 16'sb1111101100110111;
  assign alpha1_D_Lookup_Table_1[118] = 16'sb1111110111100101;
  assign alpha1_D_Lookup_Table_1[119] = 16'sb0001010110011111;
  assign alpha1_D_Lookup_Table_1[120] = 16'sb0000111001011000;
  assign alpha1_D_Lookup_Table_1[121] = 16'sb1111011100100001;
  assign alpha1_D_Lookup_Table_1[122] = 16'sb0000011011011000;
  assign alpha1_D_Lookup_Table_1[123] = 16'sb0001001001000110;
  assign alpha1_D_Lookup_Table_1[124] = 16'sb0000001000011100;
  assign alpha1_D_Lookup_Table_1[125] = 16'sb0000010101011001;
  assign alpha1_D_Lookup_Table_1[126] = 16'sb0000111110111001;
  assign alpha1_D_Lookup_Table_1[127] = 16'sb0000100001110001;
  assign alpha1_D_Lookup_Table_1[128] = 16'sb0000001101101010;
  assign alpha1_D_Lookup_Table_1[129] = 16'sb1111111010000011;
  assign alpha1_D_Lookup_Table_1[130] = 16'sb1111110010000001;
  assign alpha1_D_Lookup_Table_1[131] = 16'sb0000100101101111;
  assign alpha1_D_Lookup_Table_1[132] = 16'sb0000100000110111;
  assign alpha1_D_Lookup_Table_1[133] = 16'sb1111100110001111;
  assign alpha1_D_Lookup_Table_1[134] = 16'sb0000001000001000;
  assign alpha1_D_Lookup_Table_1[135] = 16'sb0000101111110000;
  assign alpha1_D_Lookup_Table_1[136] = 16'sb1111110101001011;
  assign alpha1_D_Lookup_Table_1[137] = 16'sb1111001110111100;
  assign alpha1_D_Lookup_Table_1[138] = 16'sb1111011011111001;
  assign alpha1_D_Lookup_Table_1[139] = 16'sb1111001001001100;
  assign alpha1_D_Lookup_Table_1[140] = 16'sb1110111100111110;
  assign alpha1_D_Lookup_Table_1[141] = 16'sb1111011010011001;
  assign alpha1_D_Lookup_Table_1[142] = 16'sb1111100100010011;
  assign alpha1_D_Lookup_Table_1[143] = 16'sb1111101001000001;
  assign alpha1_D_Lookup_Table_1[144] = 16'sb0000010100011111;
  assign alpha1_D_Lookup_Table_1[145] = 16'sb0000010110001011;
  assign alpha1_D_Lookup_Table_1[146] = 16'sb1111010011011010;
  assign alpha1_D_Lookup_Table_1[147] = 16'sb1111001100010100;
  assign alpha1_D_Lookup_Table_1[148] = 16'sb0000001110000111;
  assign alpha1_D_Lookup_Table_1[149] = 16'sb0000100100000001;
  assign alpha1_D_Lookup_Table_1[150] = 16'sb0000011000000100;
  assign alpha1_D_Lookup_Table_1[151] = 16'sb0000101011100010;
  assign alpha1_D_Lookup_Table_1[152] = 16'sb0001000100000111;
  assign alpha1_D_Lookup_Table_1[153] = 16'sb0000111000111011;
  assign alpha1_D_Lookup_Table_1[154] = 16'sb0000000110011111;
  assign alpha1_D_Lookup_Table_1[155] = 16'sb1111101000011001;
  assign alpha1_D_Lookup_Table_1[156] = 16'sb0000000100110010;
  assign alpha1_D_Lookup_Table_1[157] = 16'sb1111110100110110;
  assign alpha1_D_Lookup_Table_1[158] = 16'sb1110110111101100;
  assign alpha1_D_Lookup_Table_1[159] = 16'sb1111100101100110;
  assign alpha1_D_Lookup_Table_1[160] = 16'sb0000101000000000;
  assign alpha1_D_Lookup_Table_1[161] = 16'sb1111100101100110;
  assign alpha1_D_Lookup_Table_1[162] = 16'sb1110110111101100;
  assign alpha1_D_Lookup_Table_1[163] = 16'sb1111110100110110;
  assign alpha1_D_Lookup_Table_1[164] = 16'sb0000000100110010;
  assign alpha1_D_Lookup_Table_1[165] = 16'sb1111101000011001;
  assign alpha1_D_Lookup_Table_1[166] = 16'sb0000000110011111;
  assign alpha1_D_Lookup_Table_1[167] = 16'sb0000111000111011;
  assign alpha1_D_Lookup_Table_1[168] = 16'sb0001000100000111;
  assign alpha1_D_Lookup_Table_1[169] = 16'sb0000101011100010;
  assign alpha1_D_Lookup_Table_1[170] = 16'sb0000011000000100;
  assign alpha1_D_Lookup_Table_1[171] = 16'sb0000100100000001;
  assign alpha1_D_Lookup_Table_1[172] = 16'sb0000001110000111;
  assign alpha1_D_Lookup_Table_1[173] = 16'sb1111001100010100;
  assign alpha1_D_Lookup_Table_1[174] = 16'sb1111010011011010;
  assign alpha1_D_Lookup_Table_1[175] = 16'sb0000010110001011;
  assign alpha1_D_Lookup_Table_1[176] = 16'sb0000010100011111;
  assign alpha1_D_Lookup_Table_1[177] = 16'sb1111101001000001;
  assign alpha1_D_Lookup_Table_1[178] = 16'sb1111100100010011;
  assign alpha1_D_Lookup_Table_1[179] = 16'sb1111011010011001;
  assign alpha1_D_Lookup_Table_1[180] = 16'sb1110111100111110;
  assign alpha1_D_Lookup_Table_1[181] = 16'sb1111001001001100;
  assign alpha1_D_Lookup_Table_1[182] = 16'sb1111011011111001;
  assign alpha1_D_Lookup_Table_1[183] = 16'sb1111001110111100;
  assign alpha1_D_Lookup_Table_1[184] = 16'sb1111110101001011;
  assign alpha1_D_Lookup_Table_1[185] = 16'sb0000101111110000;
  assign alpha1_D_Lookup_Table_1[186] = 16'sb0000001000001000;
  assign alpha1_D_Lookup_Table_1[187] = 16'sb1111100110001111;
  assign alpha1_D_Lookup_Table_1[188] = 16'sb0000100000110111;
  assign alpha1_D_Lookup_Table_1[189] = 16'sb0000100101101111;
  assign alpha1_D_Lookup_Table_1[190] = 16'sb1111110010000001;
  assign alpha1_D_Lookup_Table_1[191] = 16'sb1111111010000011;
  assign alpha1_D_Lookup_Table_1[192] = 16'sb0000001101101010;
  assign alpha1_D_Lookup_Table_1[193] = 16'sb0000100001110001;
  assign alpha1_D_Lookup_Table_1[194] = 16'sb0000111110111001;
  assign alpha1_D_Lookup_Table_1[195] = 16'sb0000010101011001;
  assign alpha1_D_Lookup_Table_1[196] = 16'sb0000001000011100;
  assign alpha1_D_Lookup_Table_1[197] = 16'sb0001001001000110;
  assign alpha1_D_Lookup_Table_1[198] = 16'sb0000011011011000;
  assign alpha1_D_Lookup_Table_1[199] = 16'sb1111011100100001;
  assign alpha1_D_Lookup_Table_1[200] = 16'sb0000111001011000;
  assign alpha1_D_Lookup_Table_1[201] = 16'sb0001010110011111;
  assign alpha1_D_Lookup_Table_1[202] = 16'sb1111110111100101;
  assign alpha1_D_Lookup_Table_1[203] = 16'sb1111101100110111;
  assign alpha1_D_Lookup_Table_1[204] = 16'sb0000000101101110;
  assign alpha1_D_Lookup_Table_1[205] = 16'sb1111111000111011;
  assign alpha1_D_Lookup_Table_1[206] = 16'sb0000000010111101;
  assign alpha1_D_Lookup_Table_1[207] = 16'sb1111111110001101;
  assign alpha1_D_Lookup_Table_1[208] = 16'sb0000001000011100;
  assign alpha1_D_Lookup_Table_1[209] = 16'sb0000111000010111;
  assign alpha1_D_Lookup_Table_1[210] = 16'sb0000100001100101;
  assign alpha1_D_Lookup_Table_1[211] = 16'sb0000010001001100;
  assign alpha1_D_Lookup_Table_1[212] = 16'sb0000111110101100;
  assign alpha1_D_Lookup_Table_1[213] = 16'sb0000010001101001;
  assign alpha1_D_Lookup_Table_1[214] = 16'sb1111100100000100;
  assign alpha1_D_Lookup_Table_1[215] = 16'sb0000101001111110;
  assign alpha1_D_Lookup_Table_1[216] = 16'sb0000100110010111;
  assign alpha1_D_Lookup_Table_1[217] = 16'sb1111011001110100;
  assign alpha1_D_Lookup_Table_1[218] = 16'sb1111100001011111;
  assign alpha1_D_Lookup_Table_1[219] = 16'sb1111110010100000;
  assign alpha1_D_Lookup_Table_1[220] = 16'sb1111101110101101;
  assign alpha1_D_Lookup_Table_1[221] = 16'sb0000001100101011;
  assign alpha1_D_Lookup_Table_1[222] = 16'sb0000010101110010;
  assign alpha1_D_Lookup_Table_1[223] = 16'sb0000011010000110;
  assign alpha1_D_Lookup_Table_1[224] = 16'sb0000110000000000;
  assign alpha1_D_Lookup_Table_1[225] = 16'sb0000011010110001;
  assign alpha1_D_Lookup_Table_1[226] = 16'sb0000001000000110;
  assign alpha1_D_Lookup_Table_1[227] = 16'sb0000001110101100;
  assign alpha1_D_Lookup_Table_1[228] = 16'sb1111110111110011;
  assign alpha1_D_Lookup_Table_1[229] = 16'sb0000000010010011;
  assign alpha1_D_Lookup_Table_1[230] = 16'sb0000111100001000;
  assign alpha1_D_Lookup_Table_1[231] = 16'sb0001000001000101;
  assign alpha1_D_Lookup_Table_1[232] = 16'sb0000010011101111;
  assign alpha1_D_Lookup_Table_1[233] = 16'sb1111011111010000;
  assign alpha1_D_Lookup_Table_1[234] = 16'sb1110111000101111;
  assign alpha1_D_Lookup_Table_1[235] = 16'sb1111000111101111;
  assign alpha1_D_Lookup_Table_1[236] = 16'sb1111110110111101;
  assign alpha1_D_Lookup_Table_1[237] = 16'sb0000100000101101;
  assign alpha1_D_Lookup_Table_1[238] = 16'sb0000101000111010;
  assign alpha1_D_Lookup_Table_1[239] = 16'sb1111101110110000;
  assign alpha1_D_Lookup_Table_1[240] = 16'sb1111001100010000;
  assign alpha1_D_Lookup_Table_1[241] = 16'sb1111111100011110;
  assign alpha1_D_Lookup_Table_1[242] = 16'sb0000010001100111;
  assign alpha1_D_Lookup_Table_1[243] = 16'sb0000000000111010;
  assign alpha1_D_Lookup_Table_1[244] = 16'sb1111110011011000;
  assign alpha1_D_Lookup_Table_1[245] = 16'sb1111000101001011;
  assign alpha1_D_Lookup_Table_1[246] = 16'sb1111001111111111;
  assign alpha1_D_Lookup_Table_1[247] = 16'sb0000010100110101;
  assign alpha1_D_Lookup_Table_1[248] = 16'sb1111100001011011;
  assign alpha1_D_Lookup_Table_1[249] = 16'sb1110100000011010;
  assign alpha1_D_Lookup_Table_1[250] = 16'sb1111100101000110;
  assign alpha1_D_Lookup_Table_1[251] = 16'sb1111110011110011;
  assign alpha1_D_Lookup_Table_1[252] = 16'sb1110111100111000;
  assign alpha1_D_Lookup_Table_1[253] = 16'sb1111110100101111;
  assign alpha1_D_Lookup_Table_1[254] = 16'sb0000111001101100;
  assign alpha1_D_Lookup_Table_1[255] = 16'sb0000011110010011;
  assign alpha1_D_Lookup_Table_1[256] = 16'sb0000000010010110;
  assign alpha1_D_Lookup_Table_1[257] = 16'sb0000001000111011;
  assign alpha1_D_Lookup_Table_1[258] = 16'sb0000010001111101;
  assign alpha1_D_Lookup_Table_1[259] = 16'sb0000000011010110;
  assign alpha1_D_Lookup_Table_1[260] = 16'sb1111011100010001;
  assign alpha1_D_Lookup_Table_1[261] = 16'sb1111100110010010;
  assign alpha1_D_Lookup_Table_1[262] = 16'sb0000011000101101;
  assign alpha1_D_Lookup_Table_1[263] = 16'sb0000100010001111;
  assign alpha1_D_Lookup_Table_1[264] = 16'sb0000011001011001;
  assign alpha1_D_Lookup_Table_1[265] = 16'sb0000001000100101;
  assign alpha1_D_Lookup_Table_1[266] = 16'sb1111101111001000;
  assign alpha1_D_Lookup_Table_1[267] = 16'sb0000001100001000;
  assign alpha1_D_Lookup_Table_1[268] = 16'sb0000011101101101;
  assign alpha1_D_Lookup_Table_1[269] = 16'sb1111101010010100;
  assign alpha1_D_Lookup_Table_1[270] = 16'sb1111101111001001;
  assign alpha1_D_Lookup_Table_1[271] = 16'sb0000001110100101;
  assign alpha1_D_Lookup_Table_1[272] = 16'sb1111010110110101;
  assign alpha1_D_Lookup_Table_1[273] = 16'sb1111001010000001;
  assign alpha1_D_Lookup_Table_1[274] = 16'sb0000000100110000;
  assign alpha1_D_Lookup_Table_1[275] = 16'sb1111011101001010;
  assign alpha1_D_Lookup_Table_1[276] = 16'sb1110101000100001;
  assign alpha1_D_Lookup_Table_1[277] = 16'sb1111111011110011;
  assign alpha1_D_Lookup_Table_1[278] = 16'sb0000110111101101;
  assign alpha1_D_Lookup_Table_1[279] = 16'sb1111110110111001;
  assign alpha1_D_Lookup_Table_1[280] = 16'sb1111011000011011;
  assign alpha1_D_Lookup_Table_1[281] = 16'sb1111111010010011;
  assign alpha1_D_Lookup_Table_1[282] = 16'sb1111100000111110;
  assign alpha1_D_Lookup_Table_1[283] = 16'sb1111001000000110;
  assign alpha1_D_Lookup_Table_1[284] = 16'sb0000010010010010;
  assign alpha1_D_Lookup_Table_1[285] = 16'sb0000111110011110;
  assign alpha1_D_Lookup_Table_1[286] = 16'sb1111111101110010;
  assign alpha1_D_Lookup_Table_1[287] = 16'sb1111010010011111;
  assign realOut = alpha1_D_Lookup_Table_1[prelookup_idx];



  always @(posedge clk)
    begin : PipelineRegister_process
      if (enb) begin
        realOut_1 <= realOut;
      end
    end



  assign alpha1_D_Lookup_Table_3[0] = 16'sb0001000001111100;
  assign alpha1_D_Lookup_Table_3[1] = 16'sb1111100101011110;
  assign alpha1_D_Lookup_Table_3[2] = 16'sb1110110110001001;
  assign alpha1_D_Lookup_Table_3[3] = 16'sb1111100101011111;
  assign alpha1_D_Lookup_Table_3[4] = 16'sb1111110111111010;
  assign alpha1_D_Lookup_Table_3[5] = 16'sb0000010010000011;
  assign alpha1_D_Lookup_Table_3[6] = 16'sb0000011010100001;
  assign alpha1_D_Lookup_Table_3[7] = 16'sb1111001110000011;
  assign alpha1_D_Lookup_Table_3[8] = 16'sb1110110001100000;
  assign alpha1_D_Lookup_Table_3[9] = 16'sb1111110000100001;
  assign alpha1_D_Lookup_Table_3[10] = 16'sb0000101111011000;
  assign alpha1_D_Lookup_Table_3[11] = 16'sb0001001010100011;
  assign alpha1_D_Lookup_Table_3[12] = 16'sb0000011001110011;
  assign alpha1_D_Lookup_Table_3[13] = 16'sb1111000110101010;
  assign alpha1_D_Lookup_Table_3[14] = 16'sb1111000100110011;
  assign alpha1_D_Lookup_Table_3[15] = 16'sb1111111010101111;
  assign alpha1_D_Lookup_Table_3[16] = 16'sb0000000000110100;
  assign alpha1_D_Lookup_Table_3[17] = 16'sb1111001110100011;
  assign alpha1_D_Lookup_Table_3[18] = 16'sb1111000111011111;
  assign alpha1_D_Lookup_Table_3[19] = 16'sb0000000101101000;
  assign alpha1_D_Lookup_Table_3[20] = 16'sb0000010100011110;
  assign alpha1_D_Lookup_Table_3[21] = 16'sb0000000011011001;
  assign alpha1_D_Lookup_Table_3[22] = 16'sb0000100111010000;
  assign alpha1_D_Lookup_Table_3[23] = 16'sb0000110101111101;
  assign alpha1_D_Lookup_Table_3[24] = 16'sb0000101010001110;
  assign alpha1_D_Lookup_Table_3[25] = 16'sb0000011001000001;
  assign alpha1_D_Lookup_Table_3[26] = 16'sb1111010000101000;
  assign alpha1_D_Lookup_Table_3[27] = 16'sb1111010110110011;
  assign alpha1_D_Lookup_Table_3[28] = 16'sb0000100111111011;
  assign alpha1_D_Lookup_Table_3[29] = 16'sb1111110111001101;
  assign alpha1_D_Lookup_Table_3[30] = 16'sb1111011110110110;
  assign alpha1_D_Lookup_Table_3[31] = 16'sb0000110001100111;
  assign alpha1_D_Lookup_Table_3[32] = 16'sb0000000000000000;
  assign alpha1_D_Lookup_Table_3[33] = 16'sb1111001110011001;
  assign alpha1_D_Lookup_Table_3[34] = 16'sb0000100001001010;
  assign alpha1_D_Lookup_Table_3[35] = 16'sb0000001000110011;
  assign alpha1_D_Lookup_Table_3[36] = 16'sb1111011000000101;
  assign alpha1_D_Lookup_Table_3[37] = 16'sb0000101001001101;
  assign alpha1_D_Lookup_Table_3[38] = 16'sb0000101111011000;
  assign alpha1_D_Lookup_Table_3[39] = 16'sb1111100110111111;
  assign alpha1_D_Lookup_Table_3[40] = 16'sb1111010101110010;
  assign alpha1_D_Lookup_Table_3[41] = 16'sb1111001010000011;
  assign alpha1_D_Lookup_Table_3[42] = 16'sb1111011000110000;
  assign alpha1_D_Lookup_Table_3[43] = 16'sb1111111100100111;
  assign alpha1_D_Lookup_Table_3[44] = 16'sb1111101011100010;
  assign alpha1_D_Lookup_Table_3[45] = 16'sb1111111010011000;
  assign alpha1_D_Lookup_Table_3[46] = 16'sb0000111000100001;
  assign alpha1_D_Lookup_Table_3[47] = 16'sb0000110001011101;
  assign alpha1_D_Lookup_Table_3[48] = 16'sb1111111111001100;
  assign alpha1_D_Lookup_Table_3[49] = 16'sb0000000101010001;
  assign alpha1_D_Lookup_Table_3[50] = 16'sb0000111011001101;
  assign alpha1_D_Lookup_Table_3[51] = 16'sb0000111001010110;
  assign alpha1_D_Lookup_Table_3[52] = 16'sb1111100110001101;
  assign alpha1_D_Lookup_Table_3[53] = 16'sb1110110101011101;
  assign alpha1_D_Lookup_Table_3[54] = 16'sb1111010000101000;
  assign alpha1_D_Lookup_Table_3[55] = 16'sb0000001111011111;
  assign alpha1_D_Lookup_Table_3[56] = 16'sb0001001110100000;
  assign alpha1_D_Lookup_Table_3[57] = 16'sb0000110001111101;
  assign alpha1_D_Lookup_Table_3[58] = 16'sb1111100101011111;
  assign alpha1_D_Lookup_Table_3[59] = 16'sb1111101101111101;
  assign alpha1_D_Lookup_Table_3[60] = 16'sb0000001000000110;
  assign alpha1_D_Lookup_Table_3[61] = 16'sb0000011010100001;
  assign alpha1_D_Lookup_Table_3[62] = 16'sb0001001001110111;
  assign alpha1_D_Lookup_Table_3[63] = 16'sb0000011010100010;
  assign alpha1_D_Lookup_Table_3[64] = 16'sb1110111110000100;
  assign alpha1_D_Lookup_Table_3[65] = 16'sb1111001001001111;
  assign alpha1_D_Lookup_Table_3[66] = 16'sb1111101001010110;
  assign alpha1_D_Lookup_Table_3[67] = 16'sb0000001010111011;
  assign alpha1_D_Lookup_Table_3[68] = 16'sb0000110001101001;
  assign alpha1_D_Lookup_Table_3[69] = 16'sb0000000010010110;
  assign alpha1_D_Lookup_Table_3[70] = 16'sb1111101111011100;
  assign alpha1_D_Lookup_Table_3[71] = 16'sb0000011111110101;
  assign alpha1_D_Lookup_Table_3[72] = 16'sb0000000110010101;
  assign alpha1_D_Lookup_Table_3[73] = 16'sb1111110000111010;
  assign alpha1_D_Lookup_Table_3[74] = 16'sb1111111100110010;
  assign alpha1_D_Lookup_Table_3[75] = 16'sb1111100100001010;
  assign alpha1_D_Lookup_Table_3[76] = 16'sb0000000101111101;
  assign alpha1_D_Lookup_Table_3[77] = 16'sb0000001110011111;
  assign alpha1_D_Lookup_Table_3[78] = 16'sb1110111010111110;
  assign alpha1_D_Lookup_Table_3[79] = 16'sb1111100000001010;
  assign alpha1_D_Lookup_Table_3[80] = 16'sb0000110001101010;
  assign alpha1_D_Lookup_Table_3[81] = 16'sb0000010100010111;
  assign alpha1_D_Lookup_Table_3[82] = 16'sb0000001100100111;
  assign alpha1_D_Lookup_Table_3[83] = 16'sb1111110110100000;
  assign alpha1_D_Lookup_Table_3[84] = 16'sb1111001100010111;
  assign alpha1_D_Lookup_Table_3[85] = 16'sb0000001011110011;
  assign alpha1_D_Lookup_Table_3[86] = 16'sb0000000001000001;
  assign alpha1_D_Lookup_Table_3[87] = 16'sb1110101010000010;
  assign alpha1_D_Lookup_Table_3[88] = 16'sb1111100101111101;
  assign alpha1_D_Lookup_Table_3[89] = 16'sb0000010000101101;
  assign alpha1_D_Lookup_Table_3[90] = 16'sb1111101000000100;
  assign alpha1_D_Lookup_Table_3[91] = 16'sb1111111101011011;
  assign alpha1_D_Lookup_Table_3[92] = 16'sb1111010010100010;
  assign alpha1_D_Lookup_Table_3[93] = 16'sb1110100100011001;
  assign alpha1_D_Lookup_Table_3[94] = 16'sb0000001110000101;
  assign alpha1_D_Lookup_Table_3[95] = 16'sb0000101000111010;
  assign alpha1_D_Lookup_Table_3[96] = 16'sb1111110000000000;
  assign alpha1_D_Lookup_Table_3[97] = 16'sb0000011101010000;
  assign alpha1_D_Lookup_Table_3[98] = 16'sb0000011101101111;
  assign alpha1_D_Lookup_Table_3[99] = 16'sb1111111100010010;
  assign alpha1_D_Lookup_Table_3[100] = 16'sb0000111010111001;
  assign alpha1_D_Lookup_Table_3[101] = 16'sb0000101100101110;
  assign alpha1_D_Lookup_Table_3[102] = 16'sb1111100100110111;
  assign alpha1_D_Lookup_Table_3[103] = 16'sb0000010110110001;
  assign alpha1_D_Lookup_Table_3[104] = 16'sb0000110000110001;
  assign alpha1_D_Lookup_Table_3[105] = 16'sb1111101001010011;
  assign alpha1_D_Lookup_Table_3[106] = 16'sb1111100101011111;
  assign alpha1_D_Lookup_Table_3[107] = 16'sb0000001011110111;
  assign alpha1_D_Lookup_Table_3[108] = 16'sb1111110011101001;
  assign alpha1_D_Lookup_Table_3[109] = 16'sb1111110011111100;
  assign alpha1_D_Lookup_Table_3[110] = 16'sb0001000001011001;
  assign alpha1_D_Lookup_Table_3[111] = 16'sb0001010100000010;
  assign alpha1_D_Lookup_Table_3[112] = 16'sb0000000100011010;
  assign alpha1_D_Lookup_Table_3[113] = 16'sb1111110001010011;
  assign alpha1_D_Lookup_Table_3[114] = 16'sb0000100011000010;
  assign alpha1_D_Lookup_Table_3[115] = 16'sb0000000110011111;
  assign alpha1_D_Lookup_Table_3[116] = 16'sb1111000110100101;
  assign alpha1_D_Lookup_Table_3[117] = 16'sb1111010111000100;
  assign alpha1_D_Lookup_Table_3[118] = 16'sb0000010111010011;
  assign alpha1_D_Lookup_Table_3[119] = 16'sb0001000001111010;
  assign alpha1_D_Lookup_Table_3[120] = 16'sb0000100111010110;
  assign alpha1_D_Lookup_Table_3[121] = 16'sb1111101000011100;
  assign alpha1_D_Lookup_Table_3[122] = 16'sb1111101110010100;
  assign alpha1_D_Lookup_Table_3[123] = 16'sb0000000101110100;
  assign alpha1_D_Lookup_Table_3[124] = 16'sb1111010010111000;
  assign alpha1_D_Lookup_Table_3[125] = 16'sb1111000000100101;
  assign alpha1_D_Lookup_Table_3[126] = 16'sb1111111110101011;
  assign alpha1_D_Lookup_Table_3[127] = 16'sb0000010011000110;
  assign alpha1_D_Lookup_Table_3[128] = 16'sb1111111110000100;
  assign alpha1_D_Lookup_Table_3[129] = 16'sb0000010010011000;
  assign alpha1_D_Lookup_Table_3[130] = 16'sb0000101001011011;
  assign alpha1_D_Lookup_Table_3[131] = 16'sb0000100001011101;
  assign alpha1_D_Lookup_Table_3[132] = 16'sb0000011100010101;
  assign alpha1_D_Lookup_Table_3[133] = 16'sb1111111001101110;
  assign alpha1_D_Lookup_Table_3[134] = 16'sb1110111111100110;
  assign alpha1_D_Lookup_Table_3[135] = 16'sb1111011100111101;
  assign alpha1_D_Lookup_Table_3[136] = 16'sb0000010101000000;
  assign alpha1_D_Lookup_Table_3[137] = 16'sb1111010111110011;
  assign alpha1_D_Lookup_Table_3[138] = 16'sb1110110001111101;
  assign alpha1_D_Lookup_Table_3[139] = 16'sb0000010111100011;
  assign alpha1_D_Lookup_Table_3[140] = 16'sb0000111100011110;
  assign alpha1_D_Lookup_Table_3[141] = 16'sb1111101000001101;
  assign alpha1_D_Lookup_Table_3[142] = 16'sb1111001110110100;
  assign alpha1_D_Lookup_Table_3[143] = 16'sb1111100010001110;
  assign alpha1_D_Lookup_Table_3[144] = 16'sb1111010001111100;
  assign alpha1_D_Lookup_Table_3[145] = 16'sb1111101011111101;
  assign alpha1_D_Lookup_Table_3[146] = 16'sb0000100100010101;
  assign alpha1_D_Lookup_Table_3[147] = 16'sb0000010000000000;
  assign alpha1_D_Lookup_Table_3[148] = 16'sb1111110011011100;
  assign alpha1_D_Lookup_Table_3[149] = 16'sb0000110100001101;
  assign alpha1_D_Lookup_Table_3[150] = 16'sb0001010100110001;
  assign alpha1_D_Lookup_Table_3[151] = 16'sb1111110110110001;
  assign alpha1_D_Lookup_Table_3[152] = 16'sb1111000110000110;
  assign alpha1_D_Lookup_Table_3[153] = 16'sb0000001010110111;
  assign alpha1_D_Lookup_Table_3[154] = 16'sb0000100011001001;
  assign alpha1_D_Lookup_Table_3[155] = 16'sb0000000001111010;
  assign alpha1_D_Lookup_Table_3[156] = 16'sb1111111110011100;
  assign alpha1_D_Lookup_Table_3[157] = 16'sb1111101100000100;
  assign alpha1_D_Lookup_Table_3[158] = 16'sb1111010001100010;
  assign alpha1_D_Lookup_Table_3[159] = 16'sb1111100101000000;
  assign alpha1_D_Lookup_Table_3[160] = 16'sb0000000000000000;
  assign alpha1_D_Lookup_Table_3[161] = 16'sb0000011011000000;
  assign alpha1_D_Lookup_Table_3[162] = 16'sb0000101110011110;
  assign alpha1_D_Lookup_Table_3[163] = 16'sb0000010011111100;
  assign alpha1_D_Lookup_Table_3[164] = 16'sb0000000001100100;
  assign alpha1_D_Lookup_Table_3[165] = 16'sb1111111110000110;
  assign alpha1_D_Lookup_Table_3[166] = 16'sb1111011100110111;
  assign alpha1_D_Lookup_Table_3[167] = 16'sb1111110101001001;
  assign alpha1_D_Lookup_Table_3[168] = 16'sb0000111001111010;
  assign alpha1_D_Lookup_Table_3[169] = 16'sb0000001001001111;
  assign alpha1_D_Lookup_Table_3[170] = 16'sb1110101011001111;
  assign alpha1_D_Lookup_Table_3[171] = 16'sb1111001011110011;
  assign alpha1_D_Lookup_Table_3[172] = 16'sb0000001100100100;
  assign alpha1_D_Lookup_Table_3[173] = 16'sb1111110000000000;
  assign alpha1_D_Lookup_Table_3[174] = 16'sb1111011011101011;
  assign alpha1_D_Lookup_Table_3[175] = 16'sb0000010100000011;
  assign alpha1_D_Lookup_Table_3[176] = 16'sb0000101110000100;
  assign alpha1_D_Lookup_Table_3[177] = 16'sb0000011101110010;
  assign alpha1_D_Lookup_Table_3[178] = 16'sb0000110001001100;
  assign alpha1_D_Lookup_Table_3[179] = 16'sb0000010111110011;
  assign alpha1_D_Lookup_Table_3[180] = 16'sb1111000011100010;
  assign alpha1_D_Lookup_Table_3[181] = 16'sb1111101000011101;
  assign alpha1_D_Lookup_Table_3[182] = 16'sb0001001110000011;
  assign alpha1_D_Lookup_Table_3[183] = 16'sb0000101000001101;
  assign alpha1_D_Lookup_Table_3[184] = 16'sb1111101011000000;
  assign alpha1_D_Lookup_Table_3[185] = 16'sb0000100011000011;
  assign alpha1_D_Lookup_Table_3[186] = 16'sb0001000000011010;
  assign alpha1_D_Lookup_Table_3[187] = 16'sb0000000110010010;
  assign alpha1_D_Lookup_Table_3[188] = 16'sb1111100011101011;
  assign alpha1_D_Lookup_Table_3[189] = 16'sb1111011110100011;
  assign alpha1_D_Lookup_Table_3[190] = 16'sb1111010110100101;
  assign alpha1_D_Lookup_Table_3[191] = 16'sb1111101101101000;
  assign alpha1_D_Lookup_Table_3[192] = 16'sb0000000001111100;
  assign alpha1_D_Lookup_Table_3[193] = 16'sb1111101100111010;
  assign alpha1_D_Lookup_Table_3[194] = 16'sb0000000001010101;
  assign alpha1_D_Lookup_Table_3[195] = 16'sb0000111111011011;
  assign alpha1_D_Lookup_Table_3[196] = 16'sb0000101101001000;
  assign alpha1_D_Lookup_Table_3[197] = 16'sb1111111010001100;
  assign alpha1_D_Lookup_Table_3[198] = 16'sb0000010001101100;
  assign alpha1_D_Lookup_Table_3[199] = 16'sb0000010111100100;
  assign alpha1_D_Lookup_Table_3[200] = 16'sb1111011000101010;
  assign alpha1_D_Lookup_Table_3[201] = 16'sb1110111110000110;
  assign alpha1_D_Lookup_Table_3[202] = 16'sb1111101000101101;
  assign alpha1_D_Lookup_Table_3[203] = 16'sb0000101000111100;
  assign alpha1_D_Lookup_Table_3[204] = 16'sb0000111001011011;
  assign alpha1_D_Lookup_Table_3[205] = 16'sb1111111001100001;
  assign alpha1_D_Lookup_Table_3[206] = 16'sb1111011100111110;
  assign alpha1_D_Lookup_Table_3[207] = 16'sb0000001110101101;
  assign alpha1_D_Lookup_Table_3[208] = 16'sb1111111011100110;
  assign alpha1_D_Lookup_Table_3[209] = 16'sb1110101011111110;
  assign alpha1_D_Lookup_Table_3[210] = 16'sb1110111110100111;
  assign alpha1_D_Lookup_Table_3[211] = 16'sb0000001100000100;
  assign alpha1_D_Lookup_Table_3[212] = 16'sb0000001100010111;
  assign alpha1_D_Lookup_Table_3[213] = 16'sb1111110100001001;
  assign alpha1_D_Lookup_Table_3[214] = 16'sb0000011010100001;
  assign alpha1_D_Lookup_Table_3[215] = 16'sb0000010110101101;
  assign alpha1_D_Lookup_Table_3[216] = 16'sb1111001111001111;
  assign alpha1_D_Lookup_Table_3[217] = 16'sb1111101001001111;
  assign alpha1_D_Lookup_Table_3[218] = 16'sb0000011011001001;
  assign alpha1_D_Lookup_Table_3[219] = 16'sb1111010011010010;
  assign alpha1_D_Lookup_Table_3[220] = 16'sb1111000101000111;
  assign alpha1_D_Lookup_Table_3[221] = 16'sb0000000011101110;
  assign alpha1_D_Lookup_Table_3[222] = 16'sb1111100010010001;
  assign alpha1_D_Lookup_Table_3[223] = 16'sb1111100010110000;
  assign alpha1_D_Lookup_Table_3[224] = 16'sb0000010000000000;
  assign alpha1_D_Lookup_Table_3[225] = 16'sb1111010111000110;
  assign alpha1_D_Lookup_Table_3[226] = 16'sb1111110001111011;
  assign alpha1_D_Lookup_Table_3[227] = 16'sb0001011011100111;
  assign alpha1_D_Lookup_Table_3[228] = 16'sb0000101101011110;
  assign alpha1_D_Lookup_Table_3[229] = 16'sb0000000010100101;
  assign alpha1_D_Lookup_Table_3[230] = 16'sb0000010111111100;
  assign alpha1_D_Lookup_Table_3[231] = 16'sb1111101111010011;
  assign alpha1_D_Lookup_Table_3[232] = 16'sb0000011010000011;
  assign alpha1_D_Lookup_Table_3[233] = 16'sb0001010101111110;
  assign alpha1_D_Lookup_Table_3[234] = 16'sb1111111110111111;
  assign alpha1_D_Lookup_Table_3[235] = 16'sb1111110100001101;
  assign alpha1_D_Lookup_Table_3[236] = 16'sb0000110011101001;
  assign alpha1_D_Lookup_Table_3[237] = 16'sb0000001001100000;
  assign alpha1_D_Lookup_Table_3[238] = 16'sb1111110011011001;
  assign alpha1_D_Lookup_Table_3[239] = 16'sb1111101011101001;
  assign alpha1_D_Lookup_Table_3[240] = 16'sb1111001110010110;
  assign alpha1_D_Lookup_Table_3[241] = 16'sb0000011111110110;
  assign alpha1_D_Lookup_Table_3[242] = 16'sb0001000101000010;
  assign alpha1_D_Lookup_Table_3[243] = 16'sb1111110001100001;
  assign alpha1_D_Lookup_Table_3[244] = 16'sb1111111010000011;
  assign alpha1_D_Lookup_Table_3[245] = 16'sb0000011011110110;
  assign alpha1_D_Lookup_Table_3[246] = 16'sb0000000011001110;
  assign alpha1_D_Lookup_Table_3[247] = 16'sb0000001111000110;
  assign alpha1_D_Lookup_Table_3[248] = 16'sb1111111001101011;
  assign alpha1_D_Lookup_Table_3[249] = 16'sb1111100000001011;
  assign alpha1_D_Lookup_Table_3[250] = 16'sb0000010000100100;
  assign alpha1_D_Lookup_Table_3[251] = 16'sb1111111101101010;
  assign alpha1_D_Lookup_Table_3[252] = 16'sb1111001110010111;
  assign alpha1_D_Lookup_Table_3[253] = 16'sb1111110101000101;
  assign alpha1_D_Lookup_Table_3[254] = 16'sb0000010110101010;
  assign alpha1_D_Lookup_Table_3[255] = 16'sb0000110110110001;
  assign alpha1_D_Lookup_Table_3[256] = 16'sb0001000001111100;
  assign alpha1_D_Lookup_Table_3[257] = 16'sb1111100101011110;
  assign alpha1_D_Lookup_Table_3[258] = 16'sb1110110110001001;
  assign alpha1_D_Lookup_Table_3[259] = 16'sb1111100101011111;
  assign alpha1_D_Lookup_Table_3[260] = 16'sb1111110111111010;
  assign alpha1_D_Lookup_Table_3[261] = 16'sb0000010010000011;
  assign alpha1_D_Lookup_Table_3[262] = 16'sb0000011010100001;
  assign alpha1_D_Lookup_Table_3[263] = 16'sb1111001110000011;
  assign alpha1_D_Lookup_Table_3[264] = 16'sb1110110001100000;
  assign alpha1_D_Lookup_Table_3[265] = 16'sb1111110000100001;
  assign alpha1_D_Lookup_Table_3[266] = 16'sb0000101111011000;
  assign alpha1_D_Lookup_Table_3[267] = 16'sb0001001010100011;
  assign alpha1_D_Lookup_Table_3[268] = 16'sb0000011001110011;
  assign alpha1_D_Lookup_Table_3[269] = 16'sb1111000110101010;
  assign alpha1_D_Lookup_Table_3[270] = 16'sb1111000100110011;
  assign alpha1_D_Lookup_Table_3[271] = 16'sb1111111010101111;
  assign alpha1_D_Lookup_Table_3[272] = 16'sb0000000000110100;
  assign alpha1_D_Lookup_Table_3[273] = 16'sb1111001110100011;
  assign alpha1_D_Lookup_Table_3[274] = 16'sb1111000111011111;
  assign alpha1_D_Lookup_Table_3[275] = 16'sb0000000101101000;
  assign alpha1_D_Lookup_Table_3[276] = 16'sb0000010100011110;
  assign alpha1_D_Lookup_Table_3[277] = 16'sb0000000011011001;
  assign alpha1_D_Lookup_Table_3[278] = 16'sb0000100111010000;
  assign alpha1_D_Lookup_Table_3[279] = 16'sb0000110101111101;
  assign alpha1_D_Lookup_Table_3[280] = 16'sb0000101010001110;
  assign alpha1_D_Lookup_Table_3[281] = 16'sb0000011001000001;
  assign alpha1_D_Lookup_Table_3[282] = 16'sb1111010000101000;
  assign alpha1_D_Lookup_Table_3[283] = 16'sb1111010110110011;
  assign alpha1_D_Lookup_Table_3[284] = 16'sb0000100111111011;
  assign alpha1_D_Lookup_Table_3[285] = 16'sb1111110111001101;
  assign alpha1_D_Lookup_Table_3[286] = 16'sb1111011110110110;
  assign alpha1_D_Lookup_Table_3[287] = 16'sb0000110001100111;
  assign imagOut = alpha1_D_Lookup_Table_3[prelookup_idx];



  always @(posedge clk)
    begin : PipelineRegister_1_process
      if (enb) begin
        imagOut_1 <= imagOut;
      end
    end



  assign prelookup_idx_sat_1 = (Delay19_out1 == 16'b0000000000000000 ? 9'b000000000 :
              (Delay19_out1 >= 16'b0000000100011111 ? 9'b100011111 :
              Delay19_out1[8:0]));



  assign prelookup_idx_1 = (prelookup_idx_sat_1 > 9'b100011111 ? 9'b100011111 :
              prelookup_idx_sat_1);



  assign alpha1_D_Lookup_Table2_1[0] = 16'sb0000010000000000;
  assign alpha1_D_Lookup_Table2_1[1] = 16'sb0000010100100110;
  assign alpha1_D_Lookup_Table2_1[2] = 16'sb0000011011011011;
  assign alpha1_D_Lookup_Table2_1[3] = 16'sb0000001001111101;
  assign alpha1_D_Lookup_Table2_1[4] = 16'sb1111111010001010;
  assign alpha1_D_Lookup_Table2_1[5] = 16'sb1111110101110111;
  assign alpha1_D_Lookup_Table2_1[6] = 16'sb1111010110001100;
  assign alpha1_D_Lookup_Table2_1[7] = 16'sb1111001100101100;
  assign alpha1_D_Lookup_Table2_1[8] = 16'sb1111110000010101;
  assign alpha1_D_Lookup_Table2_1[9] = 16'sb1111110111001110;
  assign alpha1_D_Lookup_Table2_1[10] = 16'sb1111011010111111;
  assign alpha1_D_Lookup_Table2_1[11] = 16'sb1111001001001011;
  assign alpha1_D_Lookup_Table2_1[12] = 16'sb1111101001110100;
  assign alpha1_D_Lookup_Table2_1[13] = 16'sb0000101110110110;
  assign alpha1_D_Lookup_Table2_1[14] = 16'sb0000011110011110;
  assign alpha1_D_Lookup_Table2_1[15] = 16'sb1111010001001001;
  assign alpha1_D_Lookup_Table2_1[16] = 16'sb1111101111100010;
  assign alpha1_D_Lookup_Table2_1[17] = 16'sb0000101101000100;
  assign alpha1_D_Lookup_Table2_1[18] = 16'sb0000010110100000;
  assign alpha1_D_Lookup_Table2_1[19] = 16'sb0000101100010110;
  assign alpha1_D_Lookup_Table2_1[20] = 16'sb0001100011011000;
  assign alpha1_D_Lookup_Table2_1[21] = 16'sb0000100001010101;
  assign alpha1_D_Lookup_Table2_1[22] = 16'sb1111001010110001;
  assign alpha1_D_Lookup_Table2_1[23] = 16'sb1111100101010100;
  assign alpha1_D_Lookup_Table2_1[24] = 16'sb0000000111010011;
  assign alpha1_D_Lookup_Table2_1[25] = 16'sb1111100001111001;
  assign alpha1_D_Lookup_Table2_1[26] = 16'sb1111000001110111;
  assign alpha1_D_Lookup_Table2_1[27] = 16'sb1111001111101111;
  assign alpha1_D_Lookup_Table2_1[28] = 16'sb1111011010011001;
  assign alpha1_D_Lookup_Table2_1[29] = 16'sb1111001001111011;
  assign alpha1_D_Lookup_Table2_1[30] = 16'sb1111000101110000;
  assign alpha1_D_Lookup_Table2_1[31] = 16'sb1111100011000100;
  assign alpha1_D_Lookup_Table2_1[32] = 16'sb1111111000000000;
  assign alpha1_D_Lookup_Table2_1[33] = 16'sb1111100011000100;
  assign alpha1_D_Lookup_Table2_1[34] = 16'sb1111000101110000;
  assign alpha1_D_Lookup_Table2_1[35] = 16'sb1111001001111011;
  assign alpha1_D_Lookup_Table2_1[36] = 16'sb1111011010011001;
  assign alpha1_D_Lookup_Table2_1[37] = 16'sb1111001111101111;
  assign alpha1_D_Lookup_Table2_1[38] = 16'sb1111000001110111;
  assign alpha1_D_Lookup_Table2_1[39] = 16'sb1111100001111001;
  assign alpha1_D_Lookup_Table2_1[40] = 16'sb0000000111010011;
  assign alpha1_D_Lookup_Table2_1[41] = 16'sb1111100101010100;
  assign alpha1_D_Lookup_Table2_1[42] = 16'sb1111001010110001;
  assign alpha1_D_Lookup_Table2_1[43] = 16'sb0000100001010101;
  assign alpha1_D_Lookup_Table2_1[44] = 16'sb0001100011011000;
  assign alpha1_D_Lookup_Table2_1[45] = 16'sb0000101100010110;
  assign alpha1_D_Lookup_Table2_1[46] = 16'sb0000010110100000;
  assign alpha1_D_Lookup_Table2_1[47] = 16'sb0000101101000100;
  assign alpha1_D_Lookup_Table2_1[48] = 16'sb1111101111100010;
  assign alpha1_D_Lookup_Table2_1[49] = 16'sb1111010001001001;
  assign alpha1_D_Lookup_Table2_1[50] = 16'sb0000011110011110;
  assign alpha1_D_Lookup_Table2_1[51] = 16'sb0000101110110110;
  assign alpha1_D_Lookup_Table2_1[52] = 16'sb1111101001110100;
  assign alpha1_D_Lookup_Table2_1[53] = 16'sb1111001001001011;
  assign alpha1_D_Lookup_Table2_1[54] = 16'sb1111011010111111;
  assign alpha1_D_Lookup_Table2_1[55] = 16'sb1111110111001110;
  assign alpha1_D_Lookup_Table2_1[56] = 16'sb1111110000010101;
  assign alpha1_D_Lookup_Table2_1[57] = 16'sb1111001100101100;
  assign alpha1_D_Lookup_Table2_1[58] = 16'sb1111010110001100;
  assign alpha1_D_Lookup_Table2_1[59] = 16'sb1111110101110111;
  assign alpha1_D_Lookup_Table2_1[60] = 16'sb1111111010001010;
  assign alpha1_D_Lookup_Table2_1[61] = 16'sb0000001001111101;
  assign alpha1_D_Lookup_Table2_1[62] = 16'sb0000011011011011;
  assign alpha1_D_Lookup_Table2_1[63] = 16'sb0000010100100110;
  assign alpha1_D_Lookup_Table2_1[64] = 16'sb0000010000000000;
  assign alpha1_D_Lookup_Table2_1[65] = 16'sb1111111010111101;
  assign alpha1_D_Lookup_Table2_1[66] = 16'sb1111011001110101;
  assign alpha1_D_Lookup_Table2_1[67] = 16'sb1111011101010011;
  assign alpha1_D_Lookup_Table2_1[68] = 16'sb1111011111010110;
  assign alpha1_D_Lookup_Table2_1[69] = 16'sb1110111111100111;
  assign alpha1_D_Lookup_Table2_1[70] = 16'sb1111001001110110;
  assign alpha1_D_Lookup_Table2_1[71] = 16'sb0000011101011111;
  assign alpha1_D_Lookup_Table2_1[72] = 16'sb0001010000011101;
  assign alpha1_D_Lookup_Table2_1[73] = 16'sb0000011101011111;
  assign alpha1_D_Lookup_Table2_1[74] = 16'sb1111100011001110;
  assign alpha1_D_Lookup_Table2_1[75] = 16'sb1111100100111100;
  assign alpha1_D_Lookup_Table2_1[76] = 16'sb1111111001000001;
  assign alpha1_D_Lookup_Table2_1[77] = 16'sb0000011011110011;
  assign alpha1_D_Lookup_Table2_1[78] = 16'sb0000100000110011;
  assign alpha1_D_Lookup_Table2_1[79] = 16'sb1111100101010001;
  assign alpha1_D_Lookup_Table2_1[80] = 16'sb1111111001001000;
  assign alpha1_D_Lookup_Table2_1[81] = 16'sb0001000111000000;
  assign alpha1_D_Lookup_Table2_1[82] = 16'sb0000001011111010;
  assign alpha1_D_Lookup_Table2_1[83] = 16'sb1111000011001111;
  assign alpha1_D_Lookup_Table2_1[84] = 16'sb0000000001011000;
  assign alpha1_D_Lookup_Table2_1[85] = 16'sb0000100101001011;
  assign alpha1_D_Lookup_Table2_1[86] = 16'sb1111111100010011;
  assign alpha1_D_Lookup_Table2_1[87] = 16'sb1111101110110101;
  assign alpha1_D_Lookup_Table2_1[88] = 16'sb0000000101110011;
  assign alpha1_D_Lookup_Table2_1[89] = 16'sb0000010010100001;
  assign alpha1_D_Lookup_Table2_1[90] = 16'sb1111011011101000;
  assign alpha1_D_Lookup_Table2_1[91] = 16'sb1111000001100010;
  assign alpha1_D_Lookup_Table2_1[92] = 16'sb0000101001110100;
  assign alpha1_D_Lookup_Table2_1[93] = 16'sb0000110011110001;
  assign alpha1_D_Lookup_Table2_1[94] = 16'sb1111000011001001;
  assign alpha1_D_Lookup_Table2_1[95] = 16'sb0000000000001011;
  assign alpha1_D_Lookup_Table2_1[96] = 16'sb0001101000000000;
  assign alpha1_D_Lookup_Table2_1[97] = 16'sb0000011100110110;
  assign alpha1_D_Lookup_Table2_1[98] = 16'sb1111111010000110;
  assign alpha1_D_Lookup_Table2_1[99] = 16'sb0000110100011000;
  assign alpha1_D_Lookup_Table2_1[100] = 16'sb0000101010100101;
  assign alpha1_D_Lookup_Table2_1[101] = 16'sb0000010011110111;
  assign alpha1_D_Lookup_Table2_1[102] = 16'sb0000000100010011;
  assign alpha1_D_Lookup_Table2_1[103] = 16'sb1111010011001111;
  assign alpha1_D_Lookup_Table2_1[104] = 16'sb1111010110000111;
  assign alpha1_D_Lookup_Table2_1[105] = 16'sb0000010001010111;
  assign alpha1_D_Lookup_Table2_1[106] = 16'sb0000100111100110;
  assign alpha1_D_Lookup_Table2_1[107] = 16'sb0000000100011110;
  assign alpha1_D_Lookup_Table2_1[108] = 16'sb1111110100011010;
  assign alpha1_D_Lookup_Table2_1[109] = 16'sb0000110101001010;
  assign alpha1_D_Lookup_Table2_1[110] = 16'sb0001011101000110;
  assign alpha1_D_Lookup_Table2_1[111] = 16'sb0000011011010000;
  assign alpha1_D_Lookup_Table2_1[112] = 16'sb1111011011100100;
  assign alpha1_D_Lookup_Table2_1[113] = 16'sb1111011000101011;
  assign alpha1_D_Lookup_Table2_1[114] = 16'sb0000000111001001;
  assign alpha1_D_Lookup_Table2_1[115] = 16'sb0001000000000000;
  assign alpha1_D_Lookup_Table2_1[116] = 16'sb0000010110111011;
  assign alpha1_D_Lookup_Table2_1[117] = 16'sb1111001101000001;
  assign alpha1_D_Lookup_Table2_1[118] = 16'sb1111010010110111;
  assign alpha1_D_Lookup_Table2_1[119] = 16'sb1111001110110110;
  assign alpha1_D_Lookup_Table2_1[120] = 16'sb1111011001110111;
  assign alpha1_D_Lookup_Table2_1[121] = 16'sb0000100010110000;
  assign alpha1_D_Lookup_Table2_1[122] = 16'sb0000010111111110;
  assign alpha1_D_Lookup_Table2_1[123] = 16'sb1111110011100000;
  assign alpha1_D_Lookup_Table2_1[124] = 16'sb0000011111110000;
  assign alpha1_D_Lookup_Table2_1[125] = 16'sb0000010111000100;
  assign alpha1_D_Lookup_Table2_1[126] = 16'sb1111110110111010;
  assign alpha1_D_Lookup_Table2_1[127] = 16'sb0000011010000100;
  assign alpha1_D_Lookup_Table2_1[128] = 16'sb0000010000000000;
  assign alpha1_D_Lookup_Table2_1[129] = 16'sb1111100000010011;
  assign alpha1_D_Lookup_Table2_1[130] = 16'sb1111100110111111;
  assign alpha1_D_Lookup_Table2_1[131] = 16'sb0000010110111011;
  assign alpha1_D_Lookup_Table2_1[132] = 16'sb0001001000101000;
  assign alpha1_D_Lookup_Table2_1[133] = 16'sb0000101001110111;
  assign alpha1_D_Lookup_Table2_1[134] = 16'sb1111100000001011;
  assign alpha1_D_Lookup_Table2_1[135] = 16'sb1111100110011010;
  assign alpha1_D_Lookup_Table2_1[136] = 16'sb1111110010100111;
  assign alpha1_D_Lookup_Table2_1[137] = 16'sb1111101111000000;
  assign alpha1_D_Lookup_Table2_1[138] = 16'sb0000011110010010;
  assign alpha1_D_Lookup_Table2_1[139] = 16'sb0000101000000100;
  assign alpha1_D_Lookup_Table2_1[140] = 16'sb0000100001110000;
  assign alpha1_D_Lookup_Table2_1[141] = 16'sb0000101111101101;
  assign alpha1_D_Lookup_Table2_1[142] = 16'sb1111100101010111;
  assign alpha1_D_Lookup_Table2_1[143] = 16'sb1110111111011101;
  assign alpha1_D_Lookup_Table2_1[144] = 16'sb1111111011110010;
  assign alpha1_D_Lookup_Table2_1[145] = 16'sb1111100101000011;
  assign alpha1_D_Lookup_Table2_1[146] = 16'sb1111110011011000;
  assign alpha1_D_Lookup_Table2_1[147] = 16'sb0001011101011010;
  assign alpha1_D_Lookup_Table2_1[148] = 16'sb0000111000100111;
  assign alpha1_D_Lookup_Table2_1[149] = 16'sb0000000110001101;
  assign alpha1_D_Lookup_Table2_1[150] = 16'sb0000111110001110;
  assign alpha1_D_Lookup_Table2_1[151] = 16'sb0000001011011000;
  assign alpha1_D_Lookup_Table2_1[152] = 16'sb1111001111100010;
  assign alpha1_D_Lookup_Table2_1[153] = 16'sb0000010010110011;
  assign alpha1_D_Lookup_Table2_1[154] = 16'sb0000001111010111;
  assign alpha1_D_Lookup_Table2_1[155] = 16'sb1111010000101101;
  assign alpha1_D_Lookup_Table2_1[156] = 16'sb1111100010000111;
  assign alpha1_D_Lookup_Table2_1[157] = 16'sb1111110100001111;
  assign alpha1_D_Lookup_Table2_1[158] = 16'sb1111100101101110;
  assign alpha1_D_Lookup_Table2_1[159] = 16'sb1111101100111001;
  assign alpha1_D_Lookup_Table2_1[160] = 16'sb1111111000000000;
  assign alpha1_D_Lookup_Table2_1[161] = 16'sb1111101100111001;
  assign alpha1_D_Lookup_Table2_1[162] = 16'sb1111100101101110;
  assign alpha1_D_Lookup_Table2_1[163] = 16'sb1111110100001111;
  assign alpha1_D_Lookup_Table2_1[164] = 16'sb1111100010000111;
  assign alpha1_D_Lookup_Table2_1[165] = 16'sb1111010000101101;
  assign alpha1_D_Lookup_Table2_1[166] = 16'sb0000001111010111;
  assign alpha1_D_Lookup_Table2_1[167] = 16'sb0000010010110011;
  assign alpha1_D_Lookup_Table2_1[168] = 16'sb1111001111100010;
  assign alpha1_D_Lookup_Table2_1[169] = 16'sb0000001011011000;
  assign alpha1_D_Lookup_Table2_1[170] = 16'sb0000111110001110;
  assign alpha1_D_Lookup_Table2_1[171] = 16'sb0000000110001101;
  assign alpha1_D_Lookup_Table2_1[172] = 16'sb0000111000100111;
  assign alpha1_D_Lookup_Table2_1[173] = 16'sb0001011101011010;
  assign alpha1_D_Lookup_Table2_1[174] = 16'sb1111110011011000;
  assign alpha1_D_Lookup_Table2_1[175] = 16'sb1111100101000011;
  assign alpha1_D_Lookup_Table2_1[176] = 16'sb1111111011110010;
  assign alpha1_D_Lookup_Table2_1[177] = 16'sb1110111111011101;
  assign alpha1_D_Lookup_Table2_1[178] = 16'sb1111100101010111;
  assign alpha1_D_Lookup_Table2_1[179] = 16'sb0000101111101101;
  assign alpha1_D_Lookup_Table2_1[180] = 16'sb0000100001110000;
  assign alpha1_D_Lookup_Table2_1[181] = 16'sb0000101000000100;
  assign alpha1_D_Lookup_Table2_1[182] = 16'sb0000011110010010;
  assign alpha1_D_Lookup_Table2_1[183] = 16'sb1111101111000000;
  assign alpha1_D_Lookup_Table2_1[184] = 16'sb1111110010100111;
  assign alpha1_D_Lookup_Table2_1[185] = 16'sb1111100110011010;
  assign alpha1_D_Lookup_Table2_1[186] = 16'sb1111100000001011;
  assign alpha1_D_Lookup_Table2_1[187] = 16'sb0000101001110111;
  assign alpha1_D_Lookup_Table2_1[188] = 16'sb0001001000101000;
  assign alpha1_D_Lookup_Table2_1[189] = 16'sb0000010110111011;
  assign alpha1_D_Lookup_Table2_1[190] = 16'sb1111100110111111;
  assign alpha1_D_Lookup_Table2_1[191] = 16'sb1111100000010011;
  assign alpha1_D_Lookup_Table2_1[192] = 16'sb0000010000000000;
  assign alpha1_D_Lookup_Table2_1[193] = 16'sb0000011010000100;
  assign alpha1_D_Lookup_Table2_1[194] = 16'sb1111110110111010;
  assign alpha1_D_Lookup_Table2_1[195] = 16'sb0000010111000100;
  assign alpha1_D_Lookup_Table2_1[196] = 16'sb0000011111110000;
  assign alpha1_D_Lookup_Table2_1[197] = 16'sb1111110011100000;
  assign alpha1_D_Lookup_Table2_1[198] = 16'sb0000010111111110;
  assign alpha1_D_Lookup_Table2_1[199] = 16'sb0000100010110000;
  assign alpha1_D_Lookup_Table2_1[200] = 16'sb1111011001110111;
  assign alpha1_D_Lookup_Table2_1[201] = 16'sb1111001110110110;
  assign alpha1_D_Lookup_Table2_1[202] = 16'sb1111010010110111;
  assign alpha1_D_Lookup_Table2_1[203] = 16'sb1111001101000001;
  assign alpha1_D_Lookup_Table2_1[204] = 16'sb0000010110111011;
  assign alpha1_D_Lookup_Table2_1[205] = 16'sb0001000000000000;
  assign alpha1_D_Lookup_Table2_1[206] = 16'sb0000000111001001;
  assign alpha1_D_Lookup_Table2_1[207] = 16'sb1111011000101011;
  assign alpha1_D_Lookup_Table2_1[208] = 16'sb1111011011100100;
  assign alpha1_D_Lookup_Table2_1[209] = 16'sb0000011011010000;
  assign alpha1_D_Lookup_Table2_1[210] = 16'sb0001011101000110;
  assign alpha1_D_Lookup_Table2_1[211] = 16'sb0000110101001010;
  assign alpha1_D_Lookup_Table2_1[212] = 16'sb1111110100011010;
  assign alpha1_D_Lookup_Table2_1[213] = 16'sb0000000100011110;
  assign alpha1_D_Lookup_Table2_1[214] = 16'sb0000100111100110;
  assign alpha1_D_Lookup_Table2_1[215] = 16'sb0000010001010111;
  assign alpha1_D_Lookup_Table2_1[216] = 16'sb1111010110000111;
  assign alpha1_D_Lookup_Table2_1[217] = 16'sb1111010011001111;
  assign alpha1_D_Lookup_Table2_1[218] = 16'sb0000000100010011;
  assign alpha1_D_Lookup_Table2_1[219] = 16'sb0000010011110111;
  assign alpha1_D_Lookup_Table2_1[220] = 16'sb0000101010100101;
  assign alpha1_D_Lookup_Table2_1[221] = 16'sb0000110100011000;
  assign alpha1_D_Lookup_Table2_1[222] = 16'sb1111111010000110;
  assign alpha1_D_Lookup_Table2_1[223] = 16'sb0000011100110110;
  assign alpha1_D_Lookup_Table2_1[224] = 16'sb0001101000000000;
  assign alpha1_D_Lookup_Table2_1[225] = 16'sb0000000000001011;
  assign alpha1_D_Lookup_Table2_1[226] = 16'sb1111000011001001;
  assign alpha1_D_Lookup_Table2_1[227] = 16'sb0000110011110001;
  assign alpha1_D_Lookup_Table2_1[228] = 16'sb0000101001110100;
  assign alpha1_D_Lookup_Table2_1[229] = 16'sb1111000001100010;
  assign alpha1_D_Lookup_Table2_1[230] = 16'sb1111011011101000;
  assign alpha1_D_Lookup_Table2_1[231] = 16'sb0000010010100001;
  assign alpha1_D_Lookup_Table2_1[232] = 16'sb0000000101110011;
  assign alpha1_D_Lookup_Table2_1[233] = 16'sb1111101110110101;
  assign alpha1_D_Lookup_Table2_1[234] = 16'sb1111111100010011;
  assign alpha1_D_Lookup_Table2_1[235] = 16'sb0000100101001011;
  assign alpha1_D_Lookup_Table2_1[236] = 16'sb0000000001011000;
  assign alpha1_D_Lookup_Table2_1[237] = 16'sb1111000011001111;
  assign alpha1_D_Lookup_Table2_1[238] = 16'sb0000001011111010;
  assign alpha1_D_Lookup_Table2_1[239] = 16'sb0001000111000000;
  assign alpha1_D_Lookup_Table2_1[240] = 16'sb1111111001001000;
  assign alpha1_D_Lookup_Table2_1[241] = 16'sb1111100101010001;
  assign alpha1_D_Lookup_Table2_1[242] = 16'sb0000100000110011;
  assign alpha1_D_Lookup_Table2_1[243] = 16'sb0000011011110011;
  assign alpha1_D_Lookup_Table2_1[244] = 16'sb1111111001000001;
  assign alpha1_D_Lookup_Table2_1[245] = 16'sb1111100100111100;
  assign alpha1_D_Lookup_Table2_1[246] = 16'sb1111100011001110;
  assign alpha1_D_Lookup_Table2_1[247] = 16'sb0000011101011111;
  assign alpha1_D_Lookup_Table2_1[248] = 16'sb0001010000011101;
  assign alpha1_D_Lookup_Table2_1[249] = 16'sb0000011101011111;
  assign alpha1_D_Lookup_Table2_1[250] = 16'sb1111001001110110;
  assign alpha1_D_Lookup_Table2_1[251] = 16'sb1110111111100111;
  assign alpha1_D_Lookup_Table2_1[252] = 16'sb1111011111010110;
  assign alpha1_D_Lookup_Table2_1[253] = 16'sb1111011101010011;
  assign alpha1_D_Lookup_Table2_1[254] = 16'sb1111011001110101;
  assign alpha1_D_Lookup_Table2_1[255] = 16'sb1111111010111101;
  assign alpha1_D_Lookup_Table2_1[256] = 16'sb0000010000000000;
  assign alpha1_D_Lookup_Table2_1[257] = 16'sb0000010100100110;
  assign alpha1_D_Lookup_Table2_1[258] = 16'sb0000011011011011;
  assign alpha1_D_Lookup_Table2_1[259] = 16'sb0000001001111101;
  assign alpha1_D_Lookup_Table2_1[260] = 16'sb1111111010001010;
  assign alpha1_D_Lookup_Table2_1[261] = 16'sb1111110101110111;
  assign alpha1_D_Lookup_Table2_1[262] = 16'sb1111010110001100;
  assign alpha1_D_Lookup_Table2_1[263] = 16'sb1111001100101100;
  assign alpha1_D_Lookup_Table2_1[264] = 16'sb1111110000010101;
  assign alpha1_D_Lookup_Table2_1[265] = 16'sb1111110111001110;
  assign alpha1_D_Lookup_Table2_1[266] = 16'sb1111011010111111;
  assign alpha1_D_Lookup_Table2_1[267] = 16'sb1111001001001011;
  assign alpha1_D_Lookup_Table2_1[268] = 16'sb1111101001110100;
  assign alpha1_D_Lookup_Table2_1[269] = 16'sb0000101110110110;
  assign alpha1_D_Lookup_Table2_1[270] = 16'sb0000011110011110;
  assign alpha1_D_Lookup_Table2_1[271] = 16'sb1111010001001001;
  assign alpha1_D_Lookup_Table2_1[272] = 16'sb1111101111100010;
  assign alpha1_D_Lookup_Table2_1[273] = 16'sb0000101101000100;
  assign alpha1_D_Lookup_Table2_1[274] = 16'sb0000010110100000;
  assign alpha1_D_Lookup_Table2_1[275] = 16'sb0000101100010110;
  assign alpha1_D_Lookup_Table2_1[276] = 16'sb0001100011011000;
  assign alpha1_D_Lookup_Table2_1[277] = 16'sb0000100001010101;
  assign alpha1_D_Lookup_Table2_1[278] = 16'sb1111001010110001;
  assign alpha1_D_Lookup_Table2_1[279] = 16'sb1111100101010100;
  assign alpha1_D_Lookup_Table2_1[280] = 16'sb0000000111010011;
  assign alpha1_D_Lookup_Table2_1[281] = 16'sb1111100001111001;
  assign alpha1_D_Lookup_Table2_1[282] = 16'sb1111000001110111;
  assign alpha1_D_Lookup_Table2_1[283] = 16'sb1111001111101111;
  assign alpha1_D_Lookup_Table2_1[284] = 16'sb1111011010011001;
  assign alpha1_D_Lookup_Table2_1[285] = 16'sb1111001001111011;
  assign alpha1_D_Lookup_Table2_1[286] = 16'sb1111000101110000;
  assign alpha1_D_Lookup_Table2_1[287] = 16'sb1111100011000100;
  assign realOut_2 = alpha1_D_Lookup_Table2_1[prelookup_idx_1];



  always @(posedge clk)
    begin : PipelineRegister_2_process
      if (enb) begin
        realOut_3 <= realOut_2;
      end
    end



  assign alpha1_D_Lookup_Table2_3[0] = 16'sb1111110000111110;
  assign alpha1_D_Lookup_Table2_3[1] = 16'sb0000110111000111;
  assign alpha1_D_Lookup_Table2_3[2] = 16'sb0000111001101111;
  assign alpha1_D_Lookup_Table2_3[3] = 16'sb1111010110110011;
  assign alpha1_D_Lookup_Table2_3[4] = 16'sb1111100111100001;
  assign alpha1_D_Lookup_Table2_3[5] = 16'sb0000101111010011;
  assign alpha1_D_Lookup_Table2_3[6] = 16'sb0000100010001101;
  assign alpha1_D_Lookup_Table2_3[7] = 16'sb0000100011111100;
  assign alpha1_D_Lookup_Table2_3[8] = 16'sb0000101110101111;
  assign alpha1_D_Lookup_Table2_3[9] = 16'sb1111111011101111;
  assign alpha1_D_Lookup_Table2_3[10] = 16'sb1111101011111001;
  assign alpha1_D_Lookup_Table2_3[11] = 16'sb1111111011110010;
  assign alpha1_D_Lookup_Table2_3[12] = 16'sb1111010110001011;
  assign alpha1_D_Lookup_Table2_3[13] = 16'sb1111001101011110;
  assign alpha1_D_Lookup_Table2_3[14] = 16'sb1111111111010011;
  assign alpha1_D_Lookup_Table2_3[15] = 16'sb0000001001100011;
  assign alpha1_D_Lookup_Table2_3[16] = 16'sb0000000010100000;
  assign alpha1_D_Lookup_Table2_3[17] = 16'sb0000010110100101;
  assign alpha1_D_Lookup_Table2_3[18] = 16'sb0000010111000000;
  assign alpha1_D_Lookup_Table2_3[19] = 16'sb0000011001110010;
  assign alpha1_D_Lookup_Table2_3[20] = 16'sb0000101110110001;
  assign alpha1_D_Lookup_Table2_3[21] = 16'sb0000001110010001;
  assign alpha1_D_Lookup_Table2_3[22] = 16'sb1111100010011010;
  assign alpha1_D_Lookup_Table2_3[23] = 16'sb1111111100010100;
  assign alpha1_D_Lookup_Table2_3[24] = 16'sb0000010000011100;
  assign alpha1_D_Lookup_Table2_3[25] = 16'sb1111110111110111;
  assign alpha1_D_Lookup_Table2_3[26] = 16'sb1111101101101100;
  assign alpha1_D_Lookup_Table2_3[27] = 16'sb1111011010001001;
  assign alpha1_D_Lookup_Table2_3[28] = 16'sb1111000100101111;
  assign alpha1_D_Lookup_Table2_3[29] = 16'sb1111111110000011;
  assign alpha1_D_Lookup_Table2_3[30] = 16'sb0001001000000110;
  assign alpha1_D_Lookup_Table2_3[31] = 16'sb0000111101110100;
  assign alpha1_D_Lookup_Table2_3[32] = 16'sb0000000000000000;
  assign alpha1_D_Lookup_Table2_3[33] = 16'sb1111000010001100;
  assign alpha1_D_Lookup_Table2_3[34] = 16'sb1110110111111010;
  assign alpha1_D_Lookup_Table2_3[35] = 16'sb0000000001111101;
  assign alpha1_D_Lookup_Table2_3[36] = 16'sb0000111011010001;
  assign alpha1_D_Lookup_Table2_3[37] = 16'sb0000100101110111;
  assign alpha1_D_Lookup_Table2_3[38] = 16'sb0000010010010100;
  assign alpha1_D_Lookup_Table2_3[39] = 16'sb0000001000001001;
  assign alpha1_D_Lookup_Table2_3[40] = 16'sb1111101111100100;
  assign alpha1_D_Lookup_Table2_3[41] = 16'sb0000000011101100;
  assign alpha1_D_Lookup_Table2_3[42] = 16'sb0000011101100110;
  assign alpha1_D_Lookup_Table2_3[43] = 16'sb1111110001101111;
  assign alpha1_D_Lookup_Table2_3[44] = 16'sb1111010001001111;
  assign alpha1_D_Lookup_Table2_3[45] = 16'sb1111100110001110;
  assign alpha1_D_Lookup_Table2_3[46] = 16'sb1111101001000000;
  assign alpha1_D_Lookup_Table2_3[47] = 16'sb1111101001011011;
  assign alpha1_D_Lookup_Table2_3[48] = 16'sb1111111101100000;
  assign alpha1_D_Lookup_Table2_3[49] = 16'sb1111110110011101;
  assign alpha1_D_Lookup_Table2_3[50] = 16'sb0000000000101101;
  assign alpha1_D_Lookup_Table2_3[51] = 16'sb0000110010100010;
  assign alpha1_D_Lookup_Table2_3[52] = 16'sb0000101001110101;
  assign alpha1_D_Lookup_Table2_3[53] = 16'sb0000000100001110;
  assign alpha1_D_Lookup_Table2_3[54] = 16'sb0000010100000111;
  assign alpha1_D_Lookup_Table2_3[55] = 16'sb0000000100010001;
  assign alpha1_D_Lookup_Table2_3[56] = 16'sb1111010001010001;
  assign alpha1_D_Lookup_Table2_3[57] = 16'sb1111011100000100;
  assign alpha1_D_Lookup_Table2_3[58] = 16'sb1111011101110011;
  assign alpha1_D_Lookup_Table2_3[59] = 16'sb1111010000101101;
  assign alpha1_D_Lookup_Table2_3[60] = 16'sb0000011000011111;
  assign alpha1_D_Lookup_Table2_3[61] = 16'sb0000101001001101;
  assign alpha1_D_Lookup_Table2_3[62] = 16'sb1111000110010001;
  assign alpha1_D_Lookup_Table2_3[63] = 16'sb1111001000111001;
  assign alpha1_D_Lookup_Table2_3[64] = 16'sb0000001111000010;
  assign alpha1_D_Lookup_Table2_3[65] = 16'sb1111111101011000;
  assign alpha1_D_Lookup_Table2_3[66] = 16'sb0000000011110110;
  assign alpha1_D_Lookup_Table2_3[67] = 16'sb0000011111010001;
  assign alpha1_D_Lookup_Table2_3[68] = 16'sb1111100011001110;
  assign alpha1_D_Lookup_Table2_3[69] = 16'sb1111001010110011;
  assign alpha1_D_Lookup_Table2_3[70] = 16'sb1111110100100000;
  assign alpha1_D_Lookup_Table2_3[71] = 16'sb0000000000101101;
  assign alpha1_D_Lookup_Table2_3[72] = 16'sb0000100101001110;
  assign alpha1_D_Lookup_Table2_3[73] = 16'sb0001000000101000;
  assign alpha1_D_Lookup_Table2_3[74] = 16'sb0000010101101000;
  assign alpha1_D_Lookup_Table2_3[75] = 16'sb0000010111000101;
  assign alpha1_D_Lookup_Table2_3[76] = 16'sb0000100111001010;
  assign alpha1_D_Lookup_Table2_3[77] = 16'sb1111110110100010;
  assign alpha1_D_Lookup_Table2_3[78] = 16'sb1111110101101100;
  assign alpha1_D_Lookup_Table2_3[79] = 16'sb0000001111001101;
  assign alpha1_D_Lookup_Table2_3[80] = 16'sb1111111011101001;
  assign alpha1_D_Lookup_Table2_3[81] = 16'sb0000001111000001;
  assign alpha1_D_Lookup_Table2_3[82] = 16'sb0000001000010010;
  assign alpha1_D_Lookup_Table2_3[83] = 16'sb1111000001100001;
  assign alpha1_D_Lookup_Table2_3[84] = 16'sb1111100101110101;
  assign alpha1_D_Lookup_Table2_3[85] = 16'sb0000101011001111;
  assign alpha1_D_Lookup_Table2_3[86] = 16'sb1111110010111011;
  assign alpha1_D_Lookup_Table2_3[87] = 16'sb1111001110001100;
  assign alpha1_D_Lookup_Table2_3[88] = 16'sb0000000000111011;
  assign alpha1_D_Lookup_Table2_3[89] = 16'sb0000001100000110;
  assign alpha1_D_Lookup_Table2_3[90] = 16'sb1111100010111100;
  assign alpha1_D_Lookup_Table2_3[91] = 16'sb1111010100000101;
  assign alpha1_D_Lookup_Table2_3[92] = 16'sb0000010011101001;
  assign alpha1_D_Lookup_Table2_3[93] = 16'sb0001010000100010;
  assign alpha1_D_Lookup_Table2_3[94] = 16'sb0000010000111000;
  assign alpha1_D_Lookup_Table2_3[95] = 16'sb1111001110010000;
  assign alpha1_D_Lookup_Table2_3[96] = 16'sb1111101000000000;
  assign alpha1_D_Lookup_Table2_3[97] = 16'sb1111100010100111;
  assign alpha1_D_Lookup_Table2_3[98] = 16'sb1111110000101010;
  assign alpha1_D_Lookup_Table2_3[99] = 16'sb0001000100011001;
  assign alpha1_D_Lookup_Table2_3[100] = 16'sb0000101000011101;
  assign alpha1_D_Lookup_Table2_3[101] = 16'sb1111010100011001;
  assign alpha1_D_Lookup_Table2_3[102] = 16'sb1111101101110001;
  assign alpha1_D_Lookup_Table2_3[103] = 16'sb0000001000010010;
  assign alpha1_D_Lookup_Table2_3[104] = 16'sb1111111110000111;
  assign alpha1_D_Lookup_Table2_3[105] = 16'sb0000001011011100;
  assign alpha1_D_Lookup_Table2_3[106] = 16'sb1111111101110111;
  assign alpha1_D_Lookup_Table2_3[107] = 16'sb1111111100011000;
  assign alpha1_D_Lookup_Table2_3[108] = 16'sb0000010111001001;
  assign alpha1_D_Lookup_Table2_3[109] = 16'sb1111111111010011;
  assign alpha1_D_Lookup_Table2_3[110] = 16'sb1111111110000000;
  assign alpha1_D_Lookup_Table2_3[111] = 16'sb0000101001011101;
  assign alpha1_D_Lookup_Table2_3[112] = 16'sb0000101011101001;
  assign alpha1_D_Lookup_Table2_3[113] = 16'sb0000101000000111;
  assign alpha1_D_Lookup_Table2_3[114] = 16'sb0000000011101111;
  assign alpha1_D_Lookup_Table2_3[115] = 16'sb1111000101011011;
  assign alpha1_D_Lookup_Table2_3[116] = 16'sb0000000111110111;
  assign alpha1_D_Lookup_Table2_3[117] = 16'sb0001001000000101;
  assign alpha1_D_Lookup_Table2_3[118] = 16'sb1111111110011010;
  assign alpha1_D_Lookup_Table2_3[119] = 16'sb0000001110010111;
  assign alpha1_D_Lookup_Table2_3[120] = 16'sb0001100101000010;
  assign alpha1_D_Lookup_Table2_3[121] = 16'sb0001000111111100;
  assign alpha1_D_Lookup_Table2_3[122] = 16'sb0000110101101000;
  assign alpha1_D_Lookup_Table2_3[123] = 16'sb0000101000011001;
  assign alpha1_D_Lookup_Table2_3[124] = 16'sb1111001101000011;
  assign alpha1_D_Lookup_Table2_3[125] = 16'sb1111010101001111;
  assign alpha1_D_Lookup_Table2_3[126] = 16'sb0000000100100001;
  assign alpha1_D_Lookup_Table2_3[127] = 16'sb1111000101000001;
  assign alpha1_D_Lookup_Table2_3[128] = 16'sb1111001111000010;
  assign alpha1_D_Lookup_Table2_3[129] = 16'sb0000001111111001;
  assign alpha1_D_Lookup_Table2_3[130] = 16'sb1111101010101111;
  assign alpha1_D_Lookup_Table2_3[131] = 16'sb1111101111111111;
  assign alpha1_D_Lookup_Table2_3[132] = 16'sb0000001100101100;
  assign alpha1_D_Lookup_Table2_3[133] = 16'sb1111000010010101;
  assign alpha1_D_Lookup_Table2_3[134] = 16'sb1111001011000010;
  assign alpha1_D_Lookup_Table2_3[135] = 16'sb0000101011100000;
  assign alpha1_D_Lookup_Table2_3[136] = 16'sb0000000111101101;
  assign alpha1_D_Lookup_Table2_3[137] = 16'sb1111000010010000;
  assign alpha1_D_Lookup_Table2_3[138] = 16'sb1111101100011110;
  assign alpha1_D_Lookup_Table2_3[139] = 16'sb0000011010011111;
  assign alpha1_D_Lookup_Table2_3[140] = 16'sb0000000011100110;
  assign alpha1_D_Lookup_Table2_3[141] = 16'sb1111100011000001;
  assign alpha1_D_Lookup_Table2_3[142] = 16'sb1111110001101101;
  assign alpha1_D_Lookup_Table2_3[143] = 16'sb1111111111111001;
  assign alpha1_D_Lookup_Table2_3[144] = 16'sb1111001101100000;
  assign alpha1_D_Lookup_Table2_3[145] = 16'sb1110111111001100;
  assign alpha1_D_Lookup_Table2_3[146] = 16'sb1111111100110010;
  assign alpha1_D_Lookup_Table2_3[147] = 16'sb1111111001000111;
  assign alpha1_D_Lookup_Table2_3[148] = 16'sb1111001110011000;
  assign alpha1_D_Lookup_Table2_3[149] = 16'sb1111100110111011;
  assign alpha1_D_Lookup_Table2_3[150] = 16'sb1111111111100110;
  assign alpha1_D_Lookup_Table2_3[151] = 16'sb0000001101101000;
  assign alpha1_D_Lookup_Table2_3[152] = 16'sb0000100011010111;
  assign alpha1_D_Lookup_Table2_3[153] = 16'sb1111101000111111;
  assign alpha1_D_Lookup_Table2_3[154] = 16'sb1110110000110001;
  assign alpha1_D_Lookup_Table2_3[155] = 16'sb1111111000111110;
  assign alpha1_D_Lookup_Table2_3[156] = 16'sb0000101101001101;
  assign alpha1_D_Lookup_Table2_3[157] = 16'sb1111111010001001;
  assign alpha1_D_Lookup_Table2_3[158] = 16'sb1111110110100110;
  assign alpha1_D_Lookup_Table2_3[159] = 16'sb0000100000101100;
  assign alpha1_D_Lookup_Table2_3[160] = 16'sb0000000000000000;
  assign alpha1_D_Lookup_Table2_3[161] = 16'sb1111011111010100;
  assign alpha1_D_Lookup_Table2_3[162] = 16'sb0000001001011010;
  assign alpha1_D_Lookup_Table2_3[163] = 16'sb0000000101110111;
  assign alpha1_D_Lookup_Table2_3[164] = 16'sb1111010010110011;
  assign alpha1_D_Lookup_Table2_3[165] = 16'sb0000000111000010;
  assign alpha1_D_Lookup_Table2_3[166] = 16'sb0001001111001111;
  assign alpha1_D_Lookup_Table2_3[167] = 16'sb0000010111000001;
  assign alpha1_D_Lookup_Table2_3[168] = 16'sb1111011100101001;
  assign alpha1_D_Lookup_Table2_3[169] = 16'sb1111110010011000;
  assign alpha1_D_Lookup_Table2_3[170] = 16'sb0000000000011010;
  assign alpha1_D_Lookup_Table2_3[171] = 16'sb0000011001000101;
  assign alpha1_D_Lookup_Table2_3[172] = 16'sb0000110001101000;
  assign alpha1_D_Lookup_Table2_3[173] = 16'sb0000000110111001;
  assign alpha1_D_Lookup_Table2_3[174] = 16'sb0000000011001110;
  assign alpha1_D_Lookup_Table2_3[175] = 16'sb0001000000110100;
  assign alpha1_D_Lookup_Table2_3[176] = 16'sb0000110010100000;
  assign alpha1_D_Lookup_Table2_3[177] = 16'sb0000000000000111;
  assign alpha1_D_Lookup_Table2_3[178] = 16'sb0000001110010011;
  assign alpha1_D_Lookup_Table2_3[179] = 16'sb0000011100111111;
  assign alpha1_D_Lookup_Table2_3[180] = 16'sb1111111100011010;
  assign alpha1_D_Lookup_Table2_3[181] = 16'sb1111100101100001;
  assign alpha1_D_Lookup_Table2_3[182] = 16'sb0000010011100010;
  assign alpha1_D_Lookup_Table2_3[183] = 16'sb0000111101110000;
  assign alpha1_D_Lookup_Table2_3[184] = 16'sb1111111000010011;
  assign alpha1_D_Lookup_Table2_3[185] = 16'sb1111010100100000;
  assign alpha1_D_Lookup_Table2_3[186] = 16'sb0000110100111110;
  assign alpha1_D_Lookup_Table2_3[187] = 16'sb0000111101101011;
  assign alpha1_D_Lookup_Table2_3[188] = 16'sb1111110011010100;
  assign alpha1_D_Lookup_Table2_3[189] = 16'sb0000010000000001;
  assign alpha1_D_Lookup_Table2_3[190] = 16'sb0000010101010001;
  assign alpha1_D_Lookup_Table2_3[191] = 16'sb1111110000000111;
  assign alpha1_D_Lookup_Table2_3[192] = 16'sb0000110000111110;
  assign alpha1_D_Lookup_Table2_3[193] = 16'sb0000111010111111;
  assign alpha1_D_Lookup_Table2_3[194] = 16'sb1111111011011111;
  assign alpha1_D_Lookup_Table2_3[195] = 16'sb0000101010110001;
  assign alpha1_D_Lookup_Table2_3[196] = 16'sb0000110010111101;
  assign alpha1_D_Lookup_Table2_3[197] = 16'sb1111010111100111;
  assign alpha1_D_Lookup_Table2_3[198] = 16'sb1111001010011000;
  assign alpha1_D_Lookup_Table2_3[199] = 16'sb1110111000000100;
  assign alpha1_D_Lookup_Table2_3[200] = 16'sb1110011010111110;
  assign alpha1_D_Lookup_Table2_3[201] = 16'sb1111110001101001;
  assign alpha1_D_Lookup_Table2_3[202] = 16'sb0000000001100110;
  assign alpha1_D_Lookup_Table2_3[203] = 16'sb1110110111111011;
  assign alpha1_D_Lookup_Table2_3[204] = 16'sb1111111000001001;
  assign alpha1_D_Lookup_Table2_3[205] = 16'sb0000111010100101;
  assign alpha1_D_Lookup_Table2_3[206] = 16'sb1111111100010001;
  assign alpha1_D_Lookup_Table2_3[207] = 16'sb1111010111111001;
  assign alpha1_D_Lookup_Table2_3[208] = 16'sb1111010100010111;
  assign alpha1_D_Lookup_Table2_3[209] = 16'sb1111010110100011;
  assign alpha1_D_Lookup_Table2_3[210] = 16'sb0000000010000000;
  assign alpha1_D_Lookup_Table2_3[211] = 16'sb0000000000101101;
  assign alpha1_D_Lookup_Table2_3[212] = 16'sb1111101000110111;
  assign alpha1_D_Lookup_Table2_3[213] = 16'sb0000000011101000;
  assign alpha1_D_Lookup_Table2_3[214] = 16'sb0000000010001001;
  assign alpha1_D_Lookup_Table2_3[215] = 16'sb1111110100100100;
  assign alpha1_D_Lookup_Table2_3[216] = 16'sb0000000001111001;
  assign alpha1_D_Lookup_Table2_3[217] = 16'sb1111110111101110;
  assign alpha1_D_Lookup_Table2_3[218] = 16'sb0000010010001111;
  assign alpha1_D_Lookup_Table2_3[219] = 16'sb0000101011100111;
  assign alpha1_D_Lookup_Table2_3[220] = 16'sb1111010111100011;
  assign alpha1_D_Lookup_Table2_3[221] = 16'sb1110111011100111;
  assign alpha1_D_Lookup_Table2_3[222] = 16'sb0000001111010110;
  assign alpha1_D_Lookup_Table2_3[223] = 16'sb0000011101011001;
  assign alpha1_D_Lookup_Table2_3[224] = 16'sb0000011000000000;
  assign alpha1_D_Lookup_Table2_3[225] = 16'sb0000110001110000;
  assign alpha1_D_Lookup_Table2_3[226] = 16'sb1111101111001000;
  assign alpha1_D_Lookup_Table2_3[227] = 16'sb1110101111011110;
  assign alpha1_D_Lookup_Table2_3[228] = 16'sb1111101100010111;
  assign alpha1_D_Lookup_Table2_3[229] = 16'sb0000101011111011;
  assign alpha1_D_Lookup_Table2_3[230] = 16'sb0000011101000100;
  assign alpha1_D_Lookup_Table2_3[231] = 16'sb1111110011111010;
  assign alpha1_D_Lookup_Table2_3[232] = 16'sb1111111111000101;
  assign alpha1_D_Lookup_Table2_3[233] = 16'sb0000110001110100;
  assign alpha1_D_Lookup_Table2_3[234] = 16'sb0000001101000101;
  assign alpha1_D_Lookup_Table2_3[235] = 16'sb1111010100110001;
  assign alpha1_D_Lookup_Table2_3[236] = 16'sb0000011010001011;
  assign alpha1_D_Lookup_Table2_3[237] = 16'sb0000111110011111;
  assign alpha1_D_Lookup_Table2_3[238] = 16'sb1111110111101110;
  assign alpha1_D_Lookup_Table2_3[239] = 16'sb1111110000111111;
  assign alpha1_D_Lookup_Table2_3[240] = 16'sb0000000100010111;
  assign alpha1_D_Lookup_Table2_3[241] = 16'sb1111110000110011;
  assign alpha1_D_Lookup_Table2_3[242] = 16'sb0000001010010100;
  assign alpha1_D_Lookup_Table2_3[243] = 16'sb0000001001011110;
  assign alpha1_D_Lookup_Table2_3[244] = 16'sb1111011000110110;
  assign alpha1_D_Lookup_Table2_3[245] = 16'sb1111101000111011;
  assign alpha1_D_Lookup_Table2_3[246] = 16'sb1111101010011000;
  assign alpha1_D_Lookup_Table2_3[247] = 16'sb1110111111011000;
  assign alpha1_D_Lookup_Table2_3[248] = 16'sb1111011010110010;
  assign alpha1_D_Lookup_Table2_3[249] = 16'sb1111111111010011;
  assign alpha1_D_Lookup_Table2_3[250] = 16'sb0000001011100000;
  assign alpha1_D_Lookup_Table2_3[251] = 16'sb0000110101001101;
  assign alpha1_D_Lookup_Table2_3[252] = 16'sb0000011100110010;
  assign alpha1_D_Lookup_Table2_3[253] = 16'sb1111100000101111;
  assign alpha1_D_Lookup_Table2_3[254] = 16'sb1111111100001010;
  assign alpha1_D_Lookup_Table2_3[255] = 16'sb0000000010101000;
  assign alpha1_D_Lookup_Table2_3[256] = 16'sb1111110000111110;
  assign alpha1_D_Lookup_Table2_3[257] = 16'sb0000110111000111;
  assign alpha1_D_Lookup_Table2_3[258] = 16'sb0000111001101111;
  assign alpha1_D_Lookup_Table2_3[259] = 16'sb1111010110110011;
  assign alpha1_D_Lookup_Table2_3[260] = 16'sb1111100111100001;
  assign alpha1_D_Lookup_Table2_3[261] = 16'sb0000101111010011;
  assign alpha1_D_Lookup_Table2_3[262] = 16'sb0000100010001101;
  assign alpha1_D_Lookup_Table2_3[263] = 16'sb0000100011111100;
  assign alpha1_D_Lookup_Table2_3[264] = 16'sb0000101110101111;
  assign alpha1_D_Lookup_Table2_3[265] = 16'sb1111111011101111;
  assign alpha1_D_Lookup_Table2_3[266] = 16'sb1111101011111001;
  assign alpha1_D_Lookup_Table2_3[267] = 16'sb1111111011110010;
  assign alpha1_D_Lookup_Table2_3[268] = 16'sb1111010110001011;
  assign alpha1_D_Lookup_Table2_3[269] = 16'sb1111001101011110;
  assign alpha1_D_Lookup_Table2_3[270] = 16'sb1111111111010011;
  assign alpha1_D_Lookup_Table2_3[271] = 16'sb0000001001100011;
  assign alpha1_D_Lookup_Table2_3[272] = 16'sb0000000010100000;
  assign alpha1_D_Lookup_Table2_3[273] = 16'sb0000010110100101;
  assign alpha1_D_Lookup_Table2_3[274] = 16'sb0000010111000000;
  assign alpha1_D_Lookup_Table2_3[275] = 16'sb0000011001110010;
  assign alpha1_D_Lookup_Table2_3[276] = 16'sb0000101110110001;
  assign alpha1_D_Lookup_Table2_3[277] = 16'sb0000001110010001;
  assign alpha1_D_Lookup_Table2_3[278] = 16'sb1111100010011010;
  assign alpha1_D_Lookup_Table2_3[279] = 16'sb1111111100010100;
  assign alpha1_D_Lookup_Table2_3[280] = 16'sb0000010000011100;
  assign alpha1_D_Lookup_Table2_3[281] = 16'sb1111110111110111;
  assign alpha1_D_Lookup_Table2_3[282] = 16'sb1111101101101100;
  assign alpha1_D_Lookup_Table2_3[283] = 16'sb1111011010001001;
  assign alpha1_D_Lookup_Table2_3[284] = 16'sb1111000100101111;
  assign alpha1_D_Lookup_Table2_3[285] = 16'sb1111111110000011;
  assign alpha1_D_Lookup_Table2_3[286] = 16'sb0001001000000110;
  assign alpha1_D_Lookup_Table2_3[287] = 16'sb0000111101110100;
  assign imagOut_2 = alpha1_D_Lookup_Table2_3[prelookup_idx_1];



  always @(posedge clk)
    begin : PipelineRegister_3_process
      if (enb) begin
        imagOut_3 <= imagOut_2;
      end
    end



  assign Multiport_Switch2_out1_re = (Delay10_out1 == 1'b0 ? realOut_1 :
              realOut_3);
  assign Multiport_Switch2_out1_im = (Delay10_out1 == 1'b0 ? imagOut_1 :
              imagOut_3);



  always @(posedge clk or posedge reset)
    begin : Delay13_process
      if (reset == 1'b1) begin
        for(Delay13_t_1 = 32'sd0; Delay13_t_1 <= 32'sd1026; Delay13_t_1 = Delay13_t_1 + 32'sd1) begin
          Delay13_reg_re[Delay13_t_1] <= 16'sb0000000000000000;
          Delay13_reg_im[Delay13_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(Delay13_t_0_1 = 32'sd0; Delay13_t_0_1 <= 32'sd1026; Delay13_t_0_1 = Delay13_t_0_1 + 32'sd1) begin
            Delay13_reg_re[Delay13_t_0_1] <= Delay13_reg_next_re[Delay13_t_0_1];
            Delay13_reg_im[Delay13_t_0_1] <= Delay13_reg_next_im[Delay13_t_0_1];
          end
        end
      end
    end

  always @* begin
    Delay13_out1_re = Delay13_reg_re[1026];
    Delay13_out1_im = Delay13_reg_im[1026];
    Delay13_reg_next_re[0] = Multiport_Switch2_out1_re;
    Delay13_reg_next_im[0] = Multiport_Switch2_out1_im;

    for(Delay13_t_0_0 = 32'sd0; Delay13_t_0_0 <= 32'sd1025; Delay13_t_0_0 = Delay13_t_0_0 + 32'sd1) begin
      Delay13_reg_next_re[Delay13_t_0_0 + 32'sd1] = Delay13_reg_re[Delay13_t_0_0];
      Delay13_reg_next_im[Delay13_t_0_0 + 32'sd1] = Delay13_reg_im[Delay13_t_0_0];
    end

  end



  assign Constant4_out1_re = 32'sb00000000000000000000000000000000;
  assign Constant4_out1_im = 32'sb00000000000000000000000000000000;



  always @(posedge clk or posedge reset)
    begin : Delay16_process
      if (reset == 1'b1) begin
        Delay16_out1 <= 2'b00;
      end
      else begin
        if (enb) begin
          Delay16_out1 <= datain;
        end
      end
    end



  assign alpha_table_data_re[0] = 16'sb1111111111110000;
  assign alpha_table_data_re[1] = 16'sb1111111111110000;
  assign alpha_table_data_re[2] = 16'sb0000000000010000;
  assign alpha_table_data_re[3] = 16'sb0000000000010000;
  assign alpha_table_data_im[0] = 16'sb0000000000010000;
  assign alpha_table_data_im[1] = 16'sb1111111111110000;
  assign alpha_table_data_im[2] = 16'sb0000000000010000;
  assign alpha_table_data_im[3] = 16'sb1111111111110000;
  assign Rectangular_QAM_Modulator_Baseband_out1_re = alpha_table_data_re[Delay16_out1];
  assign Rectangular_QAM_Modulator_Baseband_out1_im = alpha_table_data_im[Delay16_out1];



  assign Gain8_out = {{11{Rectangular_QAM_Modulator_Baseband_out1_re[15]}}, {Rectangular_QAM_Modulator_Baseband_out1_re, 5'b00000}};



  assign Gain8_out_1 = {{11{Rectangular_QAM_Modulator_Baseband_out1_im[15]}}, {Rectangular_QAM_Modulator_Baseband_out1_im, 5'b00000}};



  always @(posedge clk or posedge reset)
    begin : Delay6_process
      if (reset == 1'b1) begin
        Delay6_out1_re <= 32'sb00000000000000000000000000000000;
        Delay6_out1_im <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay6_out1_re <= Gain8_out;
          Delay6_out1_im <= Gain8_out_1;
        end
      end
    end



  assign Multiport_Switch3_out1_re = (Compare_To_Constant_out1_2 == 1'b0 ? Constant4_out1_re :
              Delay6_out1_re);
  assign Multiport_Switch3_out1_im = (Compare_To_Constant_out1_2 == 1'b0 ? Constant4_out1_im :
              Delay6_out1_im);



  assign Compare_To_Constant1_out1 = Counter_Limited_out1 <= 16'b0000000010110011;



  always @(posedge clk or posedge reset)
    begin : Delay25_process
      if (reset == 1'b1) begin
        Delay25_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay25_out1 <= Compare_To_Constant1_out1;
        end
      end
    end



  assign AND1_out1 = Compare_To_Constant_out1 & Delay25_out1;



  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay_out1 <= AND1_out1;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : Delay5_process
      if (reset == 1'b1) begin
        Delay5_reg <= {2{1'b0}};
      end
      else begin
        if (enb) begin
          Delay5_reg[0] <= Delay_out1;
          Delay5_reg[1] <= Delay5_reg[0];
        end
      end
    end

  assign Delay5_out1 = Delay5_reg[1];



  OFDM_Modulator u_OFDM_Modulator (.clk(clk),
                                   .reset(reset),
                                   .enb(clk_enable),
                                   .enb_1_1_1(clk_enable),
                                   .data_re(Multiport_Switch3_out1_re),  // sfix32_En8
                                   .data_im(Multiport_Switch3_out1_im),  // sfix32_En8
                                   .valid(Delay5_out1),
                                   .data1_re(data_re),  // sfix32_En8
                                   .data1_im(data_im)  // sfix32_En8
                                   );

  assign Data_Type_Conversion4_out1_re = {data_re[9:0], 6'b000000};
  assign Data_Type_Conversion4_out1_im = {data_im[9:0], 6'b000000};



  always @(posedge clk or posedge reset)
    begin : Delay14_process
      if (reset == 1'b1) begin
        Delay14_out1_re <= 16'sb0000000000000000;
        Delay14_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay14_out1_re <= Data_Type_Conversion4_out1_re;
          Delay14_out1_im <= Data_Type_Conversion4_out1_im;
        end
      end
    end



  assign Saturation_out1 = (Delay14_out1_re > 16'sb0100000000000000 ? 16'sb0100000000000000 :
              (Delay14_out1_re < 16'sb1100000000000000 ? 16'sb1100000000000000 :
              Delay14_out1_re));



  assign Saturation1_out1 = (Delay14_out1_im > 16'sb0100000000000000 ? 16'sb0100000000000000 :
              (Delay14_out1_im < 16'sb1100000000000000 ? 16'sb1100000000000000 :
              Delay14_out1_im));



  assign Multiport_Switch1_out1_re = (Compare_To_Constant_out1_3 == 1'b0 ? Delay13_out1_re :
              Saturation_out1);
  assign Multiport_Switch1_out1_im = (Compare_To_Constant_out1_3 == 1'b0 ? Delay13_out1_im :
              Saturation1_out1);



  always @(posedge clk or posedge reset)
    begin : Delay15_process
      if (reset == 1'b1) begin
        Delay15_out1_re <= 16'sb0000000000000000;
        Delay15_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay15_out1_re <= Multiport_Switch1_out1_re;
          Delay15_out1_im <= Multiport_Switch1_out1_im;
        end
      end
    end



  assign rf_wave_out_re = Delay15_out1_re;

  assign rf_wave_out_im = Delay15_out1_im;

  assign datain_ready = Delay_out1;

  assign ce_out = clk_enable;

endmodule  // OFDM_TXSYS

