// -------------------------------------------------------------
// 
// File Name: D:\OFDM- HDL\simulation\baseband\v8\src\Tx\Zed_ofdm64\OFDM_Modulator.v
// Created: 2025-04-21 20:44:15
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: OFDM_Modulator
// Source Path: Zed_ofdm64/top_all/tx_top/OFDM_TXSYS/OFDM Modulator
// Hierarchy Level: 1
// Model version: 3.61
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module OFDM_Modulator
          (clk,
           reset,
           enb,
           enb_1_1_1,
           data_re,
           data_im,
           valid,
           data1_re,
           data1_im);


  input   clk;
  input   reset;
  input   enb;
  input   enb_1_1_1;
  input   signed [31:0] data_re;  // sfix32_En8
  input   signed [31:0] data_im;  // sfix32_En8
  input   valid;
  output  signed [31:0] data1_re;  // sfix32_En8
  output  signed [31:0] data1_im;  // sfix32_En8


  wire out;
  wire out_1;
  wire obj_readyLowFlag;
  wire out_2;
  wire out_3;
  wire [13:0] obj_readyLowCount;  // ufix14
  wire [13:0] obj_FFTLengthReg;  // ufix14
  wire [13:0] obj_CPLengthReg;  // ufix14
  wire [13:0] tmp;  // ufix14
  wire [13:0] obj_numLgScReg;  // ufix14
  wire [13:0] obj_insertDC;  // ufix14
  wire [13:0] obj_numRgScReg;  // ufix14
  wire [13:0] tmp_1;  // ufix14
  wire [13:0] tmp_2;  // ufix14
  wire [13:0] tmp_3;  // ufix14
  wire [13:0] tmp_4;  // ufix14
  wire obj_readyLowFlag_1;
  wire out_4;
  wire out_5;
  wire obj_validInHighFlag;
  wire out_6;
  wire out_7;
  wire [13:0] obj_validInHighCount;  // ufix14
  wire obj_validInHighFlag_1;
  wire out_8;
  wire out_9;
  wire obj_readyOut;
  wire obj_readyOut_1;
  wire obj_readyOut_2;
  wire obj_readyOut_3;
  wire out_10;
  wire out_11;
  wire tmp_5;
  wire tmp_6;
  wire tmp_7;
  wire tmp_8;
  reg [13:0] obj_validInHighCount_1;  // ufix14
  wire [13:0] tmp_9;  // ufix14
  wire [13:0] tmp_10;  // ufix14
  wire [13:0] tmp_11;  // ufix14
  wire [13:0] tmp_12;  // ufix14
  wire tmp_13;
  wire [13:0] tmp_14;  // ufix14
  wire tmp_15;
  wire tmp_16;
  reg [13:0] obj_readyLowCount_1;  // ufix14
  wire [13:0] tmp_17;  // ufix14
  wire [13:0] tmp_18;  // ufix14
  wire [13:0] tmp_19;  // ufix14
  wire [13:0] tmp_20;  // ufix14
  wire [13:0] tmp_21;  // ufix14
  wire tmp_22;
  wire tmp_23;
  wire tmp_24;
  wire tmp_25;
  wire tmp_26;
  reg  obj_readyLowFlag_2;
  reg  obj_validInHighFlag_2;
  wire tmp_27;
  wire tmp_28;
  wire tmp_29;
  wire tmp_30;
  wire tmp_31;
  wire tmp_32;
  wire tmp_33;
  wire tmp_34;
  wire tmp_35;
  wire tmp_36;
  wire tmp_37;
  wire tmp_38;
  reg  obj_delayedReady;
  wire tmp_39;
  wire signed [31:0] varargout_1_re;  // sfix32_En8
  wire signed [31:0] varargout_1_im;  // sfix32_En8
  wire varargout_2;
  wire signed [31:0] varargout_1_re_1;  // sfix32_En8
  wire signed [31:0] varargout_1_im_1;  // sfix32_En8
  wire varargout_2_1;
  wire signed [31:0] varargout_1_re_2;  // sfix32_En8
  wire signed [31:0] varargout_1_im_2;  // sfix32_En8
  wire varargout_2_2;
  wire signed [31:0] varargout_1_re_3;  // sfix32_En8
  wire signed [31:0] varargout_1_im_3;  // sfix32_En8
  reg signed [31:0] data_re_1;  // sfix32_En8
  reg signed [31:0] data_im_1;  // sfix32_En8


  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp95
  assign out = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp95
  assign out_1 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp87
  assign obj_readyLowFlag = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp130
  assign out_2 = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp130
  assign out_3 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp81
  assign obj_readyLowCount = 14'b00000000000000;



  assign obj_FFTLengthReg = 14'b00000100000000;



  assign obj_CPLengthReg = 14'b00000000100000;



  assign tmp = obj_FFTLengthReg + obj_CPLengthReg;



  assign obj_numLgScReg = 14'b00000000100110;



  assign obj_insertDC = 14'b00000000000001;



  assign obj_numRgScReg = 14'b00000000100101;



  assign tmp_1 = obj_numLgScReg + obj_numRgScReg;



  assign tmp_2 = obj_insertDC + tmp_1;



  assign tmp_3 = obj_FFTLengthReg - tmp_2;



  assign tmp_4 = tmp - tmp_3;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp109
  assign obj_readyLowFlag_1 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp100
  assign out_4 = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp100
  assign out_5 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp84
  assign obj_validInHighFlag = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp135
  assign out_6 = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp135
  assign out_7 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp78
  assign obj_validInHighCount = 14'b00000000000000;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp120
  assign obj_validInHighFlag_1 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp105
  assign out_8 = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp105
  assign out_9 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp90
  assign obj_readyOut = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp90
  assign obj_readyOut_1 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp74
  assign obj_readyOut_2 = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp58
  assign obj_readyOut_3 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp165
  assign out_10 = 1'b0;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp165
  assign out_11 = 1'b1;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp74
  assign tmp_6 = (tmp_5 == 1'b0 ? obj_readyOut :
              obj_readyOut_1);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp58
  assign tmp_8 = (tmp_7 == 1'b0 ? tmp_6 :
              obj_readyOut_2);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp126
  assign tmp_9 = obj_validInHighCount_1 + 14'b00000000000001;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp62
  assign tmp_11 = (tmp_5 == 1'b0 ? tmp_10 :
              obj_validInHighCount);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp42
  assign tmp_12 = (tmp_7 == 1'b0 ? tmp_11 :
              tmp_10);



  assign tmp_14 = (tmp_13 == 1'b0 ? tmp_12 :
              tmp_10);



  always @(posedge clk or posedge reset)
    begin : obj_validInHighCount_reg_process
      if (reset == 1'b1) begin
        obj_validInHighCount_1 <= 14'b00000000000000;
      end
      else begin
        if (enb) begin
          obj_validInHighCount_1 <= tmp_14;
        end
      end
    end



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp68
  assign tmp_16 = (tmp_5 == 1'b0 ? tmp_15 :
              obj_validInHighFlag);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_trueregionp123
  assign tmp_17 = obj_readyLowCount_1 + 14'b00000000000001;



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp65
  assign tmp_19 = (tmp_5 == 1'b0 ? tmp_18 :
              obj_readyLowCount);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp46
  assign tmp_20 = (tmp_7 == 1'b0 ? tmp_19 :
              tmp_18);



  assign tmp_21 = (tmp_13 == 1'b0 ? tmp_20 :
              tmp_18);



  always @(posedge clk or posedge reset)
    begin : obj_readyLowCount_reg_process
      if (reset == 1'b1) begin
        obj_readyLowCount_1 <= 14'b00000000000000;
      end
      else begin
        if (enb) begin
          obj_readyLowCount_1 <= tmp_21;
        end
      end
    end



  assign tmp_23 = tmp_15 && tmp_22;



  assign tmp_5 = (tmp_23 == 1'b0 ? out :
              out_1);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp71
  assign tmp_24 = (tmp_5 == 1'b0 ? tmp_22 :
              obj_readyLowFlag);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp54
  assign tmp_25 = (tmp_7 == 1'b0 ? tmp_24 :
              tmp_22);



  assign tmp_26 = (tmp_13 == 1'b0 ? tmp_25 :
              tmp_22);



  always @(posedge clk or posedge reset)
    begin : obj_readyLowFlag_reg_process
      if (reset == 1'b1) begin
        obj_readyLowFlag_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_readyLowFlag_2 <= tmp_26;
        end
      end
    end



  assign tmp_27 = obj_validInHighFlag_2 && ( ! obj_readyLowFlag_2);



  assign tmp_28 = (tmp_27 == 1'b0 ? out_2 :
              out_3);



  assign tmp_18 = (tmp_28 == 1'b0 ? obj_readyLowCount_1 :
              tmp_17);



  assign tmp_29 = tmp_18 == tmp_4;



  assign tmp_22 = (tmp_29 == 1'b0 ? obj_readyLowFlag_2 :
              obj_readyLowFlag_1);



  assign tmp_30 = tmp_15 && ( ! tmp_22);



  assign tmp_7 = (tmp_30 == 1'b0 ? out_4 :
              out_5);



  // HDL code generation from MATLAB function: SystemCore_stepImpl_falseregionp50
  assign tmp_31 = (tmp_7 == 1'b0 ? tmp_16 :
              tmp_15);



  assign tmp_32 = (tmp_13 == 1'b0 ? tmp_31 :
              tmp_15);



  always @(posedge clk or posedge reset)
    begin : obj_validInHighFlag_reg_process
      if (reset == 1'b1) begin
        obj_validInHighFlag_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_validInHighFlag_2 <= tmp_32;
        end
      end
    end



  assign tmp_34 = tmp_33 && ( ! obj_validInHighFlag_2);



  assign tmp_35 = (tmp_34 == 1'b0 ? out_6 :
              out_7);



  assign tmp_10 = (tmp_35 == 1'b0 ? obj_validInHighCount_1 :
              tmp_9);



  assign tmp_36 = tmp_10 == tmp_3;



  assign tmp_15 = (tmp_36 == 1'b0 ? obj_validInHighFlag_2 :
              obj_validInHighFlag_1);



  assign tmp_37 = ( ! tmp_15) && ( ! tmp_22);



  assign tmp_13 = (tmp_37 == 1'b0 ? out_8 :
              out_9);



  assign tmp_38 = (tmp_13 == 1'b0 ? tmp_8 :
              obj_readyOut_3);



  always @(posedge clk or posedge reset)
    begin : obj_delayedReady_reg_process
      if (reset == 1'b1) begin
        obj_delayedReady <= 1'b1;
      end
      else begin
        if (enb) begin
          obj_delayedReady <= tmp_38;
        end
      end
    end



  assign tmp_39 = obj_delayedReady && valid;



  assign tmp_33 = (tmp_39 == 1'b0 ? out_10 :
              out_11);



  symbolFormation u_symbolFormation (.clk(clk),
                                     .reset(reset),
                                     .enb(enb),
                                     .enb_1_1_1(enb_1_1_1),
                                     .tmp_re(data_re),  // sfix32_En8
                                     .tmp_im(data_im),  // sfix32_En8
                                     .tmp(tmp_33),
                                     .varargout_1_re(varargout_1_re),  // sfix32_En8
                                     .varargout_1_im(varargout_1_im),  // sfix32_En8
                                     .varargout_2(varargout_2)
                                     );

  dsphdl_IFFT u_dsphdl_IFFT (.clk(clk),
                             .reset(reset),
                             .enb(enb),
                             .enb_1_1_1(enb_1_1_1),
                             .dataIn_re(varargout_1_re),  // sfix32_En8
                             .dataIn_im(varargout_1_im),  // sfix32_En8
                             .validIn(varargout_2),
                             .dataOut_re(varargout_1_re_1),  // sfix32_En8
                             .dataOut_im(varargout_1_im_1),  // sfix32_En8
                             .validOut(varargout_2_1)
                             );

  HDLFFTShiftMod u_HDLFFTShiftMod (.clk(clk),
                                   .reset(reset),
                                   .enb(enb),
                                   .varargout_1_re(varargout_1_re_1),  // sfix32_En8
                                   .varargout_1_im(varargout_1_im_1),  // sfix32_En8
                                   .varargout_2(varargout_2_1),
                                   .varargout_1_re_1(varargout_1_re_2),  // sfix32_En8
                                   .varargout_1_im_1(varargout_1_im_2),  // sfix32_En8
                                   .varargout_2_1(varargout_2_2)
                                   );

  CPAddition u_CPAddition (.clk(clk),
                           .reset(reset),
                           .enb(enb),
                           .enb_1_1_1(enb_1_1_1),
                           .varargout_1_re(varargout_1_re_2),  // sfix32_En8
                           .varargout_1_im(varargout_1_im_2),  // sfix32_En8
                           .varargout_2(varargout_2_2),
                           .varargout_1_re_1(varargout_1_re_3),  // sfix32_En8
                           .varargout_1_im_1(varargout_1_im_3)  // sfix32_En8
                           );

  always @(posedge clk or posedge reset)
    begin : obj_dataOut_reg_process
      if (reset == 1'b1) begin
        data_re_1 <= 32'sb00000000000000000000000000000000;
        data_im_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          data_re_1 <= varargout_1_re_3;
          data_im_1 <= varargout_1_im_3;
        end
      end
    end



  assign data1_re = data_re_1;

  assign data1_im = data_im_1;

endmodule  // OFDM_Modulator

