// -------------------------------------------------------------
// 
// File Name: D:\OFDM- HDL\simulation\baseband\v8\src\Tx\Zed_ofdm64\RADIX22FFT_SDF1_7.v
// Created: 2025-04-21 20:44:15
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RADIX22FFT_SDF1_7
// Source Path: dsphdl.IFFT/RADIX22FFT_SDF1_7
// Hierarchy Level: 3
// Model version: 3.61
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_SDF1_7
          (clk,
           reset,
           enb,
           enb_1_1_1,
           din_7_1_re_dly,
           din_7_1_im_dly,
           din_7_vld_dly,
           rd_7_Addr,
           rd_7_Enb,
           twdl_7_1_re,
           twdl_7_1_im,
           proc_7_enb,
           dout_7_1_re,
           dout_7_1_im,
           dout_7_1_vld,
           dinXTwdl_7_1_vld);


  input   clk;
  input   reset;
  input   enb;
  input   enb_1_1_1;
  input   signed [31:0] din_7_1_re_dly;  // sfix32_En8
  input   signed [31:0] din_7_1_im_dly;  // sfix32_En8
  input   din_7_vld_dly;
  input   rd_7_Addr;  // ufix1
  input   rd_7_Enb;
  input   signed [31:0] twdl_7_1_re;  // sfix32_En30
  input   signed [31:0] twdl_7_1_im;  // sfix32_En30
  input   proc_7_enb;
  output  signed [31:0] dout_7_1_re;  // sfix32_En8
  output  signed [31:0] dout_7_1_im;  // sfix32_En8
  output  dout_7_1_vld;
  output  dinXTwdl_7_1_vld;


  wire signed [31:0] dinXTwdl_re;  // sfix32_En8
  wire signed [31:0] dinXTwdl_im;  // sfix32_En8
  reg  x_vld;
  wire signed [31:0] wrData_re;  // sfix32_En8
  wire signed [31:0] wrData_im;  // sfix32_En8
  wire wrAddr;  // ufix1
  wire wrEnb;
  reg signed [31:0] twoLocationReg_0_MEM_re_0;  // sfix32
  reg signed [31:0] twoLocationReg_0_MEM_im_0;  // sfix32
  reg signed [31:0] twoLocationReg_0_MEM_re_1;  // sfix32
  reg signed [31:0] twoLocationReg_0_MEM_im_1;  // sfix32
  reg signed [31:0] twoLocationReg_0_dout_re_reg;  // sfix32
  reg signed [31:0] twoLocationReg_0_dout_im_reg;  // sfix32
  reg signed [31:0] twoLocationReg_0_MEM_re_0_next;  // sfix32_En8
  reg signed [31:0] twoLocationReg_0_MEM_im_0_next;  // sfix32_En8
  reg signed [31:0] twoLocationReg_0_MEM_re_1_next;  // sfix32_En8
  reg signed [31:0] twoLocationReg_0_MEM_im_1_next;  // sfix32_En8
  reg signed [31:0] twoLocationReg_0_dout_re_reg_next;  // sfix32_En8
  reg signed [31:0] twoLocationReg_0_dout_im_reg_next;  // sfix32_En8
  reg signed [31:0] x_re;  // sfix32_En8
  reg signed [31:0] x_im;  // sfix32_En8
  reg signed [32:0] Radix22ButterflyG1_btf1_re_reg;  // sfix33
  reg signed [32:0] Radix22ButterflyG1_btf1_im_reg;  // sfix33
  reg signed [32:0] Radix22ButterflyG1_btf2_re_reg;  // sfix33
  reg signed [32:0] Radix22ButterflyG1_btf2_im_reg;  // sfix33
  reg signed [31:0] Radix22ButterflyG1_x_re_dly1;  // sfix32
  reg signed [31:0] Radix22ButterflyG1_x_im_dly1;  // sfix32
  reg  Radix22ButterflyG1_x_vld_dly1;
  reg signed [31:0] Radix22ButterflyG1_dinXtwdl_re_dly1;  // sfix32
  reg signed [31:0] Radix22ButterflyG1_dinXtwdl_im_dly1;  // sfix32
  reg signed [31:0] Radix22ButterflyG1_dinXtwdl_re_dly2;  // sfix32
  reg signed [31:0] Radix22ButterflyG1_dinXtwdl_im_dly2;  // sfix32
  reg  Radix22ButterflyG1_dinXtwdl_vld_dly1;
  reg  Radix22ButterflyG1_dinXtwdl_vld_dly2;
  wire signed [32:0] Radix22ButterflyG1_btf1_re_reg_next;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_btf1_im_reg_next;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_btf2_re_reg_next;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_btf2_im_reg_next;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_add_cast;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_add_cast_1;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_sub_cast;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_sub_cast_1;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_add_cast_2;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_add_cast_3;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_sub_cast_2;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_sub_cast_3;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_sra_temp;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_sra_temp_1;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_sra_temp_2;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_sra_temp_3;  // sfix33_En8
  reg signed [31:0] xf_re;  // sfix32_En8
  reg signed [31:0] xf_im;  // sfix32_En8
  reg  xf_vld;
  wire signed [31:0] dinXTwdlf_re;  // sfix32_En8
  wire signed [31:0] dinXTwdlf_im;  // sfix32_En8
  wire dinxTwdlf_vld;
  wire signed [31:0] btf1_re;  // sfix32_En8
  wire signed [31:0] btf1_im;  // sfix32_En8
  wire signed [31:0] btf2_re;  // sfix32_En8
  wire signed [31:0] btf2_im;  // sfix32_En8
  reg  btf_vld;


  Complex4Multiply_block1 u_MUL4 (.clk(clk),
                                  .reset(reset),
                                  .enb(enb),
                                  .din_7_1_re_dly(din_7_1_re_dly),  // sfix32_En8
                                  .din_7_1_im_dly(din_7_1_im_dly),  // sfix32_En8
                                  .din_7_vld_dly(din_7_vld_dly),
                                  .twdl_7_1_re(twdl_7_1_re),  // sfix32_En30
                                  .twdl_7_1_im(twdl_7_1_im),  // sfix32_En30
                                  .dinXTwdl_re(dinXTwdl_re),  // sfix32_En8
                                  .dinXTwdl_im(dinXTwdl_im),  // sfix32_En8
                                  .dinXTwdl_7_1_vld(dinXTwdl_7_1_vld)
                                  );

  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld <= rd_7_Enb;
        end
      end
    end



  // twoLocationReg_0
  always @(posedge clk or posedge reset)
    begin : twoLocationReg_0_process
      if (reset == 1'b1) begin
        twoLocationReg_0_MEM_re_0 <= 32'sb00000000000000000000000000000000;
        twoLocationReg_0_MEM_im_0 <= 32'sb00000000000000000000000000000000;
        twoLocationReg_0_MEM_re_1 <= 32'sb00000000000000000000000000000000;
        twoLocationReg_0_MEM_im_1 <= 32'sb00000000000000000000000000000000;
        twoLocationReg_0_dout_re_reg <= 32'sb00000000000000000000000000000000;
        twoLocationReg_0_dout_im_reg <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          twoLocationReg_0_MEM_re_0 <= twoLocationReg_0_MEM_re_0_next;
          twoLocationReg_0_MEM_im_0 <= twoLocationReg_0_MEM_im_0_next;
          twoLocationReg_0_MEM_re_1 <= twoLocationReg_0_MEM_re_1_next;
          twoLocationReg_0_MEM_im_1 <= twoLocationReg_0_MEM_im_1_next;
          twoLocationReg_0_dout_re_reg <= twoLocationReg_0_dout_re_reg_next;
          twoLocationReg_0_dout_im_reg <= twoLocationReg_0_dout_im_reg_next;
        end
      end
    end

  always @(rd_7_Addr, twoLocationReg_0_MEM_im_0, twoLocationReg_0_MEM_im_1,
       twoLocationReg_0_MEM_re_0, twoLocationReg_0_MEM_re_1,
       twoLocationReg_0_dout_im_reg, twoLocationReg_0_dout_re_reg, wrAddr,
       wrData_im, wrData_re, wrEnb) begin
    twoLocationReg_0_MEM_re_0_next = twoLocationReg_0_MEM_re_0;
    twoLocationReg_0_MEM_im_0_next = twoLocationReg_0_MEM_im_0;
    twoLocationReg_0_MEM_re_1_next = twoLocationReg_0_MEM_re_1;
    twoLocationReg_0_MEM_im_1_next = twoLocationReg_0_MEM_im_1;
    if (rd_7_Addr == 1'b1) begin
      twoLocationReg_0_dout_re_reg_next = twoLocationReg_0_MEM_re_1;
      twoLocationReg_0_dout_im_reg_next = twoLocationReg_0_MEM_im_1;
    end
    else begin
      twoLocationReg_0_dout_re_reg_next = twoLocationReg_0_MEM_re_0;
      twoLocationReg_0_dout_im_reg_next = twoLocationReg_0_MEM_im_0;
    end
    if (wrEnb) begin
      if (wrAddr == 1'b1) begin
        twoLocationReg_0_MEM_re_1_next = wrData_re;
        twoLocationReg_0_MEM_im_1_next = wrData_im;
      end
      else begin
        twoLocationReg_0_MEM_re_0_next = wrData_re;
        twoLocationReg_0_MEM_im_0_next = wrData_im;
      end
    end
    x_re = twoLocationReg_0_dout_re_reg;
    x_im = twoLocationReg_0_dout_im_reg;
  end



  // Radix22ButterflyG1
  always @(posedge clk or posedge reset)
    begin : Radix22ButterflyG1_process
      if (reset == 1'b1) begin
        Radix22ButterflyG1_btf1_re_reg <= 33'sh000000000;
        Radix22ButterflyG1_btf1_im_reg <= 33'sh000000000;
        Radix22ButterflyG1_btf2_re_reg <= 33'sh000000000;
        Radix22ButterflyG1_btf2_im_reg <= 33'sh000000000;
        Radix22ButterflyG1_x_re_dly1 <= 32'sb00000000000000000000000000000000;
        Radix22ButterflyG1_x_im_dly1 <= 32'sb00000000000000000000000000000000;
        Radix22ButterflyG1_x_vld_dly1 <= 1'b0;
        xf_re <= 32'sb00000000000000000000000000000000;
        xf_im <= 32'sb00000000000000000000000000000000;
        xf_vld <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_re_dly1 <= 32'sb00000000000000000000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly1 <= 32'sb00000000000000000000000000000000;
        Radix22ButterflyG1_dinXtwdl_re_dly2 <= 32'sb00000000000000000000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly2 <= 32'sb00000000000000000000000000000000;
        Radix22ButterflyG1_dinXtwdl_vld_dly1 <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_vld_dly2 <= 1'b0;
        btf_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          Radix22ButterflyG1_btf1_re_reg <= Radix22ButterflyG1_btf1_re_reg_next;
          Radix22ButterflyG1_btf1_im_reg <= Radix22ButterflyG1_btf1_im_reg_next;
          Radix22ButterflyG1_btf2_re_reg <= Radix22ButterflyG1_btf2_re_reg_next;
          Radix22ButterflyG1_btf2_im_reg <= Radix22ButterflyG1_btf2_im_reg_next;
          xf_re <= Radix22ButterflyG1_x_re_dly1;
          xf_im <= Radix22ButterflyG1_x_im_dly1;
          xf_vld <= Radix22ButterflyG1_x_vld_dly1;
          btf_vld <= Radix22ButterflyG1_dinXtwdl_vld_dly2;
          Radix22ButterflyG1_dinXtwdl_vld_dly2 <= Radix22ButterflyG1_dinXtwdl_vld_dly1;
          Radix22ButterflyG1_dinXtwdl_re_dly2 <= Radix22ButterflyG1_dinXtwdl_re_dly1;
          Radix22ButterflyG1_dinXtwdl_im_dly2 <= Radix22ButterflyG1_dinXtwdl_im_dly1;
          Radix22ButterflyG1_dinXtwdl_re_dly1 <= dinXTwdl_re;
          Radix22ButterflyG1_dinXtwdl_im_dly1 <= dinXTwdl_im;
          Radix22ButterflyG1_x_re_dly1 <= x_re;
          Radix22ButterflyG1_x_im_dly1 <= x_im;
          Radix22ButterflyG1_x_vld_dly1 <= x_vld;
          Radix22ButterflyG1_dinXtwdl_vld_dly1 <= proc_7_enb && dinXTwdl_7_1_vld;
        end
      end
    end

  assign dinxTwdlf_vld = ( ! proc_7_enb) && dinXTwdl_7_1_vld;
  assign Radix22ButterflyG1_add_cast = {Radix22ButterflyG1_x_re_dly1[31], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_add_cast_1 = {Radix22ButterflyG1_dinXtwdl_re_dly2[31], Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf1_re_reg_next = Radix22ButterflyG1_add_cast + Radix22ButterflyG1_add_cast_1;
  assign Radix22ButterflyG1_sub_cast = {Radix22ButterflyG1_x_re_dly1[31], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_sub_cast_1 = {Radix22ButterflyG1_dinXtwdl_re_dly2[31], Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf2_re_reg_next = Radix22ButterflyG1_sub_cast - Radix22ButterflyG1_sub_cast_1;
  assign Radix22ButterflyG1_add_cast_2 = {Radix22ButterflyG1_x_im_dly1[31], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_add_cast_3 = {Radix22ButterflyG1_dinXtwdl_im_dly2[31], Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf1_im_reg_next = Radix22ButterflyG1_add_cast_2 + Radix22ButterflyG1_add_cast_3;
  assign Radix22ButterflyG1_sub_cast_2 = {Radix22ButterflyG1_x_im_dly1[31], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_sub_cast_3 = {Radix22ButterflyG1_dinXtwdl_im_dly2[31], Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf2_im_reg_next = Radix22ButterflyG1_sub_cast_2 - Radix22ButterflyG1_sub_cast_3;
  assign dinXTwdlf_re = dinXTwdl_re;
  assign dinXTwdlf_im = dinXTwdl_im;
  assign Radix22ButterflyG1_sra_temp = Radix22ButterflyG1_btf1_re_reg >>> 8'd1;
  assign btf1_re = Radix22ButterflyG1_sra_temp[31:0];
  assign Radix22ButterflyG1_sra_temp_1 = Radix22ButterflyG1_btf1_im_reg >>> 8'd1;
  assign btf1_im = Radix22ButterflyG1_sra_temp_1[31:0];
  assign Radix22ButterflyG1_sra_temp_2 = Radix22ButterflyG1_btf2_re_reg >>> 8'd1;
  assign btf2_re = Radix22ButterflyG1_sra_temp_2[31:0];
  assign Radix22ButterflyG1_sra_temp_3 = Radix22ButterflyG1_btf2_im_reg >>> 8'd1;
  assign btf2_im = Radix22ButterflyG1_sra_temp_3[31:0];



  SDFCommutator7 u_SDFCOMMUTATOR_7 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .enb_1_1_1(enb_1_1_1),
                                    .din_7_vld_dly(din_7_vld_dly),
                                    .xf_re(xf_re),  // sfix32_En8
                                    .xf_im(xf_im),  // sfix32_En8
                                    .xf_vld(xf_vld),
                                    .dinXTwdlf_re(dinXTwdlf_re),  // sfix32_En8
                                    .dinXTwdlf_im(dinXTwdlf_im),  // sfix32_En8
                                    .dinxTwdlf_vld(dinxTwdlf_vld),
                                    .btf1_re(btf1_re),  // sfix32_En8
                                    .btf1_im(btf1_im),  // sfix32_En8
                                    .btf2_re(btf2_re),  // sfix32_En8
                                    .btf2_im(btf2_im),  // sfix32_En8
                                    .btf_vld(btf_vld),
                                    .wrData_re(wrData_re),  // sfix32_En8
                                    .wrData_im(wrData_im),  // sfix32_En8
                                    .wrAddr(wrAddr),  // ufix1
                                    .wrEnb(wrEnb),
                                    .dout_7_1_re(dout_7_1_re),  // sfix32_En8
                                    .dout_7_1_im(dout_7_1_im),  // sfix32_En8
                                    .dout_7_1_vld(dout_7_1_vld)
                                    );

endmodule  // RADIX22FFT_SDF1_7

