// -------------------------------------------------------------
// 
// File Name: D:\OFDM- HDL\simulation\baseband\v8\src\Tx\Zed_ofdm64\RADIX22FFT_SDF1_1.v
// Created: 2025-04-21 20:44:15
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RADIX22FFT_SDF1_1
// Source Path: dsphdl.IFFT/RADIX22FFT_SDF1_1
// Hierarchy Level: 3
// Model version: 3.61
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_SDF1_1
          (clk,
           reset,
           enb,
           enb_1_1_1,
           din_1_1_re_dly,
           din_1_1_im_dly,
           din_1_vld_dly,
           rd_1_Addr,
           rd_1_Enb,
           proc_1_enb,
           dout_1_1_re,
           dout_1_1_im,
           dout_1_1_vld,
           dinXTwdl_1_1_vld);


  input   clk;
  input   reset;
  input   enb;
  input   enb_1_1_1;
  input   signed [31:0] din_1_1_re_dly;  // sfix32_En8
  input   signed [31:0] din_1_1_im_dly;  // sfix32_En8
  input   din_1_vld_dly;
  input   [6:0] rd_1_Addr;  // ufix7
  input   rd_1_Enb;
  input   proc_1_enb;
  output  signed [31:0] dout_1_1_re;  // sfix32_En8
  output  signed [31:0] dout_1_1_im;  // sfix32_En8
  output  dout_1_1_vld;
  output  dinXTwdl_1_1_vld;


  reg signed [31:0] dinXTwdl_re;  // sfix32_En8
  reg signed [31:0] dinXTwdl_im;  // sfix32_En8
  reg  dinXTwdl_1_1_vld_1;
  reg  x_vld;
  wire signed [31:0] wrData_im;  // sfix32_En8
  wire [6:0] wrAddr;  // ufix7
  wire wrEnb;
  wire signed [31:0] x_im;  // sfix32_En8
  wire signed [31:0] wrData_re;  // sfix32_En8
  wire signed [31:0] x_re;  // sfix32_En8
  reg signed [32:0] Radix22ButterflyG1_btf1_re_reg;  // sfix33
  reg signed [32:0] Radix22ButterflyG1_btf1_im_reg;  // sfix33
  reg signed [32:0] Radix22ButterflyG1_btf2_re_reg;  // sfix33
  reg signed [32:0] Radix22ButterflyG1_btf2_im_reg;  // sfix33
  reg signed [31:0] Radix22ButterflyG1_x_re_dly1;  // sfix32
  reg signed [31:0] Radix22ButterflyG1_x_im_dly1;  // sfix32
  reg  Radix22ButterflyG1_x_vld_dly1;
  reg signed [31:0] Radix22ButterflyG1_dinXtwdl_re_dly1;  // sfix32
  reg signed [31:0] Radix22ButterflyG1_dinXtwdl_im_dly1;  // sfix32
  reg signed [31:0] Radix22ButterflyG1_dinXtwdl_re_dly2;  // sfix32
  reg signed [31:0] Radix22ButterflyG1_dinXtwdl_im_dly2;  // sfix32
  reg  Radix22ButterflyG1_dinXtwdl_vld_dly1;
  reg  Radix22ButterflyG1_dinXtwdl_vld_dly2;
  wire signed [32:0] Radix22ButterflyG1_btf1_re_reg_next;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_btf1_im_reg_next;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_btf2_re_reg_next;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_btf2_im_reg_next;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_add_cast;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_add_cast_1;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_sub_cast;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_sub_cast_1;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_add_cast_2;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_add_cast_3;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_sub_cast_2;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_sub_cast_3;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_sra_temp;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_sra_temp_1;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_sra_temp_2;  // sfix33_En8
  wire signed [32:0] Radix22ButterflyG1_sra_temp_3;  // sfix33_En8
  reg signed [31:0] xf_re;  // sfix32_En8
  reg signed [31:0] xf_im;  // sfix32_En8
  reg  xf_vld;
  wire signed [31:0] dinXTwdlf_re;  // sfix32_En8
  wire signed [31:0] dinXTwdlf_im;  // sfix32_En8
  wire dinxTwdlf_vld;
  wire signed [31:0] btf1_re;  // sfix32_En8
  wire signed [31:0] btf1_im;  // sfix32_En8
  wire signed [31:0] btf2_re;  // sfix32_En8
  wire signed [31:0] btf2_im;  // sfix32_En8
  reg  btf_vld;


  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        dinXTwdl_re <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          dinXTwdl_re <= din_1_1_re_dly;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        dinXTwdl_im <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          dinXTwdl_im <= din_1_1_im_dly;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        dinXTwdl_1_1_vld_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          dinXTwdl_1_1_vld_1 <= din_1_vld_dly;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld <= rd_1_Enb;
        end
      end
    end



  dataMEM_re_0_1_Wrapper_generic #(.AddrWidth(7),
                                   .DataWidth(32)
                                   )
                                 u_dataMEM_im_0_1_Wrapper (.clk(clk),
                                                           .reset(reset),
                                                           .enb(enb),
                                                           .enb_1_1_1(enb_1_1_1),
                                                           .wr_din(wrData_im),
                                                           .wr_addr(wrAddr),
                                                           .wr_en(wrEnb),
                                                           .rd_addr(rd_1_Addr),
                                                           .dout(x_im)
                                                           );

  dataMEM_re_0_1_Wrapper_generic #(.AddrWidth(7),
                                   .DataWidth(32)
                                   )
                                 u_dataMEM_re_0_1_Wrapper_generic (.clk(clk),
                                                                   .reset(reset),
                                                                   .enb(enb),
                                                                   .enb_1_1_1(enb_1_1_1),
                                                                   .wr_din(wrData_re),
                                                                   .wr_addr(wrAddr),
                                                                   .wr_en(wrEnb),
                                                                   .rd_addr(rd_1_Addr),
                                                                   .dout(x_re)
                                                                   );

  // Radix22ButterflyG1
  always @(posedge clk or posedge reset)
    begin : Radix22ButterflyG1_process
      if (reset == 1'b1) begin
        Radix22ButterflyG1_btf1_re_reg <= 33'sh000000000;
        Radix22ButterflyG1_btf1_im_reg <= 33'sh000000000;
        Radix22ButterflyG1_btf2_re_reg <= 33'sh000000000;
        Radix22ButterflyG1_btf2_im_reg <= 33'sh000000000;
        Radix22ButterflyG1_x_re_dly1 <= 32'sb00000000000000000000000000000000;
        Radix22ButterflyG1_x_im_dly1 <= 32'sb00000000000000000000000000000000;
        Radix22ButterflyG1_x_vld_dly1 <= 1'b0;
        xf_re <= 32'sb00000000000000000000000000000000;
        xf_im <= 32'sb00000000000000000000000000000000;
        xf_vld <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_re_dly1 <= 32'sb00000000000000000000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly1 <= 32'sb00000000000000000000000000000000;
        Radix22ButterflyG1_dinXtwdl_re_dly2 <= 32'sb00000000000000000000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly2 <= 32'sb00000000000000000000000000000000;
        Radix22ButterflyG1_dinXtwdl_vld_dly1 <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_vld_dly2 <= 1'b0;
        btf_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          Radix22ButterflyG1_btf1_re_reg <= Radix22ButterflyG1_btf1_re_reg_next;
          Radix22ButterflyG1_btf1_im_reg <= Radix22ButterflyG1_btf1_im_reg_next;
          Radix22ButterflyG1_btf2_re_reg <= Radix22ButterflyG1_btf2_re_reg_next;
          Radix22ButterflyG1_btf2_im_reg <= Radix22ButterflyG1_btf2_im_reg_next;
          xf_re <= Radix22ButterflyG1_x_re_dly1;
          xf_im <= Radix22ButterflyG1_x_im_dly1;
          xf_vld <= Radix22ButterflyG1_x_vld_dly1;
          btf_vld <= Radix22ButterflyG1_dinXtwdl_vld_dly2;
          Radix22ButterflyG1_dinXtwdl_vld_dly2 <= Radix22ButterflyG1_dinXtwdl_vld_dly1;
          Radix22ButterflyG1_dinXtwdl_re_dly2 <= Radix22ButterflyG1_dinXtwdl_re_dly1;
          Radix22ButterflyG1_dinXtwdl_im_dly2 <= Radix22ButterflyG1_dinXtwdl_im_dly1;
          Radix22ButterflyG1_dinXtwdl_re_dly1 <= dinXTwdl_re;
          Radix22ButterflyG1_dinXtwdl_im_dly1 <= dinXTwdl_im;
          Radix22ButterflyG1_x_re_dly1 <= x_re;
          Radix22ButterflyG1_x_im_dly1 <= x_im;
          Radix22ButterflyG1_x_vld_dly1 <= x_vld;
          Radix22ButterflyG1_dinXtwdl_vld_dly1 <= proc_1_enb && dinXTwdl_1_1_vld_1;
        end
      end
    end

  assign dinxTwdlf_vld = ( ! proc_1_enb) && dinXTwdl_1_1_vld_1;
  assign Radix22ButterflyG1_add_cast = {Radix22ButterflyG1_x_re_dly1[31], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_add_cast_1 = {Radix22ButterflyG1_dinXtwdl_re_dly2[31], Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf1_re_reg_next = Radix22ButterflyG1_add_cast + Radix22ButterflyG1_add_cast_1;
  assign Radix22ButterflyG1_sub_cast = {Radix22ButterflyG1_x_re_dly1[31], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_sub_cast_1 = {Radix22ButterflyG1_dinXtwdl_re_dly2[31], Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf2_re_reg_next = Radix22ButterflyG1_sub_cast - Radix22ButterflyG1_sub_cast_1;
  assign Radix22ButterflyG1_add_cast_2 = {Radix22ButterflyG1_x_im_dly1[31], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_add_cast_3 = {Radix22ButterflyG1_dinXtwdl_im_dly2[31], Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf1_im_reg_next = Radix22ButterflyG1_add_cast_2 + Radix22ButterflyG1_add_cast_3;
  assign Radix22ButterflyG1_sub_cast_2 = {Radix22ButterflyG1_x_im_dly1[31], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_sub_cast_3 = {Radix22ButterflyG1_dinXtwdl_im_dly2[31], Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf2_im_reg_next = Radix22ButterflyG1_sub_cast_2 - Radix22ButterflyG1_sub_cast_3;
  assign dinXTwdlf_re = dinXTwdl_re;
  assign dinXTwdlf_im = dinXTwdl_im;
  assign Radix22ButterflyG1_sra_temp = Radix22ButterflyG1_btf1_re_reg >>> 8'd1;
  assign btf1_re = Radix22ButterflyG1_sra_temp[31:0];
  assign Radix22ButterflyG1_sra_temp_1 = Radix22ButterflyG1_btf1_im_reg >>> 8'd1;
  assign btf1_im = Radix22ButterflyG1_sra_temp_1[31:0];
  assign Radix22ButterflyG1_sra_temp_2 = Radix22ButterflyG1_btf2_re_reg >>> 8'd1;
  assign btf2_re = Radix22ButterflyG1_sra_temp_2[31:0];
  assign Radix22ButterflyG1_sra_temp_3 = Radix22ButterflyG1_btf2_im_reg >>> 8'd1;
  assign btf2_im = Radix22ButterflyG1_sra_temp_3[31:0];



  SDFCommutator1 u_SDFCOMMUTATOR_1 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .enb_1_1_1(enb_1_1_1),
                                    .din_1_vld_dly(din_1_vld_dly),
                                    .xf_re(xf_re),  // sfix32_En8
                                    .xf_im(xf_im),  // sfix32_En8
                                    .xf_vld(xf_vld),
                                    .dinXTwdlf_re(dinXTwdlf_re),  // sfix32_En8
                                    .dinXTwdlf_im(dinXTwdlf_im),  // sfix32_En8
                                    .dinxTwdlf_vld(dinxTwdlf_vld),
                                    .btf1_re(btf1_re),  // sfix32_En8
                                    .btf1_im(btf1_im),  // sfix32_En8
                                    .btf2_re(btf2_re),  // sfix32_En8
                                    .btf2_im(btf2_im),  // sfix32_En8
                                    .btf_vld(btf_vld),
                                    .wrData_re(wrData_re),  // sfix32_En8
                                    .wrData_im(wrData_im),  // sfix32_En8
                                    .wrAddr(wrAddr),  // ufix7
                                    .wrEnb(wrEnb),
                                    .dout_1_1_re(dout_1_1_re),  // sfix32_En8
                                    .dout_1_1_im(dout_1_1_im),  // sfix32_En8
                                    .dout_1_1_vld(dout_1_1_vld)
                                    );

  assign dinXTwdl_1_1_vld = dinXTwdl_1_1_vld_1;

endmodule  // RADIX22FFT_SDF1_1

