// -------------------------------------------------------------
// 
// File Name: D:\OFDM- HDL\simulation\baseband\v8\src\Tx\Zed_ofdm64\RADIX22FFT_CTRL1_8.v
// Created: 2025-04-21 20:44:15
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RADIX22FFT_CTRL1_8
// Source Path: dsphdl.IFFT/RADIX22FFT_CTRL1_8
// Hierarchy Level: 3
// Model version: 3.61
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_CTRL1_8
          (clk,
           reset,
           enb,
           dout_7_1_vld,
           dinXTwdl_8_1_vld,
           rd_8_Addr,
           rd_8_Enb,
           proc_8_enb,
           multiply_8_J);


  input   clk;
  input   reset;
  input   enb;
  input   dout_7_1_vld;
  input   dinXTwdl_8_1_vld;
  output  rd_8_Addr;
  output  rd_8_Enb;
  output  proc_8_enb;
  output  multiply_8_J;


  reg [1:0] SDFController_wrState;  // ufix2
  reg [1:0] SDFController_rdState;  // ufix2
  reg  SDFController_rdAddr_reg;  // ufix1
  reg [1:0] SDFController_multjState;  // ufix2
  reg [1:0] SDFController_wrState_next;  // ufix2
  reg [1:0] SDFController_rdState_next;  // ufix2
  reg  SDFController_rdAddr_reg_next;  // ufix1
  reg [1:0] SDFController_multjState_next;  // ufix2
  reg  rd_8_Addr_1;
  reg  rd_8_Enb_1;
  reg  proc_8_enb_1;
  reg  multiply_8_J_1;


  // SDFController
  always @(posedge clk or posedge reset)
    begin : SDFController_process
      if (reset == 1'b1) begin
        SDFController_rdAddr_reg <= 1'b0;
        SDFController_wrState <= 2'b00;
        SDFController_rdState <= 2'b00;
        SDFController_multjState <= 2'b00;
      end
      else begin
        if (enb) begin
          SDFController_wrState <= SDFController_wrState_next;
          SDFController_rdState <= SDFController_rdState_next;
          SDFController_rdAddr_reg <= SDFController_rdAddr_reg_next;
          SDFController_multjState <= SDFController_multjState_next;
        end
      end
    end

  always @(SDFController_multjState, SDFController_rdAddr_reg, SDFController_rdState,
       SDFController_wrState, dinXTwdl_8_1_vld, dout_7_1_vld) begin
    SDFController_rdState_next = SDFController_rdState;
    SDFController_rdAddr_reg_next = SDFController_rdAddr_reg;
    SDFController_multjState_next = SDFController_multjState;
    case ( SDFController_multjState)
      2'b00 :
        begin
          SDFController_multjState_next = 2'b00;
          multiply_8_J_1 = 1'b0;
          if (SDFController_rdState == 2'b01) begin
            SDFController_multjState_next = 2'b01;
          end
        end
      2'b01 :
        begin
          multiply_8_J_1 = 1'b0;
          if (SDFController_rdState == 2'b00) begin
            SDFController_multjState_next = 2'b10;
          end
        end
      2'b10 :
        begin
          multiply_8_J_1 = 1'b0;
          SDFController_multjState_next = 2'b11;
        end
      2'b11 :
        begin
          multiply_8_J_1 = 1'b1;
          SDFController_multjState_next = 2'b00;
        end
      default :
        begin
          SDFController_multjState_next = 2'b00;
          multiply_8_J_1 = 1'b0;
        end
    endcase
    case ( SDFController_rdState)
      2'b00 :
        begin
          SDFController_rdState_next = 2'b00;
          SDFController_rdAddr_reg_next = 1'b0;
          rd_8_Enb_1 = 1'b0;
          if ((SDFController_wrState == 2'b11) && dout_7_1_vld) begin
            SDFController_rdState_next = 2'b01;
            rd_8_Enb_1 = dinXTwdl_8_1_vld;
          end
        end
      2'b01 :
        begin
          rd_8_Enb_1 = dinXTwdl_8_1_vld;
          if (dinXTwdl_8_1_vld) begin
            SDFController_rdState_next = 2'b00;
          end
        end
      default :
        begin
          SDFController_rdState_next = 2'b00;
          SDFController_rdAddr_reg_next = 1'b0;
          rd_8_Enb_1 = 1'b0;
        end
    endcase
    case ( SDFController_wrState)
      2'b00 :
        begin
          SDFController_wrState_next = 2'b00;
          proc_8_enb_1 = 1'b0;
          if (dout_7_1_vld) begin
            SDFController_wrState_next = 2'b11;
          end
        end
      2'b11 :
        begin
          SDFController_wrState_next = 2'b11;
          proc_8_enb_1 = 1'b0;
          if (dout_7_1_vld) begin
            SDFController_wrState_next = 2'b10;
            proc_8_enb_1 = 1'b1;
          end
        end
      2'b10 :
        begin
          proc_8_enb_1 = 1'b0;
          SDFController_wrState_next = 2'b10;
          if (dout_7_1_vld) begin
            SDFController_wrState_next = 2'b11;
          end
        end
      default :
        begin
          SDFController_wrState_next = 2'b00;
          proc_8_enb_1 = 1'b0;
        end
    endcase
    rd_8_Addr_1 = SDFController_rdAddr_reg;
  end



  assign rd_8_Addr = rd_8_Addr_1;

  assign rd_8_Enb = rd_8_Enb_1;

  assign proc_8_enb = proc_8_enb_1;

  assign multiply_8_J = multiply_8_J_1;

endmodule  // RADIX22FFT_CTRL1_8

