// -------------------------------------------------------------
// 
// File Name: D:\OFDM- HDL\simulation\baseband\v8\src\Tx\Zed_ofdm64\SimpleDualPortRAM_generic.v
// Created: 2025-04-21 20:44:15
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: SimpleDualPortRAM_generic
// Source Path: simpleDualPortRam_Wrapper_generic/SimpleDualPortRAM_generic
// Hierarchy Level: 4
// Model version: 3.61
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SimpleDualPortRAM_generic
          (clk,
           wr_din_re,
           wr_din_im,
           wr_addr,
           wr_en,
           rd_addr,
           dout_re,
           dout_im);

  parameter integer AddrWidth  = 1;
  parameter integer DataWidth  = 1;

  input   clk;
  input   signed [DataWidth - 1:0] wr_din_re;  // parameterized width
  input   signed [DataWidth - 1:0] wr_din_im;  // parameterized width
  input   [AddrWidth - 1:0] wr_addr;  // parameterized width
  input   wr_en;  // ufix1
  input   [AddrWidth - 1:0] rd_addr;  // parameterized width
  output  signed [DataWidth - 1:0] dout_re;  // parameterized width
  output  signed [DataWidth - 1:0] dout_im;  // parameterized width


  reg  [DataWidth*2 - 1:0] ram [2**AddrWidth - 1:0];
  reg  [DataWidth*2 - 1:0] data_int;


  always @(posedge clk)
    begin : SimpleDualPortRAM_generic_process
      if (wr_en == 1'b1) begin
        ram[wr_addr] <= {wr_din_re, wr_din_im};
      end
      data_int <= ram[rd_addr];
    end

  assign dout_re = data_int[DataWidth*2-1:DataWidth];
  assign dout_im = data_int[DataWidth-1:0];

endmodule  // SimpleDualPortRAM_generic

