// -------------------------------------------------------------
// 
// File Name: D:\OFDM- HDL\simulation\baseband\v8\src\Tx\Zed_ofdm64\TWDLROM_3_1.v
// Created: 2025-04-21 20:44:15
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: TWDLROM_3_1
// Source Path: dsphdl.IFFT/TWDLROM_3_1
// Hierarchy Level: 3
// Model version: 3.61
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module TWDLROM_3_1
          (clk,
           reset,
           enb,
           dout_2_1_vld,
           twdl_3_1_re,
           twdl_3_1_im);


  input   clk;
  input   reset;
  input   enb;
  input   dout_2_1_vld;
  output  signed [31:0] twdl_3_1_re;  // sfix32_En30
  output  signed [31:0] twdl_3_1_im;  // sfix32_En30


  reg [5:0] Radix22TwdlMapping_cnt;  // ufix6
  reg [1:0] Radix22TwdlMapping_phase;  // ufix2
  reg [2:0] Radix22TwdlMapping_octantReg1;  // ufix3
  reg [7:0] Radix22TwdlMapping_twdlAddr_raw;  // ufix8
  reg [4:0] Radix22TwdlMapping_twdlAddrMap;  // ufix5
  reg  Radix22TwdlMapping_twdl45Reg;
  reg  Radix22TwdlMapping_dvldReg1;
  reg  Radix22TwdlMapping_dvldReg2;
  reg [5:0] Radix22TwdlMapping_cnt_next;  // ufix6
  reg [1:0] Radix22TwdlMapping_phase_next;  // ufix2
  reg [2:0] Radix22TwdlMapping_octantReg1_next;  // ufix3
  reg [7:0] Radix22TwdlMapping_twdlAddr_raw_next;  // ufix8
  reg [4:0] Radix22TwdlMapping_twdlAddrMap_next;  // ufix5
  reg  Radix22TwdlMapping_twdl45Reg_next;
  reg  Radix22TwdlMapping_dvldReg1_next;
  reg  Radix22TwdlMapping_dvldReg2_next;
  reg [4:0] twdlAddr;  // ufix5
  reg  twdlAddrVld;
  reg [2:0] twdlOctant;  // ufix3
  reg  twdl45;
  wire signed [31:0] Twiddle_re_table_data [0:31];  // sfix32_En30 [32]
  wire signed [31:0] twiddleS_re;  // sfix32_En30
  reg signed [31:0] twiddleReg_re;  // sfix32_En30
  wire signed [31:0] Twiddle_im_table_data [0:31];  // sfix32_En30 [32]
  wire signed [31:0] twiddleS_im;  // sfix32_En30
  reg signed [31:0] twiddleReg_im;  // sfix32_En30
  reg [2:0] twdlOctantReg;  // ufix3
  reg  twdl45Reg;
  reg signed [31:0] twdl_3_1_re_1;  // sfix32_En30
  reg signed [31:0] twdl_3_1_im_1;  // sfix32_En30
  reg [2:0] Radix22TwdlMapping_octant;  // ufix3
  reg [7:0] Radix22TwdlMapping_cnt_cast;  // ufix8
  reg signed [17:0] Radix22TwdlMapping_sub_cast;  // sfix18_En5
  reg signed [17:0] Radix22TwdlMapping_sub_temp;  // sfix18_En5
  reg signed [9:0] Radix22TwdlMapping_sub_temp_0;  // sfix10
  reg signed [9:0] Radix22TwdlMapping_sub_temp_1;  // sfix10
  reg signed [17:0] Radix22TwdlMapping_sub_cast_0;  // sfix18_En5
  reg signed [17:0] Radix22TwdlMapping_sub_temp_2;  // sfix18_En5
  reg signed [17:0] Radix22TwdlMapping_sub_cast_1;  // sfix18_En5
  reg signed [17:0] Radix22TwdlMapping_sub_temp_3;  // sfix18_En5
  reg [7:0] Radix22TwdlMapping_t_0_0;  // ufix8
  reg signed [9:0] Radix22TwdlMapping_t_1;  // sfix10
  reg signed [9:0] Radix22TwdlMapping_t_2_0;  // sfix10
  reg signed [31:0] Radix22TwdlOctCorr_twdlIn_re;  // sfix32_En30
  reg signed [31:0] Radix22TwdlOctCorr_twdlIn_im;  // sfix32_En30
  reg signed [32:0] Radix22TwdlOctCorr_cast;  // sfix33_En30
  reg signed [32:0] Radix22TwdlOctCorr_cast_0;  // sfix33_En30
  reg signed [32:0] Radix22TwdlOctCorr_cast_1;  // sfix33_En30
  reg signed [32:0] Radix22TwdlOctCorr_cast_2;  // sfix33_En30
  reg signed [32:0] Radix22TwdlOctCorr_cast_3;  // sfix33_En30
  reg signed [32:0] Radix22TwdlOctCorr_cast_4;  // sfix33_En30
  reg signed [32:0] Radix22TwdlOctCorr_cast_5;  // sfix33_En30
  reg signed [32:0] Radix22TwdlOctCorr_cast_6;  // sfix33_En30
  reg signed [32:0] Radix22TwdlOctCorr_cast_7;  // sfix33_En30
  reg signed [32:0] Radix22TwdlOctCorr_cast_8;  // sfix33_En30
  reg signed [32:0] Radix22TwdlOctCorr_cast_9;  // sfix33_En30
  reg signed [32:0] Radix22TwdlOctCorr_cast_10;  // sfix33_En30


  // Radix22TwdlMapping
  always @(posedge clk or posedge reset)
    begin : Radix22TwdlMapping_process
      if (reset == 1'b1) begin
        Radix22TwdlMapping_octantReg1 <= 3'b000;
        Radix22TwdlMapping_twdlAddr_raw <= 8'b00000000;
        Radix22TwdlMapping_twdlAddrMap <= 5'b00000;
        Radix22TwdlMapping_twdl45Reg <= 1'b0;
        Radix22TwdlMapping_dvldReg1 <= 1'b0;
        Radix22TwdlMapping_dvldReg2 <= 1'b0;
        Radix22TwdlMapping_cnt <= 6'b000000;
        Radix22TwdlMapping_phase <= 2'b00;
      end
      else begin
        if (enb) begin
          Radix22TwdlMapping_cnt <= Radix22TwdlMapping_cnt_next;
          Radix22TwdlMapping_phase <= Radix22TwdlMapping_phase_next;
          Radix22TwdlMapping_octantReg1 <= Radix22TwdlMapping_octantReg1_next;
          Radix22TwdlMapping_twdlAddr_raw <= Radix22TwdlMapping_twdlAddr_raw_next;
          Radix22TwdlMapping_twdlAddrMap <= Radix22TwdlMapping_twdlAddrMap_next;
          Radix22TwdlMapping_twdl45Reg <= Radix22TwdlMapping_twdl45Reg_next;
          Radix22TwdlMapping_dvldReg1 <= Radix22TwdlMapping_dvldReg1_next;
          Radix22TwdlMapping_dvldReg2 <= Radix22TwdlMapping_dvldReg2_next;
        end
      end
    end

  always @(Radix22TwdlMapping_cnt, Radix22TwdlMapping_dvldReg1,
       Radix22TwdlMapping_dvldReg2, Radix22TwdlMapping_octantReg1,
       Radix22TwdlMapping_phase, Radix22TwdlMapping_twdl45Reg,
       Radix22TwdlMapping_twdlAddrMap, Radix22TwdlMapping_twdlAddr_raw,
       dout_2_1_vld) begin
    Radix22TwdlMapping_sub_temp = 18'sb000000000000000000;
    Radix22TwdlMapping_sub_temp_0 = 10'sb0000000000;
    Radix22TwdlMapping_sub_temp_1 = 10'sb0000000000;
    Radix22TwdlMapping_sub_temp_2 = 18'sb000000000000000000;
    Radix22TwdlMapping_sub_temp_3 = 18'sb000000000000000000;
    Radix22TwdlMapping_sub_cast_1 = 18'sb000000000000000000;
    Radix22TwdlMapping_t_0_0 = 8'b00000000;
    Radix22TwdlMapping_cnt_cast = 8'b00000000;
    Radix22TwdlMapping_sub_cast_0 = 18'sb000000000000000000;
    Radix22TwdlMapping_t_2_0 = 10'sb0000000000;
    Radix22TwdlMapping_t_1 = 10'sb0000000000;
    Radix22TwdlMapping_sub_cast = 18'sb000000000000000000;
    Radix22TwdlMapping_cnt_next = Radix22TwdlMapping_cnt;
    Radix22TwdlMapping_phase_next = Radix22TwdlMapping_phase;
    Radix22TwdlMapping_dvldReg2_next = Radix22TwdlMapping_dvldReg1;
    Radix22TwdlMapping_dvldReg1_next = dout_2_1_vld;
    case ( Radix22TwdlMapping_twdlAddr_raw)
      8'b00100000 :
        begin
          Radix22TwdlMapping_octant = 3'b000;
          Radix22TwdlMapping_twdl45Reg_next = 1'b1;
        end
      8'b01000000 :
        begin
          Radix22TwdlMapping_octant = 3'b001;
          Radix22TwdlMapping_twdl45Reg_next = 1'b0;
        end
      8'b01100000 :
        begin
          Radix22TwdlMapping_octant = 3'b010;
          Radix22TwdlMapping_twdl45Reg_next = 1'b1;
        end
      8'b10000000 :
        begin
          Radix22TwdlMapping_octant = 3'b011;
          Radix22TwdlMapping_twdl45Reg_next = 1'b0;
        end
      8'b10100000 :
        begin
          Radix22TwdlMapping_octant = 3'b100;
          Radix22TwdlMapping_twdl45Reg_next = 1'b1;
        end
      default :
        begin
          Radix22TwdlMapping_octant = Radix22TwdlMapping_twdlAddr_raw[7:5];
          Radix22TwdlMapping_twdl45Reg_next = 1'b0;
        end
    endcase
    Radix22TwdlMapping_octantReg1_next = Radix22TwdlMapping_octant;
    case ( Radix22TwdlMapping_octant)
      3'b000 :
        begin
          Radix22TwdlMapping_twdlAddrMap_next = Radix22TwdlMapping_twdlAddr_raw[4:0];
        end
      3'b001 :
        begin
          Radix22TwdlMapping_t_1 = {2'b0, Radix22TwdlMapping_twdlAddr_raw};
          Radix22TwdlMapping_sub_temp_0 = 10'sb0001000000 - Radix22TwdlMapping_t_1;
          Radix22TwdlMapping_twdlAddrMap_next = Radix22TwdlMapping_sub_temp_0[4:0];
        end
      3'b010 :
        begin
          Radix22TwdlMapping_t_2_0 = {2'b0, Radix22TwdlMapping_twdlAddr_raw};
          Radix22TwdlMapping_sub_temp_1 = Radix22TwdlMapping_t_2_0 - 10'sb0001000000;
          Radix22TwdlMapping_twdlAddrMap_next = Radix22TwdlMapping_sub_temp_1[4:0];
        end
      3'b011 :
        begin
          Radix22TwdlMapping_sub_cast_0 = {5'b0, {Radix22TwdlMapping_twdlAddr_raw, 5'b00000}};
          Radix22TwdlMapping_sub_temp_2 = 18'sb000001000000000000 - Radix22TwdlMapping_sub_cast_0;
          Radix22TwdlMapping_twdlAddrMap_next = Radix22TwdlMapping_sub_temp_2[9:5];
        end
      3'b100 :
        begin
          Radix22TwdlMapping_sub_cast_1 = {5'b0, {Radix22TwdlMapping_twdlAddr_raw, 5'b00000}};
          Radix22TwdlMapping_sub_temp_3 = Radix22TwdlMapping_sub_cast_1 - 18'sb000001000000000000;
          Radix22TwdlMapping_twdlAddrMap_next = Radix22TwdlMapping_sub_temp_3[9:5];
        end
      default :
        begin
          Radix22TwdlMapping_sub_cast = {5'b0, {Radix22TwdlMapping_twdlAddr_raw, 5'b00000}};
          Radix22TwdlMapping_sub_temp = 18'sb000001100000000000 - Radix22TwdlMapping_sub_cast;
          Radix22TwdlMapping_twdlAddrMap_next = Radix22TwdlMapping_sub_temp[9:5];
        end
    endcase
    if (Radix22TwdlMapping_phase == 2'b00) begin
      Radix22TwdlMapping_twdlAddr_raw_next = 8'b00000000;
    end
    else if (Radix22TwdlMapping_phase == 2'b01) begin
      Radix22TwdlMapping_t_0_0 = {2'b0, Radix22TwdlMapping_cnt};
      Radix22TwdlMapping_twdlAddr_raw_next = Radix22TwdlMapping_t_0_0 <<< 8'd1;
    end
    else if (Radix22TwdlMapping_phase == 2'b10) begin
      Radix22TwdlMapping_twdlAddr_raw_next = {2'b0, Radix22TwdlMapping_cnt};
    end
    else begin
      Radix22TwdlMapping_cnt_cast = {2'b0, Radix22TwdlMapping_cnt};
      Radix22TwdlMapping_twdlAddr_raw_next = (Radix22TwdlMapping_cnt_cast <<< 8'd1) + Radix22TwdlMapping_cnt_cast;
    end
    if (dout_2_1_vld && (Radix22TwdlMapping_cnt > 6'b111110)) begin
      Radix22TwdlMapping_phase_next = Radix22TwdlMapping_phase + 2'b01;
    end
    if (dout_2_1_vld) begin
      Radix22TwdlMapping_cnt_next = Radix22TwdlMapping_cnt + 6'b000001;
    end
    twdlAddr = Radix22TwdlMapping_twdlAddrMap;
    twdlAddrVld = Radix22TwdlMapping_dvldReg2;
    twdlOctant = Radix22TwdlMapping_octantReg1;
    twdl45 = Radix22TwdlMapping_twdl45Reg;
  end



  // Twiddle ROM1
  assign Twiddle_re_table_data[0] = 32'sb01000000000000000000000000000000;
  assign Twiddle_re_table_data[1] = 32'sb00111111111110110001000011000001;
  assign Twiddle_re_table_data[2] = 32'sb00111111111011000100001111000111;
  assign Twiddle_re_table_data[3] = 32'sb00111111110100111001101101011010;
  assign Twiddle_re_table_data[4] = 32'sb00111111101100010001101101001000;
  assign Twiddle_re_table_data[5] = 32'sb00111111100001001100100011100010;
  assign Twiddle_re_table_data[6] = 32'sb00111111010011101010101011111110;
  assign Twiddle_re_table_data[7] = 32'sb00111111000011101100100111110101;
  assign Twiddle_re_table_data[8] = 32'sb00111110110001010010111110100000;
  assign Twiddle_re_table_data[9] = 32'sb00111110011100011110011101011001;
  assign Twiddle_re_table_data[10] = 32'sb00111110000101001111110111110111;
  assign Twiddle_re_table_data[11] = 32'sb00111101101011101000000111001111;
  assign Twiddle_re_table_data[12] = 32'sb00111101001111101000001010101110;
  assign Twiddle_re_table_data[13] = 32'sb00111100110001010001000111011001;
  assign Twiddle_re_table_data[14] = 32'sb00111100010000100100001000001010;
  assign Twiddle_re_table_data[15] = 32'sb00111011101101100010011101101110;
  assign Twiddle_re_table_data[16] = 32'sb00111011001000001101011110011110;
  assign Twiddle_re_table_data[17] = 32'sb00111010100000100110100110100011;
  assign Twiddle_re_table_data[18] = 32'sb00111001110110101111010111101000;
  assign Twiddle_re_table_data[19] = 32'sb00111001001010101001011001000010;
  assign Twiddle_re_table_data[20] = 32'sb00111000011100010110010111100011;
  assign Twiddle_re_table_data[21] = 32'sb00110111101011111000000101011001;
  assign Twiddle_re_table_data[22] = 32'sb00110110111001010000011010001010;
  assign Twiddle_re_table_data[23] = 32'sb00110110000100100001010010110000;
  assign Twiddle_re_table_data[24] = 32'sb00110101001101101100110001010010;
  assign Twiddle_re_table_data[25] = 32'sb00110100010100110100111101000001;
  assign Twiddle_re_table_data[26] = 32'sb00110011011001111100000010010000;
  assign Twiddle_re_table_data[27] = 32'sb00110010011101000100010010010011;
  assign Twiddle_re_table_data[28] = 32'sb00110001011110010000000011010110;
  assign Twiddle_re_table_data[29] = 32'sb00110000011101100001110000011000;
  assign Twiddle_re_table_data[30] = 32'sb00101111011010111011111001000101;
  assign Twiddle_re_table_data[31] = 32'sb00101110010110100001000001110000;
  assign twiddleS_re = Twiddle_re_table_data[twdlAddr];



  always @(posedge clk or posedge reset)
    begin : TWIDDLEROM_RE_process
      if (reset == 1'b1) begin
        twiddleReg_re <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          twiddleReg_re <= twiddleS_re;
        end
      end
    end



  // Twiddle ROM2
  assign Twiddle_im_table_data[0] = 32'sb00000000000000000000000000000000;
  assign Twiddle_im_table_data[1] = 32'sb11111110011011011110101010100001;
  assign Twiddle_im_table_data[2] = 32'sb11111100110111000001001101000010;
  assign Twiddle_im_table_data[3] = 32'sb11111011010010101011011111011011;
  assign Twiddle_im_table_data[4] = 32'sb11111001101110100001011001010001;
  assign Twiddle_im_table_data[5] = 32'sb11111000001010100110110001101010;
  assign Twiddle_im_table_data[6] = 32'sb11110110100110111111011111001001;
  assign Twiddle_im_table_data[7] = 32'sb11110101000011101111010111011110;
  assign Twiddle_im_table_data[8] = 32'sb11110011100000111010001111100010;
  assign Twiddle_im_table_data[9] = 32'sb11110001111110100011111011001011;
  assign Twiddle_im_table_data[10] = 32'sb11110000011100110000001101000010;
  assign Twiddle_im_table_data[11] = 32'sb11101110111011100010110110011101;
  assign Twiddle_im_table_data[12] = 32'sb11101101011010111111100111010001;
  assign Twiddle_im_table_data[13] = 32'sb11101011111011001010001101101100;
  assign Twiddle_im_table_data[14] = 32'sb11101010011100000110010110001010;
  assign Twiddle_im_table_data[15] = 32'sb11101000111101110111101011001111;
  assign Twiddle_im_table_data[16] = 32'sb11100111100000100001110101011001;
  assign Twiddle_im_table_data[17] = 32'sb11100110000100001000011010111100;
  assign Twiddle_im_table_data[18] = 32'sb11100100101000101110111111110110;
  assign Twiddle_im_table_data[19] = 32'sb11100011001110011001000101100111;
  assign Twiddle_im_table_data[20] = 32'sb11100001110101001010001011001000;
  assign Twiddle_im_table_data[21] = 32'sb11100000011101000101101100100100;
  assign Twiddle_im_table_data[22] = 32'sb11011111000110001111000011001110;
  assign Twiddle_im_table_data[23] = 32'sb11011101110000101001100101011000;
  assign Twiddle_im_table_data[24] = 32'sb11011100011100011000100110001101;
  assign Twiddle_im_table_data[25] = 32'sb11011011001001011111010101100110;
  assign Twiddle_im_table_data[26] = 32'sb11011001111000000001000000000110;
  assign Twiddle_im_table_data[27] = 32'sb11011000101000000000101110101110;
  assign Twiddle_im_table_data[28] = 32'sb11010111011001100001100110110110;
  assign Twiddle_im_table_data[29] = 32'sb11010110001100100110101010001000;
  assign Twiddle_im_table_data[30] = 32'sb11010101000001010010110110010111;
  assign Twiddle_im_table_data[31] = 32'sb11010011110111101001000101010110;
  assign twiddleS_im = Twiddle_im_table_data[twdlAddr];



  always @(posedge clk or posedge reset)
    begin : TWIDDLEROM_IM_process
      if (reset == 1'b1) begin
        twiddleReg_im <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          twiddleReg_im <= twiddleS_im;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        twdlOctantReg <= 3'b000;
      end
      else begin
        if (enb) begin
          twdlOctantReg <= twdlOctant;
        end
      end
    end



  always @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        twdl45Reg <= 1'b0;
      end
      else begin
        if (enb) begin
          twdl45Reg <= twdl45;
        end
      end
    end



  // Radix22TwdlOctCorr
  always @(twdl45Reg, twdlOctantReg, twiddleReg_im, twiddleReg_re) begin
    Radix22TwdlOctCorr_cast_0 = 33'sh000000000;
    Radix22TwdlOctCorr_cast_2 = 33'sh000000000;
    Radix22TwdlOctCorr_cast_4 = 33'sh000000000;
    Radix22TwdlOctCorr_cast_6 = 33'sh000000000;
    Radix22TwdlOctCorr_cast_8 = 33'sh000000000;
    Radix22TwdlOctCorr_cast_10 = 33'sh000000000;
    Radix22TwdlOctCorr_cast_3 = 33'sh000000000;
    Radix22TwdlOctCorr_cast_9 = 33'sh000000000;
    Radix22TwdlOctCorr_cast_1 = 33'sh000000000;
    Radix22TwdlOctCorr_cast_7 = 33'sh000000000;
    Radix22TwdlOctCorr_cast = 33'sh000000000;
    Radix22TwdlOctCorr_cast_5 = 33'sh000000000;
    Radix22TwdlOctCorr_twdlIn_re = twiddleReg_re;
    Radix22TwdlOctCorr_twdlIn_im = twiddleReg_im;
    if (twdl45Reg) begin
      case ( twdlOctantReg)
        3'b000 :
          begin
            Radix22TwdlOctCorr_twdlIn_re = 32'sb00101101010000010011110011001101;
            Radix22TwdlOctCorr_twdlIn_im = 32'sb11010010101111101100001100110011;
          end
        3'b010 :
          begin
            Radix22TwdlOctCorr_twdlIn_re = 32'sb11010010101111101100001100110011;
            Radix22TwdlOctCorr_twdlIn_im = 32'sb11010010101111101100001100110011;
          end
        3'b100 :
          begin
            Radix22TwdlOctCorr_twdlIn_re = 32'sb11010010101111101100001100110011;
            Radix22TwdlOctCorr_twdlIn_im = 32'sb00101101010000010011110011001101;
          end
        default :
          begin
            Radix22TwdlOctCorr_twdlIn_re = 32'sb00101101010000010011110011001101;
            Radix22TwdlOctCorr_twdlIn_im = 32'sb11010010101111101100001100110011;
          end
      endcase
    end
    else begin
      case ( twdlOctantReg)
        3'b000 :
          begin
          end
        3'b001 :
          begin
            Radix22TwdlOctCorr_cast = {twiddleReg_im[31], twiddleReg_im};
            Radix22TwdlOctCorr_cast_0 =  - (Radix22TwdlOctCorr_cast);
            Radix22TwdlOctCorr_twdlIn_re = Radix22TwdlOctCorr_cast_0[31:0];
            Radix22TwdlOctCorr_cast_5 = {twiddleReg_re[31], twiddleReg_re};
            Radix22TwdlOctCorr_cast_6 =  - (Radix22TwdlOctCorr_cast_5);
            Radix22TwdlOctCorr_twdlIn_im = Radix22TwdlOctCorr_cast_6[31:0];
          end
        3'b010 :
          begin
            Radix22TwdlOctCorr_twdlIn_re = twiddleReg_im;
            Radix22TwdlOctCorr_cast_7 = {twiddleReg_re[31], twiddleReg_re};
            Radix22TwdlOctCorr_cast_8 =  - (Radix22TwdlOctCorr_cast_7);
            Radix22TwdlOctCorr_twdlIn_im = Radix22TwdlOctCorr_cast_8[31:0];
          end
        3'b011 :
          begin
            Radix22TwdlOctCorr_cast_1 = {twiddleReg_re[31], twiddleReg_re};
            Radix22TwdlOctCorr_cast_2 =  - (Radix22TwdlOctCorr_cast_1);
            Radix22TwdlOctCorr_twdlIn_re = Radix22TwdlOctCorr_cast_2[31:0];
            Radix22TwdlOctCorr_twdlIn_im = twiddleReg_im;
          end
        3'b100 :
          begin
            Radix22TwdlOctCorr_cast_3 = {twiddleReg_re[31], twiddleReg_re};
            Radix22TwdlOctCorr_cast_4 =  - (Radix22TwdlOctCorr_cast_3);
            Radix22TwdlOctCorr_twdlIn_re = Radix22TwdlOctCorr_cast_4[31:0];
            Radix22TwdlOctCorr_cast_9 = {twiddleReg_im[31], twiddleReg_im};
            Radix22TwdlOctCorr_cast_10 =  - (Radix22TwdlOctCorr_cast_9);
            Radix22TwdlOctCorr_twdlIn_im = Radix22TwdlOctCorr_cast_10[31:0];
          end
        default :
          begin
            Radix22TwdlOctCorr_twdlIn_re = twiddleReg_im;
            Radix22TwdlOctCorr_twdlIn_im = twiddleReg_re;
          end
      endcase
    end
    twdl_3_1_re_1 = Radix22TwdlOctCorr_twdlIn_re;
    twdl_3_1_im_1 = Radix22TwdlOctCorr_twdlIn_im;
  end



  assign twdl_3_1_re = twdl_3_1_re_1;

  assign twdl_3_1_im = twdl_3_1_im_1;

endmodule  // TWDLROM_3_1

