// -------------------------------------------------------------
// 
// File Name: D:\OFDM- HDL\simulation\baseband\v8\src\Tx\Zed_ofdm64\Wrap_To_Zero.v
// Created: 2025-04-21 20:44:15
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Wrap_To_Zero
// Source Path: Zed_ofdm64/top_all/tx_top/OFDM_TXSYS/Counter Limited/Wrap To Zero
// Hierarchy Level: 2
// Model version: 3.61
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Wrap_To_Zero
          (U,
           Y);


  input   [15:0] U;  // uint16
  output  [15:0] Y;  // uint16


  wire switch_compare_1;
  wire [15:0] Constant_out1;  // uint16
  wire [15:0] FixPt_Switch_out1;  // uint16

  // U(k)


  assign switch_compare_1 = U > 16'b0000000100011111;



  assign Constant_out1 = 16'b0000000000000000;



  assign FixPt_Switch_out1 = (switch_compare_1 == 1'b0 ? U :
              Constant_out1);



  assign Y = FixPt_Switch_out1;

endmodule  // Wrap_To_Zero

